- scripts/initialize_local_test_node.sh
> Fix initialize local node script

- loadtest/sign.go
Minor fix on the load test scripts since we've enabled sequence number decorator
> Use sequence number in tx signing logics

- app/upgrades.go
Add upgrade handler for code changes in https://github.com/sei-protocol/sei-chain/pull/27
> Add ignite cli removal upgrade

- scripts/oracle/mock_price_feed.py
Keyring password is enabled on remote boxes
> pass password in when running oracle script

- app/upgrades.go
Cherry pick https://github.com/sei-protocol/sei-chain/commit/776f64eae55e06c945f722d7ef32e3e6d4f27291
> Cherry pick  1.0.5beta upgrade handler name fix

- app/app.go
- wasmbinding/queries.go
- wasmbinding/query_plugin.go
- wasmbinding/test/query_test.go
- wasmbinding/wasm.go
- x/epoch/client/wasm/bindings/queries.go
- x/epoch/client/wasm/query.go
Tested with localsei, I'll update with another commit adding some tests shortly
> [epoch][wasmbindings] Add epoch query wasmbinding

- wasmbinding/encoder.go
- wasmbinding/test/encoder_test.go
- x/dex/client/wasm/encoder.go
Still need to do localsei testing, but have modified the unit tests to match the new encoder pattern
> [wasmbindings][dex] Refactored encoders to be more modular/extensible

- cmd/seid/cmd/root.go
To enable frontend testing. Remove before mainnet
> Allow unsafe cors

- x/dex/client/cli/query.go
- Small PR fix to add registered pair queries to commands
> Add registered pairs query to cmds

- wasmbinding/queries.go
- x/oracle/types/params.go
> Allow Oracle price to be submitted for ETH

- x/dex/client/utils/utils.go
- Fixes json tag for asset list in asset list proposal json
> Fix asset list proposal json

- loadtest/config.json
- loadtest/main.go
- scripts/initialize_local_test_node.sh
- Use json file instead of cmd flags to specify load testing configs
- Allow specifying distribution between limit orders and market orders
> Enhance load testing script

- x/dex/keeper/settlement.go
- x/dex/keeper/settlements_test.go
- x/dex/module_test.go
Only entries belong to the keyed order ID should be set into the store
> Fix SetSettlements

- x/dex/keeper/order.go
- x/dex/keeper/order_test.go
- x/dex/module.go
- x/dex/module_test.go
Reduce quantity from `Order` object upon order settlement
> Update order quantity upon settlement

- scripts/oracle/price_feeder.py
- scripts/oracle/price_fetcher.py
- scripts/oracle/readme.md
Simple script to submit price feed, command to run: `python3 price_feed.py admin sei-chain 'cosmos'`
TODO:
- add binance api as the second layer of price feeder
> Add oracle price feeder script

- app/abci.go
- go.mod
- go.sum
- loadtest/main.go
- x/dex/contract/execution.go
- x/dex/contract/runner_test.go
- x/dex/contract/settlement.go
- x/dex/module.go
More telemetry to debug issues
> Add more telemetry to sei-chain

- loadtest/config.json
- loadtest/contracts/deploy_ten_contracts.sh
- loadtest/contracts/jupiter/src/msg.rs
- loadtest/contracts/mars/src/msg.rs
- loadtest/contracts/saturn/src/msg.rs
- loadtest/contracts/venus/src/msg.rs
- Fix settlement message type from i32 to String
- Add a script to deploy ten parallel contracts
> Fix multi-contract scripts

- app/upgrades.go
> Add upgrade handler for 1.2.0beta

- app/ante.go
- app/antedecorators/gasless_test.go
- app/antedecorators/traced.go
- app/antedecorators/traced_test.go
- app/app.go
CheckTx has been quite expensive so we want to get insights on which ante handlers are the heaviest
> Add tracing to ante handlers

- wasmbinding/encoder.go
- wasmbinding/test/encoder_test.go
- Updates the SeiWasmMessage to `MintTokens` and `BurnTokens`
> Update to MintTokens and BurnTokens

- scripts/dump_app_state_for_height.sh
we can extend the set of modules dumped if needed. For now we can keep the set small
> Script to dump application state

- app/app.go
- wasmbinding/queries.go
- wasmbinding/query_plugin.go
- wasmbinding/test/query_test.go
- wasmbinding/wasm.go
- x/tokenfactory/client/wasm/bindings/queries.go
- x/tokenfactory/client/wasm/query.go
- Adds wasm route for tokenfactory queries + queries to the tokenfactory whitelist for create denom fees
> Add TokenFactory Wasm Queries

- app/antedecorators/gasless.go
Gasless ante handler was not working for message types whose check requires querying the state (e.g. oracle vote, nitro recording), because the action of querying the state itself requires gas, so if a TX is sent with 0 gas, it will not be able to complete the check.
The fix is to preemptively set infinite gas meter and only revert back to the old meter if the check does not pass.
Tested on local chain with `--fees=0usei --gas=0`
> Fix gasless ante handler

- app/app.go
- app/graph.go
Updated the metrics statement to better represent full dag build time.
> [graph] Move metric to dag builder helper

- aclmapping/dependency_generator.go
- aclmapping/dex/mappings.go
- aclmapping/wasm/mappings.go
- app/app.go
- app/test_helpers.go
- cmd/seid/cmd/root.go
- go.mod
- go.sum
- testutil/network/network.go
Add in the dynamic dependency generators and implement the wasm dependency generator to handle generating dependencies for wasm contracts.
TODO: still need to write tests for the mappings.
> Add aclmapping options and mapping folder

- loadtest/scripts/validator_failures.py
Create script to perform following failure scenarios for testing:
1. restart seid
2. slow network
3. change voting power delegation
Ran the following:
1. tested restart seid on personal node
2. tested slow network on personal node
3. will test voting power delegation once testnet is set up
> Add validator failure scripts

- scripts/oracle/price_feeder.py
- scripts/oracle/price_fetcher.py
This updates the oracle script to follow the new pattern to provide prices (no prevote, just vote). 
Currently running on atlantic-1
> Oracle script fix

- app/upgrades.go
> [app] Add 1.2.4beta upgrade

- aclmapping/staking/mappings.go
- aclmapping/staking/mappings_test.go
- aclmapping/tokenfactory/mappings.go
- aclmapping/tokenfactory/mappings_test.go
- aclmapping/utils/resource_type.go
- app/app.go
- go.mod
- go.sum
- store/testutils.go
- x/oracle/simulation/operations.go
* updates the identifier and ran through validation unit tests to make sure that the dependencies are there 
Got all the unit tests to pass 
Ran test on all of sei-chain
> update staking validation identifier

- cmd/seid/cmd/root.go
Need to specify home directory
tested as part of outage remediation
> Fix export

- x/dex/module_test.go
> [dex] Fix dex test

- go.mod
- go.sum
- scripts/old_initialize_local.sh
Bumped grpc and genproto versions to be the newer ones. Also added QoL changes to init local node script to set seid config to properly use test keyring and set chain id in config
> [scripts] QoL changes to init script and updated go mod

- x/nitro/replay/replay.go
- x/nitro/replay/replay_test.go
- x/nitro/replay/replayer.h
- x/nitro/replay/rustbinding.go
Update replayer build artifacts binary and rustbindings
unit tests
> Add nitro artifacts

- loadtest/contracts/deploy_ten_contracts.sh
Need to add rent deposit to contract registration for loadtest script
> Deploy ten deposit

- go.mod
- go.sum
includes a fix for nil proposal block and hard rollback changes
> Bump TM version

- x/tokenfactory/keeper/migrations_test.go
- x/tokenfactory/types/codec.go
- Adds in unit tests for migration for tokenfactory (verifying removal of denom creation fee param + removal of denom creation fee whitelist)
- Tested unit test locally
> Add Tokenfactory Migration Unit Tests

- aclmapping/oracle/mappings_test.go
Add some more tests for oracle aclmapping dependency generator to improve unit test coverage
Coverage before: 50%
Coverage after: 100%
> [tests] Improve oracle aclmapping test coverage

- aclmapping/wasm/mappings_test.go
Added tests for aclmapping wasm package
Prev coverage: 0%
New coverage: 83.3% (uncovered is some error return statements)
> [tests] Add wasm aclmapping tests

- loadtest/contracts/jupiter/Cargo.lock
- loadtest/contracts/jupiter/Cargo.toml
- loadtest/contracts/jupiter/src/contract.rs
- loadtest/contracts/mars/Cargo.lock
- loadtest/contracts/mars/Cargo.toml
- loadtest/contracts/saturn/Cargo.lock
- loadtest/contracts/saturn/Cargo.toml
- loadtest/contracts/venus/Cargo.lock
- loadtest/contracts/venus/Cargo.toml
Updating WASM based on this change:
https://github.com/sei-protocol/sei-chain/commit/e40e41ace966f875a04f8023e1163ed62c7e9ce1
https://github.com/sei-protocol/sei-cosmwasm/commit/ac8ff66f8225677e53d2f2df43276e90b9d50b42 
https://github.com/sei-protocol/sei-cosmwasm/releases/tag/0.4.3
> Fix tick size for LT contracts

- app/antedecorators/gasless_test.go
- app/antedecorators/priority_test.go
Added more + better tests to gasless and priority antedecorators to improve unit test coverage
Previous coverage: 32%
New Coverage: 89%
> [ante] Add tests to antedecorators to improve coverage

- loadtest/contracts/deploy_ten_contracts.sh
Instead of taking arguments, we can just get the info from the local instance 
This also replaces the need to manually editing the loadtest config file every time too 
Ran it on a LT cluster and see that the config was replaced and able torun loadtest binary after
> Automate deploy_ten_contracts.sh

- oracle/price-feeder/oracle/provider/binance_test.go
> [oracle] Replace binance websocket with mock server

- loadtest/contracts/deploy_ten_contracts.sh
- loadtest/main.go
- x/dex/cache/order.go
- x/dex/contract/abci.go
- x/dex/contract/execution.go
- x/oracle/common_test.go
- x/oracle/keeper/test_utils.go
- x/oracle/simulation/operations.go
See this PR for context https://github.com/sei-protocol/sei-cosmos/pull/101 
Also made some changes for loadtest clients to let them run easier
> Change CacheKv to use sync.map for deleted 

- .github/workflows/go.yml
> Add test coverage report to CI

- go.mod
- go.sum
- loadtest/config.json
- loadtest/contracts/deploy_ten_contracts.sh
- x/oracle/simulation/operations.go
> Bump Sei-cosmos version and deposit more rent 

- loadtest/scripts/populate_genesis_accounts.py
> More usei for test accounts

- app/ante.go
- app/ante_test.go
- app/antedecorators/accesscontrol_wasm_dependency.go
- app/antedecorators/gas_test.go
- app/app.go
- go.mod
- go.sum
This adds the antehandler and associated tests for permissioning the register wasm dependency tx
> Add wasm register deps tx permissioning via antehandler

- go.mod
- go.sum
As per the README we also need to replace this package
https://github.com/cosmos/cosmos-sdk/releases/tag/v0.45.9 
Started local chain
> Dragonberry patch part 2

- docker/README.md
- docker/localnode/scripts/step0_build.sh
- readme.md
Simply add some instructions for how to set up the local 4 node docker clusters
> Add README for setting up local docker cluster

- x/oracle/spec/MidBlock.md
Adds the important content from oracle RFC to a markdown spec file for reference.
> [oracle] Add midblock Spec

- aclmapping/dependency_generator.go
This PR registers oracle dependency generator to the aclmapping.
loadtest
> Register oracle dependency generator in aclmapping

- aclmapping/staking/mappings.go
- go.mod
- go.sum
- runtests.py
This makes the relevant changes to the staking dependency generators to maintain parity with the new resources used as part of the max voting power check.
Updated unit tests
> [aclmapping] Modify staking dependencies for max vote power change

- go.mod
- go.sum
- scripts/old_initialize_local.sh
See these 
* https://github.com/sei-protocol/sei-tendermint/pull/29 
* https://github.com/sei-protocol/sei-cosmos/pull/119
> Fix hard rollback 

- .gitignore
- aclmapping/bank/mappings.go
- aclmapping/dex/mappings.go
- aclmapping/utils/resource_type.go
- app/params/config.go
- go.mod
- go.sum
- parallelization/bank/Cargo.toml
- parallelization/bank/deps.json
- parallelization/bank/src/contract.rs
- parallelization/bank/src/lib.rs
- parallelization/bank/src/msg.rs
- parallelization/staking/Cargo.toml
- parallelization/staking/src/contract.rs
- parallelization/staking/src/lib.rs
- parallelization/staking/src/msg.rs
- parallelization/wasm/Cargo.toml
- parallelization/wasm/src/contract.rs
- parallelization/wasm/src/lib.rs
- parallelization/wasm/src/msg.rs
- x/dex/cache/deposit.go
- x/dex/types/keys.go
- x/oracle/simulation/operations.go
Cherry picking consensus and fixes to sei-devnet-2 branch will need to run an upgrade
> Cherry pick fix and consensus config 

- aclmapping/wasm/mappings.go
- aclmapping/wasm/mappings_test.go
- app/antedecorators/gas.go
- app/antedecorators/gas_test.go
- go.mod
- go.sum
- Integrate with new inter-contract parallelization sei-cosmos change
- Conform with the new function signature in dependency generator
- Evaluate referenced contract's dependency identifier template to decide if gas discount should be granted. Gas discount is granted only if all referred messages' identifiers are non-wildcard. Note that if there are cycles in the reference graph, gas discount will also not be granted.
unit tests
> [ACL] integrate with inter-contract parallelization changes

- x/mint/types/minter.go
- x/mint/types/minter_test.go
- x/oracle/simulation/operations.go
Fix the issue where if the chain was down for more than a day we could miss the mint date
Unit test
> Fix minter could miss release date

- go.mod
- go.sum
Bump to include interblock cache fixes
local sei
> Bump cosmos version

- x/dex/contract/abci.go
- x/dex/module.go
Repurpose `BeginBlockGasLimit` and `EndBlockGasLimit` parameters to be per-contract. Set gas limit for each contract separately, instead of having all contracts sharing one limit which could cause non-determinism: validator A thinks contract X is the one that pushes beyond the gas limit whereas validator B thinks it's Y.
test on loadtest cluster
> Set per-contract gas limit in dex Begin/EndBlock

- x/dex/module.go
- x/epoch/module.go
- x/mint/keeper/hooks_test.go
- x/mint/module.go
- x/oracle/module.go
title 
`> git grep "// TODO (codchen): Revert before mainnet so we don't silently fail"` 
Nothing shows up
> Remove silent panic handler

- scripts/dump_app_state_for_height.sh
> Nit fixes for dump app

- go.mod
- go.sum
Bump to include this fix: https://github.com/sei-protocol/sei-tendermint/pull/43
> Bump TM For statesync fix

- go.mod
- go.sum
- x/dex/contract/abci.go
- x/dex/keeper/price.go
- x/dex/keeper/utils/wasm.go
- x/dex/module.go
> Reduce logs, bump cosmos and tm version

- go.mod
- go.sum
Bump
- sei-cosmos
- sei-tendermint
- sei-iavl
local sei with rollback
> Bump lib version for rollback fixes

- go.mod
- go.sum
> Bump TM for fixes

- Makefile
- docker/README.md
- docker/localnode/config/app.toml
- docker/localnode/scripts/deploy.sh
- docker/localnode/scripts/step1_configure_init.sh
- docker/localnode/scripts/step2_genesis.sh
- docker/localnode/scripts/step5_start_sei.sh
- docker/localnode/scripts/step6_start_price_feeder.sh
- docker/rpcnode/Dockerfile
- docker/rpcnode/config/app.toml
- docker/rpcnode/config/config.toml
- docker/rpcnode/scripts/deploy.sh
- docker/rpcnode/scripts/step0_build.sh
- docker/rpcnode/scripts/step1_configure_init.sh
- docker/rpcnode/scripts/step2_start_sei.sh
This change makes the debugging/testing state sync much easier on your local laptop!
Step 1 : start a chain
> make docker-cluster-start
> [+] Running 5/4
>  ⠿ Container sei-node0      Removed                                                                                                                                           0.3s
>  ⠿ Container sei-node1      Removed                                                                                                                                           0.1s
>  ⠿ Container sei-node3      Removed                                                                                                                                           0.1s
>  ⠿ Container sei-node2      Removed …
> feat: Run state sync node locally via docker container

- go.mod
- go.sum
Removes p2p changes: https://github.com/sei-protocol/sei-tendermint/pull/52
> Update tendermint to v0.1.151

- go.mod
- go.sum
Bumping to include intercache and better TM logging
> [go.mod] bump tm and cosmos version 

- go.mod
- go.sum
going to delete "master" branch for sei-cosmos and sei-tendermint, they're using the main branch and it's causing confusion
> Bump sei-cosmos again

- app/params/config.go
Disable this while we're investigating issues regarding proposal blocks missing TXs 
Re-enable once the fix is in
> Disable Gossip TX

- x/oracle/ante.go
display the height in the error log
> Oracle logs get height

- go.mod
- go.sum
> Bump tm to not run check tx on proposal tx

- go.mod
- go.sum
Include 
https://github.com/tendermint/tendermint/pull/8759
> [go.mod] bump tm version 

- scripts/dump_app_state_for_height.sh
Adds accesscontrol module to the dump state script
> Add acl module to dump state

- go.mod
- go.sum
> [go.mod] bump tm version

- app/params/config.go
- go.mod
- go.sum
- oracle/price-feeder/oracle/client/client.go
- oracle/price-feeder/oracle/oracle.go
- x/oracle/types/params.go
> [go.mod][config] bump TM and cosmos, re-enable gossip tx and update oracle whitelist 

- .github/workflows/integration-test.yml
- Makefile
- docker/localnode/config/config.toml
- docker/rpcnode/config/config.toml
- go.mod
- go.sum
https://github.com/sei-protocol/sei-cosmos/pull/154
> [go.mod] use new golang-lru version for generics support 

- go.mod
- go.sum
Includes https://github.com/sei-protocol/sei-tendermint/pull/58 and https://github.com/sei-protocol/sei-cosmos/pull/156 to allow for seid to restart if necessary
Deployed on loadtest cluster with failure injection:
> Bump TM version to include self kill changes

- go.mod
- go.sum
Replace wasmd with sei-wasmd which is a fork of wasmd 0.27.0 with some custom changes
todo
> Use sei-wasmd

- scripts/run-sha256sum.sh
Runs a checksum on each file in a directory, then runs checksum on top of that list
```
root@ip-172-31-17-179:/home/ubuntu# ./run-sha256sum.sh ~/go/pkg/mod/github.com
Checksum of all files in /root/go/pkg/mod/github.com:
58d681753f9c1a2ddf0d592c336687c8d124a6b8b04b08af7d7fa8e49a003922
Please view checksum.list for individual files
```
> Add checksum tool to detect module changes

- oracle/price-feeder/README.md
Added steps outlining systemd service setup and feeder setup.
> Add systemd and feeder instructions to price feeder readme

- x/dex/handler.go
- x/dex/keeper/msgserver/msg_server_contract_deposit_rent_test.go
- x/dex/keeper/msgserver/msg_server_unregister_contract_test.go
- x/dex/types/codec.go
Add missing registrations
unit tests through handler instead of msg server impl
> Register interfaces for UnregisterContract and ContractDepositRent

- oracle/price-feeder/README.md
- oracle/price-feeder/config.example.toml
> add instructions for setting up price feeder

- x/dex/contract/abci.go
- x/dex/contract/execution.go
- x/dex/keeper/utils/wasm.go
- x/dex/module.go
- x/oracle/simulation/operations.go
> Remove dex end block catch all panic

- cmd/seid/cmd/debug.go
- cmd/seid/cmd/iavl_parser.go
This adds the staking module key parsing to the iavl dump
Tested on local cluster and on loadtest cluster
> Add staking module key parsing to iavl dump

- go.mod
- go.sum
https://github.com/sei-protocol/sei-cosmos/pull/166
> Add flag for profiling

- utils/metrics/metrics_util.go
- x/oracle/keeper/keeper.go
- x/oracle/simulation/operations.go
Better visibility around other validator's oracle votes and if they're missing 
Helps with trackign oracle related changes
> Add metrics for oracle vote penalties

- x/dex/cache/order.go
Cherry Pick tony's patch for the deadlock issue.
From Tony:
> The fix I think should be to do store writes outside of iterator iteration and after the iterator is closed https://github.com/sei-protocol/sei-chain/blob/master/x/dex/cache/order.go#L77 We might also want to audit other places as well
Deadlock Cycle:
Going to test in loadtest
> Fix store iterator deadlock under high load

- go.mod
- go.sum
includes p2p fix for node hang and other optimizations
> [go.mo] Bump sei-cosmos and sei-tm

- app/upgrades.go
> Add handler for 2.0.29beta

- go.mod
- go.sum
> [go.mod] bump sei-iavl

- oracle/price-feeder/README.md
- oracle/price-feeder/config.example.toml
- scripts/setup/README.md
- scripts/setup/setup.py
Each of these can be ran separately and the price-feeder is ran post genesis. Setting up validator or preparing for genesis will remove ~/.sei but it will back up the folder before deleting it 
Idea here is for validators to use this script instead of following copy pasted instructions like this:
https://docs.google.com/document/d/1fa7EqAt3EbfrtL_nW6gNvkKnNJ0h1DW_Vp8RTkQBx90/edit#heading=h.b1pcvx4g4opl 
Setup Validator:
```
root@ip-172-31-13-172:/home/ubuntu/sei-chain# python3  ./scripts/setup/setup.py setup-validator --chain-id sei-chain --version 2.0.13beta-bweng-2 --moniker sei-node-0
02/17/2023 04:25:31 AM::INFO:: Chain ID: sei-chain
02/17/2023 04:25:31 AM::INFO:: Version: 2.0.13beta-bweng-2
02/17/2023 04:25:31 AM::INFO:: Moniker: sei-node-0
02/17/2023 04:25:31 AM::INFO:: Backed up …
```
> Setup Script for Sei 

- x/oracle/keeper/keeper.go
> Reset penalty counter for oracle vote metrics 

- loadtest/scripts/populate_genesis_accounts.py
> Clean up for pop gene account

- oracle/price-feeder/config.example.toml
This fixes the config example to use a valid global tag
> fix example config to have proper chain_id label

- app/params/config.go
This should make cold start (i.e. upgrades, new chain) faster as we spend less time waiting for bad proposers before moving on
Ran locally and ensured configs changed
> Lower propose timeout

- app/upgrades.go
> Upgrade handler for 2.0.32beta

- scripts/old_initialize_local.sh
- scripts/setup/setup.py
> Update default genesis tokens

- scripts/setup/setup.py
> Fix setup script

- go.mod
- go.sum
> [go.mod] bump with cache fix

- cmd/seid/cmd/iavl_parser.go
Makes acc.data iavl dump more readable
local testing
> add acc iavl parser

- app/app.go
Having optimistic processing running in parallel with the main goroutine might cause race condition in iavl-nodedb level. So we always wait for optimistic processing to finish, regardless of whether its results are eligible for commit or not
tested in clusters
> Wait for optimistic processing to finish

- loadtest/contracts/deploy_fifty_contracts.sh
> Add 50 contract script

- x/oracle/ante.go
> Fix oracle err log message

- CHANGELOG.md
- app/upgrades.go
- go.mod
- go.sum
> 2.0.36beta release

- x/oracle/keeper/keeper.go
This moves the deletion operation outside of the iterator for greater safety based on previous discussions to move store operations outside of iterators.
existing tests
> [oracle] Move store operations outside of iterator

- CHANGELOG.md
- app/upgrades.go
> 2.0.37beta release 

- utils/metrics/metrics_util.go
- x/epoch/module.go
- x/epoch/types/events.go
This adds an event for newEpoch, emitted for blocks in which a new epoch begins
tested on localsei
> [epoch] Add new epoch events

- x/dex/client/cli/query/query_asset_list.go
- x/dex/client/cli/query/query_get_latest_price.go
- x/dex/client/cli/query/query_get_price.go
- x/dex/client/cli/query/query_get_prices.go
- x/dex/client/cli/query/query_get_twaps.go
- x/dex/client/cli/query/query_long_book.go
- x/dex/client/cli/query/query_match_result.go
- x/dex/client/cli/query/query_orders.go
- x/dex/client/cli/query/query_registered_pairs.go
- x/dex/client/cli/query/query_short_book.go
- x/dex/client/cli/tx/gov_tx.go
- x/dex/client/cli/tx/tx_cancel_orders.go
- x/dex/client/cli/tx/tx_contract_deposit_rent.go
- x/dex/client/cli/tx/tx_place_orders.go
- x/dex/client/cli/tx/tx_register_contract.go
- x/dex/client/cli/tx/tx_register_pairs.go
- x/dex/client/cli/tx/tx_unregister_contract.go
- x/dex/client/cli/tx/tx_update_price_tick_size.go
- x/dex/client/cli/tx/tx_update_quantity_tick_size.go
- x/mint/client/cli/query.go
- x/oracle/client/cli/tx.go
Adds long messages for dex and mint module CLI commands. @LCyson there's a TODO for you to clarify a bit more around the place-orders command since I don't have full context on the specific formatting of order placement.
> [dex][mint] Add long messages for dex and mint

- app/upgrades.go
- go.mod
- go.sum
https://github.com/sei-protocol/sei-iavl/commits/v0.1.1
> 2.0.38beta release

- app/params/config.go
Make mempool configs more conservative to avoid slowing node down
> Mempool configs

- CHANGELOG.md
- app/upgrades.go
- go.mod
- go.sum
> 2.0.39beta Release

- app/app.go
- app/upgrade_test.go
- app/utils.go
This reverts commit c464c9621297e5d3313a89d090b56191d803a7e1.
> Revert "Fix optimistic processing deadlock in upgrade issue (#636)"

- go.mod
- go.sum
Bump sei-cosmos
test cluster (tony-race-detector-on)
> Bump sei-cosmos to v0.2.3

- x/oracle/client/rest/query.go
Removes the rest query for the aggregate vote queries
> [oracle] Remove rest query for aggregate votes

- app/apptesting/test_suite.go
- app/test_helpers.go
- go.mod
- go.sum
This bumps the sei cosmos version to use the slashing refactor, and also updates usages in sei testing helpers respectively
loadtest cluster
> use slashing missed heights change

- app/upgrades.go
- go.mod
- go.sum
> 2.0.41beta release

- go.mod
- go.sum
> bump sei cosmos for devnet-3 fix

- app/upgrades.go
> Add 2.0.42beta upgrade handler

- CHANGELOG.md
- app/apptesting/test_suite.go
- app/test_helpers.go
- go.mod
- go.sum
Committing the long term changes from release branch to master
> Bump version and add change logs for 2.0.42beta

- app/app.go
- go.mod
- go.sum
This PR updates the affected EventAttribute fields from https://github.com/sei-protocol/sei-cosmos/pull/195
- unit test
- local test
- pending testing on loadtest cluster and upgrade on devnet-3
> Update EventAttribute type

- CHANGELOG.md
- app/upgrades.go
> Add 2.0.43beta upgrade changelogs and handler

- go.mod
- go.sum
> Bump sei-tendermint version to include genesis encoder fix

- go.mod
- go.sum
- x/dex/keeper/abci/end_block_deposit.go
- x/dex/keeper/abci/end_block_place_orders_test.go
- x/dex/module_test.go
Previously `escrowed` wasn't properly updated. This PR fixes it
unit test
> Fix GetDepositSudoMsg

- go.mod
- go.sum
> [go.mod] bump with consensus metrics and ibc fixes

- CHANGELOG.md
- app/upgrades.go
> 2.0.44beta upgrade handler

- scripts/old_initialize_local.sh
Adds a mint token schedule to the local script as an additional param
> add mint to local script

- loadtest/config.json
- loadtest/types.go
> Fix loadtest fee config

- utils/metrics/metrics_util.go
- x/oracle/abci.go
One SLO for chain-level correctness is how often the denoms are updated 
Need to deploy this to create recording rule and dashboards 
make install runs fine
> Add price update counter for price-feeder

- CHANGELOG.md
- app/upgrades.go
- go.mod
- go.sum
> 2.0.45beta release

- cmd/seid/cmd/root.go
This gives us capability to manually prune state
tested on testnet
> Register prune command

- .github/workflows/go.yml
> Add write permissiosn to build workflows

- oracle/price-feeder/README.md
- oracle/price-feeder/config.example.toml
Updated per validator request, shouout to whisper nodes
> Update price-feeder healthcheck doc

- CHANGELOG.md
- app/upgrades.go
- go.mod
- go.sum
> Add 2.0.46beta upgrade handler

- go.mod
- go.sum
> Bump tendermint and cosmos

- go.mod
- go.sum
> DBsync fixes for hanging metadata

- go.mod
- go.sum
bump to include this change:
https://github.com/sei-protocol/sei-cosmos/pull/230
> [go.mod] bump for module to module debug logs

- CHANGELOG.md
- app/upgrades.go
> 2.0.47beta upgrade commit

- app/app.go
- app/upgrade_test.go
- x/oracle/simulation/operations.go
This is the logic in the app code already
> Wait for completion signal in unit test

- x/dex/types/genesis.go
- x/dex/types/genesis_test.go
- Updates validation for export genesis to only check for duplicates in a specific market
- Added more unit tests
- Tested on chain
> Update Dex Genesis Validate

- x/dex/module.go
> Add error log to contract unregistration

- docs/rfc/README.md
> rm link for adr

- x/dex/ante_test.go
- x/dex/migrations/v12_to_v13.go
- x/dex/migrations/v12_to_v13_test.go
- x/dex/module.go
- x/dex/types/params.go
Params need a migration after adding them here: https://github.com/sei-protocol/sei-chain/pull/744
Checked out in test cluster and ran
> Add param migration handler

- loadtest/sign.go
This is the only type in the chain now
> Use Secp256k1Type for loadtest

- x/oracle/types/params.go
> No oracle slashing by default

- CHANGELOG.md
- app/upgrades.go
- go.mod
- go.sum
> 3.0.0 release

- app/ante.go
- x/dex/ante.go
This should add the appropriate access operation to fulfill the READ access used for dex contract info in the antehandler
need to test on rpc node
> Fix dex ante deps

- go.mod
- go.sum
> [go.mod] bump for deadlock issue fix

- app/app.go
- go.mod
- go.sum
- utils/metrics/metrics_util.go
- x/dex/keeper/msgserver/msg_server_place_orders.go
https://github.com/sei-protocol/sei-cosmos/pull/248
https://github.com/sei-protocol/sei-cosmos/pull/248
> [go.mod] bump for throughput metrics and metrics fix

- x/dex/types/message_place_orders.go
This PR temporarily disables FOK market order type.
- unit test
> Disable FOK

- CHANGELOG.md
- app/upgrades.go
> 3.0.2 release

- go.mod
- go.sum
Dump sei cosmos for feegrant dependency fixes
> bump sei cosmos

- x/oracle/types/params.go
Use default isNeg rather than allcoating new sdk dec
> [Certik Audit] Unnecessary allocation for neg check

- x/dex/README.md
> `dex` README Part 1

- go.mod
- go.sum
- x/tokenfactory/keeper/admins_test.go
This adds unit tests for the scenario known to cause issues for the deferred operation prior to sei-cosmos fix.
Unit Tests
DO NOT MERGE - currently using a sei-cosmos commit hash, needs to be replaced with a tag after merging changes
> Add tkf unit tests for two mints with deferred behavior

- .github/workflows/unit-test-coverage.yml
> Test coverage workflow

- .github/workflows/unit-test-coverage.yml
> Verify unit test coverage

- .github/workflows/unit-test-coverage.yml
- codecov.yml
> Verify unit test coverage workflow

- .github/workflows/test-coverage.yml
> Unit test coverage fix

- loadtest/config.json
- loadtest/main.go
- loadtest/types.go
Add a new `wasm_instantiate` type. Note that the code needs to be uploaded beforehand.
running on sei-internal
> Add wasm instantiate type load test message

- x/dex/client/utils/utils.go
Fix dex negative ticksize issue by checking for value validity.
> fix potential negative ticksize

- aclmapping/tokenfactory/mappings.go
- app/app_test.go
- go.mod
- go.sum
- x/dex/contract/abci.go
- x/dex/keeper/abci/end_block_deposit.go
- x/dex/module_test.go
- x/mint/types/expected_keepers.go
- x/tokenfactory/keeper/bankactions.go
- x/tokenfactory/types/expected_keepers.go
This refactors sei-chain to remove deferred send usages for this PR: https://github.com/sei-protocol/sei-cosmos/pull/266
local chain testing, dex behavior needs testing / review for sudo endblock behavior.
> Update sei-chain usages to remove some deferred operations

- .github/workflows/unit-test-coverage.yml
- .github/workflows/unit_tests.yml
- Makefile
> Run parallel unit tests when possible and update codecov

- codecov.yml
> update codecov to ignore more pb paths for code coverage test

- x/mint/keeper/keeper.go
Not needed and causes additional print when exporting
> Remove unnecessary print

- integration_test/scripts/runner.py
Enhance eval in runner.py to support more complicated expressions such as:
A == B and B < C and C >= D or D != E
Tested locally
> Enhance eval expression for integration test

- x/epoch/types/epoch.go
- x/epoch/types/genesis.go
- x/epoch/types/genesis_test.go
- x/epoch/types/params.go
Just validating that no param is set here 
Unit tests already call validate (coverage)
> Add validate to epoch params

- oracle/price-feeder/cmd/price-feeder.go
Once it starts up it's able to retry on failure but first connection could be flakey, therefore we want to retry over 5 seconds
> Retry oracle start up client

- Makefile
> invar check interval is not required

- .github/workflows/integration-test.yml
- codecov.yml
- docker/localnode/scripts/step2_genesis.sh
- integration_test/mint_module/mint_test.yaml
- integration_test/scripts/runner.py
Adds mint integration tests
PR tests 
also ran locally:
> Add mint module integration testing 

- .github/workflows/integration-test.yml
- integration_test/mint_module/mint_test.yaml
> Fix mint module integration tests 

- aclmapping/staking/mappings.go
- x/dex/types/message_update_price_tick_size.go
- x/dex/types/message_update_quantity_tick_size.go
Remove redundant access Operation and redundant checks for message validation
> remove redundant code

- tests/dex_test.go
- testutil/processblock/verify/dex.go
Added tests for cancellation and also fixed test harness util which uses `sdk.Dec` as a map key into using a string
tests
> Add dex cancellatoon flow tests

- x/dex/module.go
Add registration for the new migration handler
> Register migration handler

- x/dex/client/cli/query/query_long_book.go
- x/dex/client/cli/tx/tx_place_orders.go
- x/dex/contract/abci.go
> [Certik Audit] Fix typos

- x/dex/keeper/tick.go
- x/dex/types/events.go
Emits events for updating ticket quantity and price
> [dex] Emit Quantity and Price events

- x/oracle/types/ballot.go
> [Certik Audit] Remove duplicate code

- x/dex/types/message_cancel_orders.go
- x/dex/types/message_cancel_orders_test.go
- x/dex/types/message_place_orders.go
- x/dex/types/message_place_orders_test.go
> [Certik Audit] Denom validation

- integration_test/contracts/deploy_dex_contract.sh
- integration_test/dex_module/place_order_test.yaml
Added integration test to make sure we are not seeing issues described in https://linear.app/seilabs/issue/SEI-4596/sei-02-or-missing-amino-codec-registration
Tested with integration test
> [Certik Audit] Add integration test to verify denom correctness during place orders

- cmd/seid/cmd/debug.go
- go.mod
- go.sum
> Bump version and fix compile error

- x/mint/types/params.go
Denom regex already doesn't allow space
> [Certik Audit] Remove denom trim

- .github/workflows/compatiblity_check.yml
- cmd/seid/cmd/root.go
- go.mod
- go.sum
- Bump version for cosmos and fix the compile issue
- Add a github workflow to check forward compatibility as a reminder for things that could break in the future
> Add forward compatibility test and deprecate NoVersioning

- x/dex/client/utils/utils.go
Validate pair when converting from JSON
> Validate pair when creating tick size from json

- utils/metrics/metrics_util.go
- x/dex/contract/execution.go
- x/dex/contract/execution_test.go
- x/dex/exchange/helpers.go
- x/dex/exchange/limit_order.go
- x/dex/exchange/limit_order_test.go
- MinPrice: https://linear.app/seilabs/issue/SEI-4692/lim-01-or-possibly-incorrect-update-of-minprice-in-limit-order
- Metrics: https://linear.app/seilabs/issue/SEI-4678/exe-02-or-discussion-on-the-computation-of-totalquantity-with-size
unit tests
> Address certik audit finds

- cmd/seid/cmd/root.go
- go.mod
- go.sum
Make separate orphan storage change configurable
local sei
> Bump sei-cosmos to v0.2.53

- integration_test/bank_module/send_funds_test.yaml
Add a bank integration test. There's not much to test except that bank sends work
Ran locally
> Add bank integration test

- .github/workflows/compatiblity_check.yml
- .github/workflows/fuzz.yml
- .github/workflows/integration-test.yml
- .github/workflows/unit_tests.yml
- app/app.go
- docker/README.md
- docker/localnode/Dockerfile
- integration_test/README.md
- integration_test/authz_module/generic_authorization_test.yaml
- integration_test/authz_module/send_authorization_test.yaml
- integration_test/authz_module/staking_authorization_test.yaml
- oracle/price-feeder/dockerfile/Dockerfile
- oracle/price-feeder/dockerfile/README.md
Add authz module to sei chain
localsei testing and integration tests
> Add authz module to sei-chain

- x/oracle/types/params.go
- x/oracle/types/params_test.go
We don't handle cases where slashwindow % voteperiod != 0, so add the check
Unit tests
> Ensure slash window is divisible by vote period

- x/dex/types/message_update_quantity_tick_size.go
> [Certik Audit] Remove redundant address check

- x/dex/types/genesis.go
- x/dex/types/genesis_test.go
Add address validation to contracts
Unit test
> [Certik Audit]Add contract addr validation

- .github/workflows/integration-test.yml
- integration_test/dex_module/cancel_order_test.yaml
Add cancellation integration test
integration test
> add cancel integration test

- .github/ISSUE_TEMPLATE/enahancement.yml
Rebase the change based main, not master. 
Add a issue template for submitting feature request.
> Add enhancement template for sei-chain

- CHANGELOG.md
- app/upgrades.go
- go.mod
- go.sum
- x/dex/module.go
> 3.0.5 hotfix release

- go.mod
- go.sum
- integration_test/bank_module/multi_sig_send_test.yaml
- integration_test/bank_module/simulation_tx.yaml
> Add integration test for --dry-run and multi-sig TXs 

- app/app.go
- app/fork_manager.go
- app/fork_manager_test.go
- app/test_helpers.go
This adds the hard fork manager pattern to allow for registering hard forks based on height and chain ID
Unit tests
> Add hard fork manager

- integration_test/distribution_module/community_pool.yaml
- integration_test/distribution_module/rewards.yaml
Add integration test for basic distribution validation
> Add distribution module integration test

- app/app.go
- x/oracle/keeper/querier_test.go
> fix oracle unit tests to use param vals instead of constant

- app/app.go
> replace TODO with upgrade name

- cmd/seid/cmd/root.go
> Use default for pruning

- x/mint/types/minter.go
- x/mint/types/minter_test.go
> [Certik Audit] Add denom validation to mint, fix param

- .github/workflows/integration-test.yml
> Register distribution module to integration test ci

- app/antedecorators/gasless.go
- app/antedecorators/gasless_test.go
We want gasless tx to still be subject to normal gas limit check iff it specifies a gas limit (for the purpose of being ranked higher in the priority queue)
unit test
> Fix gasless decorator

- integration_test/dex_module/place_order_test.yaml
- integration_test/distribution_module/community_pool.yaml
Fixes distribution unit test (no starting balance results in null). Also adds the max block gas violation dex test
Ran locally
> Fix distribution integ test, add max block gas violation test

- .dockerignore
- .github/workflows/docker_publish.yml
- Dockerfile
Allows us to publish sei docker images upon tagging
TODO
> Add heighliner docker img build and publish

- app/antedecorators/gasless.go
- app/app.go
- docker/localnode/scripts/step2_genesis.sh
- integration_test/dex_module/cancel_order_test.yaml
- integration_test/dex_module/place_order_test.yaml
- scripts/initialize_local_chain.sh
This results in that gasless txs will pass no matter what the supplied --gas value is
- Local testing
- Unit tests
> Skip gasless txs in max block gas calculation

- CHANGELOG.md
- app/upgrades.go
Release log and migration for 3.0.6
Change tested and validated in arctic-1
> Cut 3.0.6 release

- loadtest/main.go
> Multi msg bank sends

- app/params/config.go
Updating default param to go along with config change in chain envs
> change commit T/O to 200ms

- oracle/price-feeder/config/config.go
- oracle/price-feeder/oracle/oracle.go
Add cryptocom to supported providers list
Verified on localsei with oracle process running with crypto provider
> add cryptocom support

- oracle/price-feeder/config/config.go
- oracle/price-feeder/oracle/oracle.go
> Add comments to explain what the various providers are used for

- oracle/price-feeder/config/config.go
> Clarify oracle api comments

- scripts/dump_app_state_for_height.sh
> Verify height is passed in script

- scripts/initialize_local_chain.sh
> Update local script to be similar to default

- loadtest/scripts/metrics.py
> Move best block stats to helper function

- loadtest/scripts/populate_genesis_accounts.py
Remove the need to call add-genesis-account, its a redundant call taht's prone to error since it there's a contention on the genesis file 
This should also speed it up significantly 
Created 10k accounts locally 
Created chain locally
> Remove need for add-genesis-account

- CHANGELOG.md
- app/upgrades.go
Adds 3.0.7 upgrade
tested on loadtest cluster
> 3.0.7 Upgrade

- .github/workflows/proto-registry.yml
- proto/buf.lock
- proto/buf.yaml
Add workflow to push protobuf definition to buf.build
CI
> add buf.build workflow

- oracle/price-feeder/oracle/oracle.go
- scripts/initialize_local_chain.sh
Add a debug log to show the assets and the providers that are currently supporting prices for the assets. This can help in identifying when an asset has insufficient provider diversity.
Tested on local chain to verify output
> Add provider debug log

- docker/README.md
- Updates docker local node command
- Updates correct path to tail node logs
- Fix twitter handle on docker readme
- Verified correct handle
- Verified correct local node
- Verified correct path to logs generated
> Fix Docker Readme

- app/app.go
This just adds some comments with useful code pointers and TODOs for eventual OCC work
NA
> add some TODOs pointing to key areas to refactor for OCC work

- oracle/price-feeder/oracle/oracle.go
This makes provider failures non-blocking for the oracle loop.
Tested on local chain
> Make provider failures non-blocking to oracle tick loop

- loadtest/scripts/metrics.py
> Small metrics script fix

- evmrpc/block.go
- evmrpc/block_test.go
- evmrpc/testutils.go
- evmrpc/tx.go
- evmrpc/tx_test.go
Add the following endpoints:
- getTransactionByBlockNumberAndIndex
- getTransactionByBlockHashAndIndex
- getTransactionByHash
unit tests
> [EVM] add getTransactions endpoints

- evmrpc/tx.go
- evmrpc/tx_test.go
Implement `eth_getTransactionCount` which returns the number of transactions sent by a given account in a specific block
unit tests
> [EVM] add endpoint to get transaction count by address

- evmrpc/info.go
- evmrpc/info_test.go
- evmrpc/testutils.go
Added the following info endpoints:
- chainId
- gasPrice
- coinbase
- blockNumber
Also refactored testing utilities to reduce boilerplates
unit tests
> [EVM] add info endpoints

- .github/workflows/compatiblity_check.yml
- app/app.go
- go.mod
- go.sum
- This is against `occ-main` (adds latest cosmos)
- Invokes the new `DeliverTxBatch` interface 
- In flight (will be via load test cluster)
> Add occ to sei-chain

- loadtest/loadtest_client.go
- x/dex/cache/cancel.go
- x/dex/cache/deposit.go
- x/dex/cache/order.go
- x/dex/keeper/utils/wasm.go
- x/tokenfactory/keeper/migrations.go
This fixes some of the issues raised by golangci-lint since it has recently been failing CI
> fix linting issues

- integration_test/gov_module/proposal/expedited_proposal.json
- integration_test/gov_module/proposal/param_change_proposal.json
- scripts/initialize_local_chain.sh
This fixes the initialize_local_chain script to override the staking max_votign_power_ratio genesis param to allow for delegating ton a one node cluster
tested with local chain
> Fix max voting power ratio config for local chain

- app/abci.go
- go.mod
- go.sum
- occ_tests/occ_test.go
- utils/metrics/metrics_util.go
- Adds a trace span for DeliverTXBatch 
- Unit tests pass (and breakpoint confirms new codepath)
- Local testing
> [OCC] Add trace span for DeliverTxBatch

- go.mod
- go.sum
Bumping the underline IBC version from 3.2.0 to 3.3.0
Tested locally
> Bump IBC to v3.3.0

- CHANGELOG.md
- app/upgrades.go
Release sei-chain v3.3.0 for upgrade
> Bump version to v3.3.0

- evmrpc/state.go
- evmrpc/state_test.go
- go.mod
- go.sum
Fix `getProof` endpoint by using the parent kv store to generate the proof, and added the unit test back
unit test
> [EVM] fix getProof

- go.mod
- go.sum
> Bump wasmd version

- evmrpc/send.go
- evmrpc/send_test.go
- evmrpc/setup_test.go
Instead of showing error codes (which are Cosmos specific), we will convert the error code into actual error messages
unit tests
> Use better error message

- CHANGELOG.md
- app/upgrades.go
- go.mod
- go.sum
Introduces the v3.5.0 upgrade handler and updates affected dependencies as needed. Also updates changelog appropriately
> register v3.5.0 upgrade and changelog

- evmrpc/block.go
- evmrpc/block_test.go
- evmrpc/setup_test.go
- evmrpc/tx.go
- evmrpc/tx_test.go
- evmrpc/utils.go
- x/evm/client/cli/tx.go
Map Cosmos bank send messages into EVM transaction format when returning block transactions in EVM RPC.
unit test
> [EVM] show bank send in GetBlock response

- app/ante.go
- evmrpc/block.go
- evmrpc/filter.go
- evmrpc/query_builder.go
- evmrpc/query_builder_test.go
- evmrpc/setup_test.go
- evmrpc/tx.go
- evmrpc/utils.go
- x/evm/ante/basic.go
- x/evm/ante/basic_test.go
- x/evm/ante/fee.go
- x/evm/ante/fee_test.go
- x/evm/keeper/msg_server.go
- x/evm/keeper/msg_server_test.go
- x/evm/types/ethtx/blob_tx.go
- x/evm/types/ethtx/blob_tx_test.go
Perform stateless checks that are also performed on Ethereum before TXs getting added to mempool
TODO
> [EVM] add stateless checks

- x/evm/ante/fee.go
Need to propagate to the next ante handler
> Fix ante handler

- x/dex/ante.go
- x/dex/contract/abci.go
- x/dex/contract/execution.go
- x/dex/contract/execution_test.go
- x/dex/exchange/limit_order.go
- x/dex/exchange/market_order.go
- x/dex/keeper/contract.go
- x/dex/keeper/contract_test.go
- x/dex/keeper/msgserver/msg_server_contract_deposit_rent.go
- x/dex/keeper/msgserver/msg_server_register_contract.go
> Audit and fix all potential uint64 overflow sites

- x/evm/client/cli/tx.go
Requiring nonce is annoying so this PR changes the deploy ERC20 wrapper command to automatically query for the expected nonce.
local sei
> Automatically query for nonce for deploy erc20 cmd

- x/evm/client/cli/tx.go
return error properly
local sei cli
> Improve error handling

- go.mod
- go.sum
To include pending tx removal fix
local sei
> bump sei-tendermint

- app/upgrades.go
> Tick version for devnet

- go.mod
- go.sum
Include https://github.com/sei-protocol/sei-cosmos/commit/66854d0e7c3f21e0429cce910d7b03c5c9eaf17f
> Bump cosmos seqno fix

- app/app.go
- cmd/seid/cmd/root.go
- go.mod
- go.sum
This adds a config to app.toml for enabling / disabling occ tx execution
local chain testing
> add occ-enable config

- x/evm/ante/preprocess.go
- x/evm/ante/preprocess_test.go
Unprotected transactions will have V values of 27 or 28 which should not be adjusted.
unit tests
> Do not adjust V for unprotected txs

- x/evm/client/cli/tx.go
- output should be json instead of this:
```
Response: &{2.0 deploy-erc20 0x90b3f6a8e66551801507d26d3f3872129f60a5fe8ac6c78355c7b6ffc8a71f6b}
```
- manual confirmation
> [EVM] fix json send evm tx for cli

- evmrpc/info.go
- evmrpc/info_test.go
- evmrpc/setup_test.go
- evmrpc/simulate.go
- evmrpc/simulate_test.go
- evmrpc/state.go
- evmrpc/state_test.go
- evmrpc/tx.go
- evmrpc/tx_test.go
- evmrpc/utils.go
- evmrpc/utils_test.go
- go.mod
- go.sum
Check if version exists and return meaningful error if it doesn't
> Handle pruned heights in RPC gracefully

- app/upgrades.go
- add version to upgrades file
> [EVM] update version for devnet v4.0.3

- app/upgrades.go
- go.mod
- go.sum
- ticks version for sei-db
- updates version for upgrades.go
- CI
> [EVM] set version for v4.0.4-evm-devnet

- app/app.go
- app/app_test.go
- go.mod
- go.sum
- occ_tests/occ_test.go
- occ_tests/utils/utils.go
This removes the block gas meter for occ
> OCC Remove block gas meter

- evmrpc/server.go
verified here https://evm.arctic-1.seinetwork.io/
> Wildcard vhosts to allow for dns rpc

- go.mod
- go.sum
> Bump go-ethereum

- x/evm/keeper/msg_server.go
This change removes usages of the block gas meter in preparation for an underlying change that will remove it. This refactor will allow us to canary test a binary that doesn't have the block gas meter.
Prior testing with the refactor
> refactor block gas meter usages to ignore block gas meter in preparation for removal

- app/upgrades.go
- updates upgrades to v4.0.6-evm-devnet
- slanders-evm will upgrade to this
> [EVM] Tick upgrades v4.0.6-evm-devnet

- Makefile
Verified:
```
root@ip-172-31-32-250:/home/ubuntu/sei-chain# seid version
4.0.7-evm-devnet
--- makefile change ---
root@ip-172-31-32-250:/home/ubuntu/sei-chain# seid version
v4.0.7-evm-devnet
```
> Keep v prefix for seid version

- app/upgrades.go
- updates upgrades for the new version
- lower env testing
> [EVM] Tick upgrade for v4.0.8-evm-devnet

- x/evm/state/log.go
- x/evm/state/log_test.go
Also need to take snapshotted logs into account
unit tests
> Fix log index

- go.mod
- go.sum
Bump cosmos and seidb version for all new bug fixes
> Release v3.6.3

- app/upgrades.go
- Fixes duplicate logIndex bug
- Lower environment testing
> Tick version for v4.0.9-evm-devnet

- .github/workflows/compatiblity_check.yml
- app/upgrades.go
- go.mod
- go.sum
- Rebased sei-cosmos and creating new release
- CI and lower env testing
> [EVM] Update with rebased sei-cosmos

- go.mod
- go.sum
- integration_test/bank_module/send_funds_test.yaml
- integration_test/contracts/create_tokenfactory_denoms.sh
- integration_test/contracts/deploy_wasm_contracts.sh
- integration_test/seidb/state_store_test.yaml
This PR is to add integration test for https://github.com/sei-protocol/sei-cosmos/pull/424
> [SeiDB] Add integration test for historical bank send

- docker/localnode/Dockerfile
- docker/localnode/scripts/deploy.sh
- integration_test/evm_module/hardhat_test.yaml
- integration_test/scripts/runner.py
This PR add cast to docker cluster and integration test for better testability.
> Add cast support for docker and integration test

- Makefile
- go.mod
- go.sum
- integration_test/bank_module/send_funds_test.yaml
- integration_test/contracts/create_tokenfactory_denoms.sh
- integration_test/contracts/deploy_wasm_contracts.sh
- integration_test/seidb/state_store_test.yaml
- oracle/price-feeder/oracle/client/client.go
- scripts/run-node.py
- x/oracle/ante.go
> Rebase occ main

- app/app.go
> Add writeset estimation tracing + generate writesets concurrently

- app/upgrades.go
- v4.1.2-evm-devnet
- lower env testing and CI
> [EVM] update upgrades.go to include the 4.1.2 version

- app/upgrades.go
- add v4.1.3-evm-devnet
- unit and lower env testing
> [EVM] Add v4.1.3-evm-devnet to upgrades go

- loadtest/main.go
Change TPS calculation from 1 second to 10 seconds to make it more stable and reliable
> [Loadtest] Optimize loadtest client throughput calculation

- CHANGELOG.md
- app/upgrades.go
- go.mod
- go.sum
- x/tokenfactory/types/events.go
> Release version v3.7.0

- x/evm/keeper/code.go
- x/evm/keeper/code_test.go
- x/evm/state/state.go
Handle `nil` code so that it doesn't lead to a panic in `SetCode`.
Also fixed comments related to `SelfDestruct`
unit tests
> handle nil code

- contracts/test/EVMCompatabilityTester.js
Do some historical queries to make sure the state changes for a tx (balance change, nonce change) happen on the exact blocks that they're supposed to.
hardhat tests
> [EVM] historical query test

- cmd/seid/cmd/root.go
> Set default min gas price to 0.02usei

- app/upgrades.go
> V4.1.4 evm devnet branch

- x/evm/ante/fee.go
- x/evm/ante/fee_test.go
- uses floats instead of int truncation
- uses effective gas price to support legacy/dynamic/blob/etc
- new unit test
> [EVM] fix gas tip calculation related to priority

- docker/docker-compose.yml
- evmrpc/simulate.go
- evmrpc/tracers.go
- evmrpc/tracers_test.go
This PR add two new debug endpoints as well as adding parent hash for backend:
- debug_traceBlockByNumber
- debug_traceBlockByHash
Unit Test + Docker verified
> Add two debug endpoints for trace

- go.mod
- go.sum
Bump TM version to include EVM tx eviction changes
CI
> Bump tendermint

- .github/workflows/enforce-labels.yml
As part of our seid release process, we want to tag PRs with appropriate labels for wether a major upgrade is needed or not
Verified:
> Add job to enforce github label

- go.mod
- go.sum
Update sei-chain to use sei-cosmos version `v0.2.74-seiv2`
CI / loadtesting
> Update go mod with sei-cosmos tag

- go.mod
- go.sum
> Bump seidb version to latest

- go.mod
- go.sum
- wasmbinding/encoder.go
> bump sei-wasmd

- .github/workflows/compatiblity_check.yml
- loadtest/contracts/deploy_erc20.sh
- loadtest/contracts/deploy_erc721.sh
> Add funding logic to erc721 deploy script

- CHANGELOG.md
- app/upgrades.go
- go.mod
- go.sum
> v3.8.0-release seiv2

- app/upgrades.go
> V4.1.5 evm devnet release

- go.mod
- go.sum
> Update sei cosmos 0.2.77 seiv2

- go.mod
- go.sum
> Bump tendermint version to 0.2.40

- go.mod
- go.sum
- fixes performance regression for occ 
- unit tests
> [OCC] tick cosmos version to v0.2.78-seiv2

- x/evm/keeper/msg_server.go
- Add metrics for evm panics and errors
- Verifying on chain
> EVM Module Panic + Error Metrics

- app/eth_replay.go
- x/evm/keeper/code.go
- x/evm/keeper/code_test.go
- x/evm/state/check.go
- x/evm/state/code_test.go
> Account for withdrawals in replay

- app/app.go
- app/app_test.go
The decoding/preprocessing process is stateless so can be parallelized without non-determinism concerns.
unit test
> Parallelize tx decoding/EVM preprocessing

- x/evm/keeper/msg_server.go
Previously the signature of an EVM transaction is decoded twice:
1. in the ante: https://github.com/sei-protocol/sei-chain/blob/seiv2/x/evm/ante/preprocess.go#L166-L183
2. in the msg_server: https://github.com/sei-protocol/sei-chain/blob/seiv2/x/evm/keeper/msg_server.go#L166 (where `core.TransactionToMessage` would decode signature again)
However we can take advantage of the fact that the signature decoding in 1 is cached. So this PR changes the `msg_server` logic to compose `core.Message` with the cached sender address instead.
should not break any existing `msg_server_test` test
> Remove redundant signature decoding

- wasmbinding/queries.go
- x/evm/client/wasm/bindings/queries.go
- x/evm/client/wasm/query.go
- x/evm/client/wasm/query_test.go
Add queries for CosmWasm contracts to get associated addresses
unit tests
> Add wasm binding for getting associated addresses

- cmd/seid/cmd/blocktest.go
- x/evm/module.go
- addresses golint that broke recently 
- golint should pass
- unit tests
> [seiv2] fix golint

- x/evm/keeper/msg_server.go
Print stack trace if a panic happens to help debugging
block test that caused a panic
> Add EVM panic stack trace

- app/app.go
- precompiles/common/expected_keepers.go
- precompiles/common/precompiles.go
- precompiles/ibc/IBC.sol
- precompiles/ibc/abi.json
- precompiles/ibc/ibc.go
- precompiles/ibc/ibc_test.go
- precompiles/setup.go
- precompiles/wasmd/wasmd.go
- x/evm/keeper/genesis.go
- x/evm/keeper/keeper.go
Adding IBC transfer precompile
- unit testing
- local testing
- setup local Sei and gaia nodes
- installed hermes and and setup channel
- executed transfer via precompile with seid tx evm call-contract command
- verified funds were deducted on sei wallet and added to gaia wallet. Verified no errors in hermes logs
Also this PR is in place of https://github.com/sei-protocol/sei-chain/pull/1459
> IBC transfer precompile

- x/evm/keeper/address.go
- x/evm/types/events.go
Emit event for address association
local tx
> Emit tendermint event upon address association

- x/evm/module.go
> mock beacon root

- x/evm/ante/basic.go
- x/evm/ante/basic_test.go
- Updates EVM Basic Ante to run outside of just checktx
- Updated unit tests
- Verifying on local chain
> Update EVM Basic Ante

- precompiles/distribution/distribution.go
- precompiles/gov/gov.go
- precompiles/staking/staking.go
- precompiles/wasmd/wasmd.go
- Removes more panics in precompiles for `RequiredGas`
- Adds more validation to inputs in wasmd precompile like validating msgs, labels etc
- Testing on chain
> Precompile Remove Panics + Add More Validation

- x/evm/ante/preprocess.go
> add comments

- precompiles/common/precompiles.go
```
sei gas = evm gas * multiplier
sei gas price = fee / sei gas = fee / (evm gas * multiplier) = evm gas / multiplier
```
multiplier is 1 now
> fix precompile remaining gas calculation

- x/evm/state/nonce_test.go
- x/evm/state/utils.go
- x/evm/state/utils_test.go
This PR add more unit tests for x/evm/state module
> Add unit test for x/evm/state

- x/evm/ante/preprocess.go
- x/evm/ante/preprocess_test.go
Since it's possible for an unassociated Sei address to have wei balance (if it's the recipient of `sendNative` precompile call), we need to check for it when evaluating whether the account has enough balance for AssociateTx
unit test
> Check wei balance in associate tx handling

- x/evm/state/utils_test.go
> Fix unit test

- app/upgrades.go
> V4.1.8 evm devnet release 2

- x/evm/types/keys_test.go
- x/evm/types/message_evm_transaction_test.go
- x/evm/types/message_send_test.go
- x/evm/types/params.go
- x/evm/types/params_test.go
Add unit tests for edge cases
Unit tests pass
> Add x/evm/types unit tests

- go.mod
- go.sum
- Bump s sei-db to v0.0.35
- Fixes proof query issue
- Verified on local chain
> Bump SeiDB (Seiv2)

- go.mod
- go.sum
- Bump s sei-db to v0.0.35
- Fixes proof query issue
- Verified on local chain
> Bump Seidb

- go.mod
- go.sum
- updates sei-tendermint
- this includes an adjustment to prevent duplicate nonces from making it past the mempool
- also includes metrics for mempool (added/removed)
- unit testing
- load testing
> [EVM] update sei-tendermint v0.2.41-seiv2

- x/evm/ante/error.go
- x/evm/ante/error_test.go
- adds new ante handler tests for error handler 
- new unit tests
> [EVM] Add error antehandler tests

- x/evm/client/cli/tx.go
Usage: `seid tx evm deploy <path to bin> --from=<key>`
local sei
> Add CLI command to deploy EVM contract

- loadtest/config.json
- loadtest/main.go
- loadtest/types.go
Add loadtest config for querying logs of the deployed ERC20 contract
loadtest
> Add loadtest for filter logs

- contracts/src/EVMCompatibilityTester.sol
- contracts/test/EVMCompatabilityTester.js
- adding bytes type to hardhat test 
- new test
> [EVM] Add bytes to hardhat check

- app/upgrades.go
- Adds `v3.9.0` upgrade
- Migration added to add cosmos gas params
- Tested on local chain param chain proposal + migration in upgrade
- Testing again on loadtest
> v3.9.0 Upgrade

- proto/tokenfactory/tx.proto
- x/tokenfactory/client/cli/tx.go
- x/tokenfactory/keeper/bankactions.go
- x/tokenfactory/types/codec.go
- x/tokenfactory/types/msgs.go
Remove dead unused code in the repo
> Remove dead unused code

- CHANGELOG.md
> v3.9.0 Changelog

- .github/workflows/compatiblity_check.yml
- .github/workflows/eth_blocktests.yml
> Update seiv2 CI to use main

- CHANGELOG.md
- app/upgrades.go
Register v5.0.0 upgrade and update changelog (updated with compare links due to large number of commits
> Add v5.0.0 upgrade

- app/app.go
- precompiles/addr/addr.go
- precompiles/bank/bank.go
- precompiles/common/precompiles.go
- precompiles/distribution/distribution.go
- precompiles/gov/gov.go
- precompiles/ibc/ibc.go
- precompiles/json/json.go
- precompiles/oracle/oracle.go
- precompiles/pointer/pointer.go
- precompiles/pointerview/pointerview.go
- precompiles/setup.go
- precompiles/staking/staking.go
- precompiles/wasmd/wasmd.go
- x/evm/client/cli/common.go
- x/evm/client/cli/query.go
- x/evm/client/cli/tx.go
rebase of https://github.com/sei-protocol/sei-chain/pull/1575
> Cleanup EVM CLI

- CHANGELOG.md
- app/upgrades.go
> Register v5.0.1 upgrade and update changelog

- scripts/initialize_local_chain.sh
> Update init script to enable seidb and occ

- x/evm/keeper/address_test.go
- x/evm/keeper/coinbase_test.go
- x/evm/keeper/genesis_test.go
- x/evm/keeper/nonce_test.go
- x/evm/keeper/receipt_test.go
- x/evm/keeper/tx_test.go
- x/evm/keeper/whitelist_test.go
add unit tests for files missing tests
unit tests
> Add EVM keeper unit tests

- x/evm/genesis_test.go
- x/evm/module.go
- x/evm/module_test.go
This PR add more unit test coverage for x/evm
Unit test
> Add unit test for x/evm

- x/evm/client/cli/native_tx.go
- x/evm/client/cli/tx.go
Usage:
```bash
seid tx evm register-pointer ERC20 0x...... --from=tony --fees=200000usei
```
local sei
> Add CLI to register CW->ERC pointers

- contracts/src/ERC721.sol
- contracts/test/CW721toERC721PointerTest.js
- contracts/test/lib.js
- integration_test/evm_module/scripts/evm_interoperability_tests.sh
- adds query tests for cw721 
- adds transfer / approve tests
- new integration test
> [EVM] Add cw721 to erc721 tests

- go.mod
- go.sum
- Bump seidb version to latest 
- Launched local chain, verified fix
> Bump SeiDB version

- cmd/seid/cmd/root.go
- evmrpc/config.go
- evmrpc/config_test.go
- evmrpc/server.go
- evmrpc/subscribe.go
Add a limit for the number of concurrent subscription that can exist at a given moment in time, and make it configurable
patched on rhino node
> Limit number of subscriptions

- evmrpc/info.go
- evmrpc/info_test.go
- evmrpc/server.go
- evmrpc/tx_test.go
- for safety validate params 
- uses same max blocks value as log history
- new unit test
> [EVM] validate eth_getFeeHistory params

- precompiles/addr/addr.go
- precompiles/bank/bank.go
- precompiles/distribution/distribution.go
- precompiles/gov/gov.go
- precompiles/ibc/ibc.go
- precompiles/json/json.go
- precompiles/oracle/oracle.go
- precompiles/pointer/pointer.go
- precompiles/pointer/pointer_test.go
- precompiles/pointerview/pointerview.go
- precompiles/staking/staking.go
- precompiles/wasmd/wasmd.go
- precompiles/wasmd/wasmd_test.go
- x/evm/keeper/msg_server.go
- x/evm/state/statedb.go
Surface precompile-level error to be persisted in receipts
unit tests
> Surface precompile error

- x/evm/types/codec.go
Allows for upgrading pointers through a gov proposal. Allows allows for these `seid tx evm` commands to go through:
```
add-erc-cw20-pointer   Submit an add ERC-CW20 pointer proposal
add-erc-cw721-pointer  Submit an add ERC-CW721 pointer proposal
add-erc-native-pointer Submit an add ERC-native pointer proposal
```
manual testing.
> Unregistered EVM NewProposalHandler

- app/upgrades.go
> Add v5.2.1 and v5.2.2 upgrade handler

- precompiles/pointer/Pointer.sol
- precompiles/pointer/pointer.go
- precompiles/wasmd/wasmd.go
- x/evm/client/cli/query.go
- x/evm/handler.go
- x/evm/keeper/msg_server.go
- x/evm/keeper/precompile.go
- Add wasmd in payablePrecompiles list
- RegisterPointer unregistered in msgServer handler 
- The client should check the correctness of the parameters
- execute_batch should use GetSeiAddress
unit tests
> Multiple Sec3 fixes

- x/evm/ante/preprocess.go
- x/evm/types/events.go
Emit event that indicate the signer(s) of a transaction in both Sei address and EVM address
local sei
> Emit signer event for all transactions

- go.mod
- go.sum
> bump sei-cosmos

- contracts/test/ERC20toNativePointerTest.js
- contracts/test/lib.js
- integration_test/evm_module/scripts/evm_interoperability_tests.sh
This adds hardhat tests for erc20 -> native pointers.
> Add native pointer erc20 tests

- app/app.go
- docker/rpcnode/Dockerfile
- go.mod
- go.sum
- integration_test/chain_operation/snapshot_operation.yaml
Reverts sei-protocol/sei-chain#1653
> Revert "Fix genesis export command"

- CHANGELOG.md
- app/app.go
- app/upgrades.go
- x/evm/module.go
- x/evm/module_test.go
> v5.5.1 & v5.5.2 release

- go.mod
- go.sum
- proto/evm/gov.proto
- x/evm/client/cli/gov_tx.go
- x/evm/client/cli/tx.go
- x/evm/gov.go
- x/evm/gov_test.go
- x/evm/handler.go
- x/evm/keeper/pointer.go
- x/evm/types/codec.go
- x/evm/types/gov.go
- x/evm/types/gov.pb.go
Add new proposal types to register/unregister CW->ERC pointers, similar to what we already have in gov for ERC->CW pointers.
unit test
> Add gov proposal type to modify CW->ERC pointer registration

- contracts/test/CW20toERC20PointerTest.js
- contracts/test/CW721toERC721PointerTest.js
- contracts/test/ERC20toCW20PointerTest.js
- contracts/test/ERC721toCW721PointerTest.js
- contracts/test/lib.js
- x/evm/types/gov.go
- registers the pointer registration types (bugfix)
- adds integration test for upgrading a cw20->erc20 pointer
- passes via governance proposal in the test
- new integration test
> [EVM] Add upgrade cw->erc20 pointer test

- evmrpc/tracers.go
- evmrpc/tracers_test.go
This PR add a new EVM rpc endpoint debug_traceCall: https://docs.chainstack.com/reference/ethereum-tracecall
Added unit test
> Add evm rpc endpoint debug_traceCall

- go.mod
- go.sum
> Bump geth to v1.13.5-sei-21

- contracts/test/ERC20toNativePointerTest.js
- contracts/test/lib.js
- precompiles/bank/bank.go
- added test to verify association requirements for native tokens
- new test
> [EVM] add test for receiving tokens by unlinked wallet

- CHANGELOG.md
- app/upgrades.go
- Add v5.5.5 upgrade
- Tested on local chain
> Add v5.5.5 upgrade

- contracts/test/CW20toERC20PointerTest.js
- contracts/test/lib.js
- evmrpc/tx.go
- precompiles/wasmd/wasmd.go
- precompiles/wasmd/wasmd_test.go
- x/evm/client/cli/common.go
- x/evm/keeper/evm.go
- x/evm/keeper/evm_test.go
This reverts commit d065752ff931347f4148b4938c687de399ee85c3.
> Revert "Remove interoperability hop limit with isolated EVM instances (#1729)"

- CHANGELOG.md
- go.mod
- go.sum
Update CHANGELOG and go mod dependencies for the v5.6.0 upgrade
> Update dependencies and changelog for v5.6.0 upgrade

- precompiles/distribution/distribution.go
- precompiles/distribution/distribution_test.go
Adding delegation and static call check to distribution precompile
- unit tests
- reproduced the issue (using methods stated in report) and then validated does not reproduce after the fix
- functional test in progress
> Add delegation and static call check

- go.mod
- go.sum
> Fix compatibility CI

- app/app.go
- app/app_test.go
For transactions that fail to decode, we will set it to nil. There are several places where we weren't handling such nil txs properly. This PR addresses those places.
unit tests
> handle nil tx properly

- CHANGELOG.md
- app/upgrades.go
> Add v5.7.0 upgrade

- app/app.go
- app/upgrades.go
> Add v5.7.1 upgrade

- CHANGELOG.md
- app/app.go
- app/upgrades.go
- go.mod
- go.sum
> V5.7.2 release

- app/app.go
Update evidence max bytes
- Testing queries on node to verify that they match the evidence max bytes
> Evidence Max Bytes Update

- app/receipt_test.go
- contracts/test/ERC20toNativePointerTest.js
- contracts/test/EVMCompatabilityTest.js
- x/evm/integration_test.go
- x/evm/module_test.go
- x/evm/types/params.go
> Tune Configs

- go.mod
- go.sum
This will fix two issues for archive node:
- Archive node start up will not cause OOM any more
- Archive node start up will not take more than 5 minutes
> Bump IAVL version

- go.mod
- go.sum
- precompiles/bank/bank_test.go
- run_blocktests.sh
- x/evm/keeper/replay.go
pull in the gas refund change https://github.com/sei-protocol/go-ethereum/pull/32 in sei-chain
existing tests
> bump geth to pull in gas refund changes

- contracts/test/ERC20toCW20PointerTest.js
- contracts/test/ERC721toCW721PointerTest.js
- evmrpc/block.go
- evmrpc/block_test.go
- evmrpc/filter.go
- evmrpc/filter_test.go
> Exclude only shell receipts from eth endpoints v5.9.0

- go.mod
- go.sum
> Bump CW versions

- app/receipt.go
> use infinite gas meter for wasm query context

- app/receipt.go
- contracts/test/ERC721toCW721PointerTest.js
- contracts/test/EVMCompatabilityTest.js
- contracts/test/lib.js
- go.mod
- go.sum
- x/evm/ante/fee.go
> Bump sei-cosmos to integrate with DeliverTxHook change

- .github/workflows/integration-test.yml
- app/receipt.go
- contracts/test/ERC20toCW20PointerTest.js
> Use limited wasm gas meter

- go.mod
- go.sum
> bump sei-tendermint to v0.4.3 for improving blocksync and p2p issue

- CHANGELOG.md
- app/upgrades.go
- go.mod
- go.sum
- tools/migration/sc/migrator.go
> v6.0.0 release

- app/upgrades.go
- x/evm/migrations/migrate_eip_1559_max_base_fee_test.go
- x/evm/module.go
- x/evm/module_test.go
- x/evm/types/params_test.go
Missing bump of consensus version, which broke the migration process.
tested upgrade on a local chain
> Fix max base fee upgrade

- .github/workflows/integration-test.yml
- integration_test/confidential_transfers_module/apply_pending_balance_test.yaml
- integration_test/confidential_transfers_module/close_account_test.yaml
- integration_test/confidential_transfers_module/deposit_test.yaml
- integration_test/confidential_transfers_module/initialize_account_test.yaml
- integration_test/confidential_transfers_module/transfer_test.yaml
- integration_test/confidential_transfers_module/withdraw_test.yaml
- x/confidentialtransfers/keeper/msg_server.go
- x/confidentialtransfers/keeper/msg_server_test.go
- x/confidentialtransfers/types/account.go
- x/confidentialtransfers/types/apply_pending_balance.go
- x/confidentialtransfers/types/expected_keepers.go
- x/confidentialtransfers/utils/utils.go
- x/confidentialtransfers/utils/utils_test.go
We want to add a set of integration tests that test module end to end, calling the methods from the CLI
Added tests so far for
- Initialization
- Deposit
- Withdraw
- ApplyPendingBalances
Also found a bug in the CLI in how we calculate the combined pending balances in ApplyPendingBalances
-
> Add Integration tests for CT Module

- go.mod
- go.sum
- precompiles/bank/bank_test.go
> revert: 150% gasUsed refund limit policy

- go.mod
- go.sum
Return UTC formatted error message for IBC timeout error
- Unit test
> - king nodes IBC patch

- evmrpc/block.go
- evmrpc/block_test.go
> Exclude block receipts whose block number do not match

- go.mod
- go.sum
> update IBC version

- app/upgrades.go
> migrate min txs in block

- evmrpc/tracers.go
- go.mod
- go.sum
Force call `init` on the JS tracer package which registers the JS tracer
tested on a detached node
> support JS tracers

- app/receipt.go
- app/receipt_test.go
Previously the `data` field of 1155 batch events is encoded with a non-ABI-compliant format, which would cause applications that relies on ABI-compliance (e.g. ethers.js) to fail to parse such fields. This PR changes the `data` field to be parsed via ABI.
unit test
> Properly encode ERC1155 translated batch event data

- app/params/config.go
> Decrease mempool ttl defaults

- x/evm/keeper/grpc_query.go
- x/evm/keeper/grpc_query_test.go
- return error if required argument is not specified
- return consistent response for non-existent pointers/pointees
unit test
> Imporve pointer/pointee query UX

- x/confidentialtransfers/client/cli/query.go
- x/evm/client/cli/query.go
Add error checking for Marshalling CLI Query objects
Unit tests
> L-09 Proto Serialization Failures

- app/ante_test.go
- evmrpc/simulate.go
- evmrpc/simulate_test.go
- go.mod
- go.sum
- x/evm/module_test.go
- handle block number keywords for all endpoints
- pass the converted block number to geth api
todo
> tracer RPC fixes

- CHANGELOG.md
- app/upgrades.go
> V6.0.4 upgrade

- aclmapping/confidentialtransfers/mappings.go
- x/confidentialtransfers/keeper/msg_server.go
- x/confidentialtransfers/keeper/msg_server_test.go
- x/confidentialtransfers/types/expected_keepers.go
Support allow lists feature in CT to restrict deposits/withdrawals/transfers
- unit tests
> adding allowlist to CT

- evmrpc/filter.go
- evmrpc/filter_test.go
- evmrpc/tests/log_test.go
- evmrpc/tests/mock_accounts.go
- evmrpc/tests/mock_contracts.go
- evmrpc/tests/tx.go
- evmrpc/tests/utils.go
- evmrpc/utils.go
Refactor log logics and unit tests
unit tests
> Refactor RPC log logics

- CHANGELOG.md
- app/upgrades.go
- go.mod
- go.sum
> v6.0.5 upgrade

- go.mod
- go.sum
bump sei-cosmos version
existing unit tests
> bump sei-cosmos to v0.3.57

- evmrpc/block.go
- evmrpc/tx.go
> Fix receipt tx index confusion

- evmrpc/filter.go
- Removes panic in evmrpc filter method
- Surfaces first error
> Remove Evmrpc Filter Panic

- evmrpc/filter.go
- Filter evmrpc instead of panic surface first error and return
> Filter EVM Rpc default case

- .github/workflows/docker_build.yml
- CHANGELOG.md
- Dockerfile
- app/test_state_store.go
- go.mod
- go.sum
> Update changelog and seidb

- app/seidb.go
This PR is adding the newly introduced SC config: OnlyAllowExportOnSnapshotVersion
> Add new sc config OnlyAllowExportOnSnapshotVersion for sei-chain

- contracts/test/EVMCompatabilityTest.js
- go.mod
- go.sum
pulls in geth change, please see for context: https://github.com/sei-protocol/go-ethereum/pull/56. 
existing tests + add tests for debug_trace with no gas params
> Make MaxFee and MaxPriorityFee optional for eth_call (NoBaseFee: true)

- evmrpc/filter.go
- evmrpc/filter_test.go
> fix: blockhash issue in eth_getlog

- evmrpc/filter.go
- evmrpc/filter_test.go
> fix: use evm only index in eth_getLogs

- app/ante.go
- app/app.go
- precompiles/bank/bank_test.go
- x/evm/ante/fee.go
- x/evm/ante/fee_test.go
- x/evm/client/wasm/query_test.go
- x/evm/keeper/msg_server_test.go
> Make EVM Antehandler getBaseFee backwards compatible

- .github/workflows/unit_tests.yml
> use normal runner for unit tests

- occ_tests/messages/test_msgs.go
- occ_tests/occ_test.go
- occ_tests/utils/utils.go
- adds determinism testing for occ pointer deploys 
- see unit test
> Add occ test for pointers

- evmrpc/tx.go
IMO drastically simplifies the function and makes it more readable.
CI is triggering the appropriate test suite.
> Refactor `GetEvmTxIndex`

- .github/workflows/pr-to-slack-codex.yml
- Explicitly set model to gpt-5
Verified: Slack thread with review https://sei-network-io.slack.com/archives/C09999UP1JT/p1755548874786079
> GPT-5 in Codex

- .github/CODEOWNERS
> Add yzang2019 to codeowners

- app/test_helpers.go
- evmrpc/block.go
- evmrpc/block_test.go
- evmrpc/filter.go
- evmrpc/rpcstack.go
- evmrpc/send.go
- evmrpc/server.go
- evmrpc/setup_test.go
- evmrpc/simulate.go
- evmrpc/simulate_test.go
- evmrpc/tracers.go
- evmrpc/tx.go
- evmrpc/tx_test.go
- evmrpc/utils.go
- loadtest/sign.go
- cache receipts in memory
- only load nonce for applicable txs to reduce reads
tested on archive node
> optimize GetLogs performance
