- app/ante.go
This will allow transactions with the same content to be processed as long as they are not received simultaneously (i.e. not having the same sequence number)
> Re-enable sequence increment decorator

- app/app.go
- app/upgrades.go
- x/dex/module.go
- x/epoch/module.go
- x/oracle/module.go
- Add new store for `oracle` if the chain is upgraded from an older version when `oracle` doesn't exist
- Add no-op migration handlers for all modules
> Add upgrade handlers

- x/oracle/abci.go
- x/oracle/abci_test.go
- x/oracle/common_test.go
- x/oracle/keeper/test_utils.go
- x/oracle/tally.go
This updates the oracle logic to differ from the Terra behavior. We want the oracle to penalize abstaining from votes by counting them as misses, and to also count unmet quorum as miss for validator/oracles that don't provide in-range values to prevent collusion to avoid meeting quorum.
> [oracle] Update miss calculation for abstaining and unmet quorum

- app/app.go
- app/const.go
- cmd/seid/main.go
- cmd/seid/root.go
Set the prefix for accounts to start with `sei` rather than `cosmos`. Also do some small refactoring.
Started the chain and created account. Checked validator addr:
Account
```
> ./build/seid keys add seiprefixacc
- name: seiprefixacc
type: local
address: sei1pryw5ymj6dgq90ulsgvxan374nd0qy50lwnrd5
```
Validator
```
> ./build/seid q tendermint-validator-set
block_height: "4"
total: "1"
validators:
- address: seivalcons1p9pvsyjgyqjd5gppqh7dfs89kqgmacgm420hsq
proposer_priority: "0"
```
> Fix address prefix to sei

- app/app.go
- app/encoding.go
- app/params/amino.go
- app/params/config.go
- app/params/doc.go
- app/params/encoding.go
- app/params/proto.go
- cmd/seid/cmd/genaccounts.go
- cmd/seid/cmd/init.go
- cmd/seid/cmd/root.go
- cmd/seid/main.go
- go.mod
- testutil/network/network.go
Remove ignite/starport CLI from our codebase so that we can set configs (config.toml, app.toml) at the sei code level (see `cmd/seid/cmd/init.go`. This will allow everyone running the chain to have unified configs that we can control and change with upgrades.
- Verified that starport no longer exists: 
```
~/sei-chain  rm-ignite-cli *1 ?1  seid version --long | grep star                                                     ok  21:04:40
~/sei-chain  rm-ignite-cli *1 ?1
```
- Start and restart a chain with default chain name
- Start and restart a chain with a unique name
- Create account
- List keys
- Send funds from one account to another
- Query validator set
- Create a param change proposal
- Voted on proposal
- Verified proposal passed
> Remove ignite/starport cli from codebase

- app/abci.go
- app/app.go
- app/app_test.go
- app/test_helpers.go
- x/dex/cache/cache.go
- x/dex/keeper/end_block_cancel_orders.go
- x/dex/keeper/end_block_liquidation.go
- x/dex/keeper/end_block_place_orders.go
- x/dex/keeper/keeper.go
- x/dex/keeper/msg_server_liquidate.go
- x/dex/keeper/msg_server_register_contract.go
- x/dex/module.go
Instead of looping over a map, we will fetch a slice of registered pairs first, and then iterate over the slice and get map's value keyed by each pair, so that the iteration is deterministic.
> Use slice based loop instead of map based loop in Begin/EndBlock

- app/upgrades.go
- cmd/seid/cmd/init.go
Set default commit timeout to 1 second
> Set commit timeout to 1 second

- loadtest/main.go
- loadtest/sign.go
- loadtest/tx.go
- scripts/initialize_local_test_node.sh
- x/dex/keeper/end_block_place_orders.go
- x/dex/keeper/end_block_place_orders_test.go
Fix scripts used by loadtest to work with sequence numbers properly. Tested on local chain with 1000 accounts.
> Fix loadtest scripts

- x/dex/exchange/market_order.go
- x/dex/exchange/market_order_test.go
- x/dex/exchange/settlement.go
We use a uniform clearing price for all market orders for the same pair in the same block.
The old clearing price calculation logic is the weighted average of the mid point between market order's price limit and order book order's price limit. Such calculation has been shown to be vulnerable to exploitations.
The new clearing price calculation is the weighted average of only order book side's price limit.
Tested with unit tests
> Fix market order clearing price calculation

- app/ante.go
- x/dex/ante.go
This PR does two things:
1. Add a whitelist (currently hardcoded but will be parameterized in a subsequent PR) for addresses that can cancel orders gaslessly.
2. Ensure order placements and order cancellations (for whitelisted accounts) are truly gasless by overriding the gas meter in TX's context to an infinite gas meter
Tested on local chain
> Gasless transaction fixes

- x/dex/keeper/keeper.go
- x/dex/keeper/params.go
- x/dex/migrations/v3_to_v4.go
- x/dex/module.go
Set default param during migration. Tested in local chain
> Add migration handler for new DEX params

- x/dex/migrations/v3_to_v4.go
- x/dex/migrations/v3_to_v4_test.go
- x/dex/module.go
Add unit tests as well as tested with correct previous commit on local chain
> fix migration and add tests

- scripts/oracle/abstain_oracle_voting.py
Tested locally with 1.0.4beta sei-chain: 
`python3 abstain_oracle_voting.py cyson sei-chain 12345678 ""`
> Add oracle price abstaining script

- x/oracle/types/params.go
We need `sei`'s price for both integration test as well as incentivized testnet.
> [oracle] add sei to whitelist

- wasmbinding/test/query_test.go
- x/oracle/keeper/querier.go
- x/oracle/keeper/querier_test.go
Without explicitly initializing as empty array, the response would be nil, which will cause contract-side parsing to fail
> Fix query empty exchange rates

- app/app.go
- scripts/initialize_local_test_node.sh
- x/dex/client/cli/gov_tx.go
- Register `gov` router after `dex` keeper is instantiated, instead of before
- Add common flags (e.g. `--from`) to `NewRegisterPairsProposalTxCmd`
- Minor fixes to local chain script
> Fix register pair proposal

- app/antedecorators/gasless.go
- app/antedecorators/gasless_test.go
Make GaslessDecorator to still call `next` so that we don't skip ante handlers. Also added unit test to ensure all decorators run.
> [Sei] fix ante decorators

- app/params/config.go
Set consensus configs to be more relaxed (100 -> 250ms) so testnet is more stable.
> Set consensus timeouts to 250ms

- loadtest/main.go
- loadtest/sign.go
- loadtest/tx.go
Fix loadtest to use the new data structure
> Fix loadtest

- app/app.go
in the `sei-cosmwasm` package, there is [the following TODO item](https://github.com/sei-protocol/sei-cosmwasm/blob/1bf3aeebbce891265f715dd7e5b6d4c117992b1a/packages/sei-cosmwasm/src/lib.rs#L18-L22):
```rust
// TODO: properly support this requirement behavior in sei-chain
// // This export is added to all contracts that import this package, signifying that they require
// // "sei" support on the chain they run on.
// #[no_mangle]
// extern "C" fn requires_sei() {}
```
to enable this feature is easy, just add `sei` to the [`supportedFeatures`](https://github.com/sei-protocol/sei-chain/blob/9fb298f9850d02007dbad3e1d752153392ee91bd/app/app.go#L455) variable in `app.go`:
```diff
- supportedFeatures := "iterator,staking,stargate"
+ supportedFeatures := "iterator,staking,stargate,sei"
``` …
> enable `sei` feature for wasm contracts

- x/dex/exchange/market_order.go
- x/dex/keeper/end_block_liquidation.go
- x/dex/keeper/end_block_liquidation_test.go
- x/dex/module.go
Use `types.GetPairString(&pair)` as map key. This is the only non-testing place where `GetPairString` is not used.
Tested in integration tests
> Fix liquidation order placement

- x/dex/migrations/v4_to_v5.go
- x/dex/migrations/v4_to_v5_test.go
- x/dex/module.go
Add a migration handler for `dex` v5 that nukes everything in `dex` store
> Add v4 to v5 migration handler

- x/dex/exchange/limit_order.go
- x/dex/migrations/v2_to_v3.go
- x/dex/migrations/v4_to_v5.go
- x/dex/migrations/v4_to_v5_test.go
- x/oracle/client/rest/query.go
The production store doesn't accept empty byte array as a prefix, so we will just iterate through all possible byte values and clear those prefixes one-by-one.
> Fix v4 to v5 migration handler

- x/dex/keeper/gov.go
- x/dex/keeper/msg_server_place_orders.go
- remove register pair restriction to be in asset list
> Remove register pair restriction

- x/dex/example/add-asset-metadata-proposal.json
- x/dex/example/register-pair-proposal.json
- x/dex/example/update-tick-size-proposal.json
- Dex Asset List and Register Pair proposals should be the same denom as the price denom (accepted as deposits)
- Updates all display types (key for asset list) to micro denom e.g. "usei"
> Update example proposals display type to micro denom

- x/dex/module.go
- x/dex/module_test.go
- Explicitly sort order book entries before matching. Long term we should avoid this sorting by making sure the entries are stored and iterated in order in the store.
- Mark order objects as cancelled if a market order is not filled
> Fix issues found during bug bash

- app/app.go
> Bump wasm size limit to 1MB

- x/dex/module.go
- x/dex/module_test.go
Right now market order status would stay as `PLACED` even after it's fully executed. It makes more sense for its status to be updated to `FULFILLED` in such cases.
> Set status to be fulfilled if market order is fully executed

- x/dex/module.go
- x/dex/module_test.go
`pair.String()` is unstable as sometimes the `Pair` struct may not specify ticksize. Using `types.GetPairString(&pair)` avoids this problem.
> Fix settlements write logic

- app/app.go
- app/upgrade_test.go
- app/upgrades.go
Adds a check that the upgrade names are in alphabetical order before the handlers are registered. 
This will only prevent users from appending non-alphabetical ordering names. I think if we wanted to catch the case where users are inserting a "valid" upgrade name in between two past upgrades, we would need to know additional metadata (when it was added) or if an upgrade was already applied in the past. 
Note, I had to remove `"ignite-cli-removal-upgrade"` as it was conflicting with the alphabetical ordering assertion. It was causing the test to fail. 
1. make install 
2. fresh instance of the chain 
3. propose 1.0.8beta at 25
4. restart chain with 1.0.8beta handler added  and proceeds fine 
5. propose 1.0.0beta and add handler to code after it stops
6. try to start and see that it errors …
> Assert that upgrade names are sorted

- cmd/seid/cmd/root.go
- On chain init (`seid init` ) enables usdc as gas price
- Validators can always change this in their `app.toml`
> Add usdc to min gas prices

- loadtest/main.go
- loadtest/scripts/populate_genesis_accounts.py
- x/dex/exchange/market_order_test.go
- Overwriting the existing file should not throw error
- Create accounts with keyring backend. For some reason, this works in integration but on loadtest, without this param it ends up creating it with a password which doesn't seem to work with the loadtest script: https://github.com/sei-protocol/sei-chain/blob/master/loadtest/sign.go#L29
> Loadtest fixes

- app/app.go
- app/upgrades.go
Ran into this when doing internal upgrade. Fixed by adding prev upgrade handlers
```
4:32AM INF Replay last block using real app module=consensus
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x165dbcd]
goroutine 1 [running]:
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()
/root/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.6.3/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc0000c6600, {0x0, 0x0, 0x35ca3c0?})
/root/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.6.3/trace/span.go:398 +0x8dd
panic({0x1b53140, 0x3510750})
/usr/local/go/src/runtime/panic.go:838 +0x207 …
```
> Add missing upgrade handlers

- x/oracle/types/params.go
We need lower the oracle quorum to enable the oracle in the incentivized testnet
> Decrease oracle quorum lower bound

- scripts/oracle/price_feeder.py
Allows one to configure feeder account with `seid tx oracle set-feeder <addr>` and using that on the feeder script instead of exposing operator keys. Need to give the validator's valoper as the new parameter.
> Add support for using price feeder account

- x/dex/keeper/msgserver/msg_server_place_orders.go
- x/dex/keeper/msgserver/msg_server_place_orders_test.go
For some reason `sdk.Dec` in a proto type can be initialized as `sdk.Dec{}`, which will cause nil pointer exception if used for arithmetic purposes.
Also removed tracing which is no longer in use.
> Add order validation

- x/dex/module.go
- x/dex/module_test.go
For now we will catch all panics in EndBlock so that bugs won't cause the chain to be halted. Each panic will result in a metric being incremented with the error description as the label.
We will need to remove this catch before mainnet launch to prevent silent failing
> Catch all panics in DEX EndBlock

- x/dex/module.go
- x/epoch/module.go
- x/mint/module.go
- x/oracle/module.go
Since we have custom logics for:
- `epoch` BeginBlock
- `dex` BeginBlock and EndBlock
- `mint` BeginBlock
- `oracle` EndBlock
We will also be adding catch-all logics just for the testing phase so that the chain isn't halted frequently. These need to be removed before mainnet launch.
> Add catch-all for all custom modules

- loadtest/main.go
- loadtest/sign.go
Fixes error on `/root/outputs` dir already existing when creating a file. Also uses "test" keyring backend so no password is required, and fixes homedir to be .sei
> Fixes for loadtest

- store/testutils.go
- store/whitelist/cachemulti/store.go
- store/whitelist/cachemulti/store_test.go
- store/whitelist/kv/store.go
- store/whitelist/kv/store_test.go
- store/whitelist/multi/store.go
- store/whitelist/multi/store_test.go
Add store wrapper such that only writes to whitelisted keys are permitted. Reads are not affected by the whitelist and can be made against any key.
These stores will be used to ensure no race condition during parallel execution. Specifically, each goroutine can instantiate a whitelisted MultiStore and set it to its context. The goroutine would then only be able to write to the whitelisted keys and thus prevent any race condition unless the same key is whitelisted in multiple concurrent goroutines.
> Add whitelist store utility

- app/app.go
Enables snapshot manager to fix statesync 
For the node I wanted to catch up, i just followed this to set the block height and the hash (including setting perisstent peer and restarting the seid daemon)
https://docs.seinetwork.io/nodes-and-validators/statesync
Then for the node0, that I used as a persistent peer i updated `~/.sei/config/app.toml`  to set the snapshot-interval as it was disabled in the past (set to 0)
Restarted seid service on node0 with `systemctl restart seid` and see that the new node was able to find a snapshot and caught up 
See that both have the same wasm folder:
Note:
Juno and Osmosis had the same PR:
https://github.com/osmosis-labs/osmosis/commit/8e1b6201a514fb3970c3d6537342d66f38ba0446
https://github.com/CosmosContracts/juno/commit/375c9015c7db73f54b320d6004e8c496 …
> Fix Statesync with snapshot manager

- .github/workflows/fuzz.yml
- .gitignore
- testutil/fuzzing/dex.go
- x/dex/exchange/cancel_order.go
- x/dex/exchange/limit_order_fuzz_test.go
- x/dex/exchange/market_order_fuzz_test.go
- x/dex/exchange/rebalance.go
- x/dex/exchange/rebalance_fuzz_test.go
- x/dex/exchange/settlement.go
- x/dex/exchange/settlement_fuzz_test.go
Add fuzz testing for
- limit order matching
- market order matching
- limit order settlement
- market order settlement
- rebalance
and fixed issues found during fuzzing
> Add fuzz testing for exchange logics

- go.mod
- go.sum
- proto/dex/contract.proto
- utils/slice.go
- utils/slice_test.go
- x/dex/contract/dag.go
- x/dex/contract/dag_test.go
- x/dex/handler.go
- x/dex/keeper/contract.go
- x/dex/keeper/msgserver/msg_server.go
- x/dex/keeper/msgserver/msg_server_cancel_orders.go
- x/dex/keeper/msgserver/msg_server_liquidate.go
- x/dex/keeper/msgserver/msg_server_place_orders_fuzz_test.go
- x/dex/keeper/msgserver/msg_server_place_orders_test.go
- x/dex/keeper/msgserver/msg_server_register_contract.go
- x/dex/keeper/msgserver/msg_server_register_contract_test.go
- x/dex/keeper/msgserver/msg_server_test.go
- x/dex/migrations/v5_to_v6.go
- x/dex/migrations/v5_to_v6_test.go
- x/dex/module.go
- x/dex/types/contract.pb.go
According to parallelization design discussed in https://www.notion.so/3pgv/RFC-dex-EndBlock-Parallelization-96188f5904f94172a7fdd7d2bac196f3#5937b9bab86e46dc97b8cc7d8b516007 , we will now maintain the immediate sibling (both younger and elder) for each inter-contract dependency. This PR:
- replaces `ContractInfo`'s existing field of `DependentContractAddrs` with a new `Dependencies` field which is an array of struct `ContractDependencyInfo` that keeps track of siblings. The old `ContractInfo` is renamed to `LegavcyContractInfo` for migration purposes.
- adds a `numIncomingDependencies` field to record the number of contracts that depend on the current contract.
- adds logics in `msg_server_register_contract` to keep the new fields updated whenever a contract is added/updated
- adds `dex` …
> Update ContractInfo data structure

- app/params/config.go
- loadtest/config.json
- loadtest/main.go
- loadtest/scripts/metrics.py
- store/whitelist/cachemulti/store_test.go
- store/whitelist/multi/store_test.go
- x/dex/ante.go
- x/dex/module_test.go
This PR changes it so that the client doesn't limit the number of txns / block since that's ultimately what we're trying to benchmark. Instead, we now send as many txns as possible and specify `rounds` - which is the number of times the accounts should loop and send txns. Includes other optimizations (see inline comments).
> Loadtest client fixes

- scripts/oracle/price_feeder.py
- scripts/oracle/price_fetcher.py
Fixes a crash when API limit is hit when fetching price data. And sleep 60 seconds in this case to make sure we have quota for the next price query.
> Handle error when fetching price data

- wasmbinding/bindings/msg.go
- wasmbinding/encoder.go
- wasmbinding/test/encoder_test.go
- x/dex/client/wasm/encoder.go
- Removes the `Creator` and `ContractAddr` field from wasmbinding messages in dex
> Remove signer in dex wasmbinding messages

- x/dex/keeper/query/grpc_query_settlements.go
- x/dex/keeper/query/grpc_query_settlements_test.go
- x/dex/keeper/settlement.go
- x/dex/keeper/settlements_test.go
- x/dex/migrations/v7_to_v8.go
- x/dex/migrations/v7_to_v8_test.go
- x/dex/module.go
- x/dex/module_test.go
- x/dex/types/keys.go
Previously, settlement entries for the same order ID are stored as a list under a single KV store entry. This becomes inefficient as the list grows for certain large orders, as the chain would need to read and write some very large lists even if there is only one settlement entry added in a particular block.
We optimize this by storing settlement entries as individual KV store entries. Specifically, each `contract-pair-orderID` combo now has an associated incrementing counter that provides a settlement ID for each settlement entry in a deterministic way. There is no need to read all historical settlement entries during `dex` EndBlock anymore. Corresponding migration handler is also included in this PR.
For frontend queries, we will add pagination for settlement entries in a separate PR.
> Optimize settlements storage

- x/dex/contract/abci.go
- x/dex/contract/execution.go
- x/dex/keeper/abci/end_block_deposit.go
- x/dex/keeper/abci/end_block_place_orders.go
- x/dex/module.go
Fix spans so they use the same context (otherwise they don't show up under the same request).
Additionally, fix the endblockpanic alert since we cannot glob over titles (only labels).
Span: <img width="1892" alt="image" src="https://user-images.githubusercontent.com/3821073/183821536-7663f607-9684-434a-a1ea-28e1661632a1.png">
Page: https://seinetwork.pagerduty.com/incidents/Q3UV2GHWDHQWQR
> Fix spans and endblockpanic alert

- Makefile
- loadtest/contracts/deploy_ten_contracts.sh
- scripts/old_initialize_local.sh
- sync/gas.go
- utils/panic.go
- x/dex/cache/cache.go
- x/dex/cache/cancel.go
- x/dex/cache/liquidation.go
- x/dex/cache/order.go
- x/dex/contract/abci.go
- x/dex/contract/execution.go
- x/dex/contract/market_order.go
- x/dex/contract/runner.go
- x/dex/exchange/limit_order_fuzz_test.go
- x/dex/exchange/limit_order_test.go
- x/dex/exchange/market_order.go
- x/dex/exchange/market_order_fuzz_test.go
- x/dex/exchange/market_order_test.go
- x/dex/keeper/utils/order_book.go
- x/dex/types/orders.go
- x/dex/types/wasm/block_hooks.go
Fixed all race conditions detected when running load test with `--race` flag on. Note that the race detector doesn't necessarily capture non-determinism, so testing on multiple nodes is still necessary even after this change.
> Fix race conditions detected by --race

- app/app.go
When new modules / keepers are introduced, a store migration must be introduced otherwise it will lead to state-sync consensus failures.
Tested in internal testnet, verified that upgrade works with this patch.
> Add tokenfactory keeper migration

- utils/panic.go
- x/dex/module.go
- x/epoch/module.go
- x/mint/module.go
- x/oracle/module.go
In order to create an alert, the metric name needs to be consistent. We make all of the alerts "end/begin"blockpanic and add module name to albels.
> Fix panic metrics

- app/export.go
- cmd/seid/cmd/root.go
- go.mod
- go.sum
- utils/metrics/README.md
- utils/metrics/metrics_util.go
- wasmbinding/bindings/msg.go
- x/dex/contract/runner.go
- x/dex/keeper/utils/wasm.go
- x/oracle/simulation/operations.go
Adds custom metrics to measure sei-specific logic, similar to measuring request duration in Web2. In this case, we need to measure the E2E latency on the client side as we are unable to export time-based metrics from WASM 
This is a more repeatable way of measuring the latency without manually adding print statements and parsing the query in an excel sheet
From http://grafana.sei-loadtest-testnet.seinetwork.io/d/ellgRxZ4k/sei-custom-metrics?orgId=1&var-instance=18.219.201.246:26660: 
Spikes line up with when I ran the load test 
* One thing to call out here is that there are a lot more bulk_cancel order calls here (almost 1-1 with the bulk order placements), which I believe is why there's no settlements
> Add Metrics to measure sudo calls 

- loadtest/main.go
- loadtest/sign.go
- utils/panic.go
- utils/panic_test.go
- x/dex/client/utils/utils.go
- x/dex/keeper/utils/wasm.go
- x/dex/module.go
- x/epoch/module.go
- x/mint/module.go
- x/oracle/module.go
In the case where the host of a sei chain deployment has its underlying architecture updated, `wasmer` VM instantiation will throw error. Right now we print out errors received during `sudo` calls since we thought they are all deterministic, but the aforementioned error type is not deterministic (as in, it will only happen to nodes that undergo such system level update). So to prevent the chain from ending up in a bad state, we would like it to crash when in such cases.
> Hard fail on wasmer instantiation error caused by missing CPU features

- x/tokenfactory/client/cli/query.go
- Fix tokenfactory query cli by removing the expected args for querying the create denom fee whitelist
> (Minor) Fix tokenfactory query cli

- app/abci.go
- app/ante.go
- app/app.go
- go.mod
- go.sum
- loadtest/sign.go
Upgrade to `sei-cosmos` version where sr25519 is the default
> Use SR25519 as signing algo

- x/dex/client/cli/tx/tx_cancel_orders.go
- x/dex/keeper/msgserver/msg_server_cancel_orders.go
- x/dex/keeper/msgserver/msg_server_cancel_orders_test.go
This PR fixes the cancellation msg_server and adds corresponding unit tests. 
Verified e2e locally.
> Fix order cancellation

- app/ante.go
- app/app.go
- app/export.go
- go.mod
- go.sum
- wasmbinding/bindings/msg.go
- x/oracle/simulation/operations.go
Adds ACL module to sei-chain 
Also had to make some fixes based on this PR:
https://github.com/sei-protocol/sei-cosmos/pull/23/files 
Tested this by starting a local chain with Phil script:
https://github.com/sei-protocol/sei-chain/pull/251/files#diff-eb97f7c509f5a70c4ca7de4773937b07c26a74d4d9142c5ec1c97896dece4318L1
> Register accesscontrol module 

- app/upgrades.go
also backfill the 1.2.0beta handle
> Add upgrade 1.2.1beta

- app/ante.go
- app/antedecorators/priority.go
- ante handler that processes transactions and caps priority that is solely determined by gas + assigns highest priority to oracle tx's
> Prioritize ante decorator

- app/app.go
- app/graph.go
- app/graph_test.go
- go.mod
- go.sum
- x/oracle/simulation/operations.go
Creates channels based on the DAG 
Pointing the PR to https://github.com/sei-protocol/sei-chain/pull/258 
Tested by running: ./scripts/old_initialize_local.sh
> Create Channels from DAG

- app/graph.go
- app/graph_test.go
- go.mod
- go.sum
This adds in the ability to create dependencies between resources of different types based on predefined resource hierarchies. Currently, for dependencies with the same resource, we are only performing exact matching on the identifier template, but we can modify that in the future to allow for partial matching and fuzzy matching for more control over dependency granularity.
> [graph] Add resource hierarchy to dependency graph

- app/app.go
- app/graph.go
Tested locally with sei chain and gov txs
> [app] Add behavior to process blocks with gov txs sync

- app/app.go
Nil indicates no errors 
See concurrent txs from running loadtest
> Fix for DAG building switch cases

- app/app.go
- loadtest/config.json
- loadtest/main.go
- loadtest/scripts/metrics.py
- loadtest/tx.go
Cherry picking phil's changes for load testing that I've been using in this branch https://github.com/sei-protocol/sei-chain/pull/284/commits 
And also merging a fix for completion channels 
Ran Loadtesting with on this branch (though not all the way though cus of the app_hash issue)
https://github.com/sei-protocol/sei-chain/pull/284/commits
> Cherry-pick loadtesting changes and make a fix for parallel tx

- app/export.go
- x/tokenfactory/keeper/createdenom.go
- Removes any sends to fund the community pool: Sending to community pool when charging a tokenfactory denom creation fee + sending to community pool scraps from unwithdrawn validator fees
- Tested locally by querying `seid query distribution community-pool` and verifying its empty
> Remove sends to community pool

- x/dex/types/codec.go
- x/tokenfactory/types/codec.go
- Adds the tokenfactory `AddCreatorsToDenomFeeWhitelistProposal` and dex `MsgRegisterContract` to their respective `codec.go`
> Add AddCreatorsToDenomFeeWhitelistProposal and MsgRegisterContract to Codecs

- go.mod
- go.sum
- loadtest/scripts/populate_genesis_accounts.py
Bump to include tendermint fixes for consensus changes merged previously
Also, include fixes here:
https://github.com/sei-protocol/sei-cosmos/pull/40 
Ran 20 iterations of the basic msg load test with 5 validators and didn't experience any issues
> Bump sei-cosmos and sei-tendermint for 2.0.0beta

- app/app.go
- utils/metrics/labels.go
- utils/metrics/metrics_util.go
- x/oracle/simulation/operations.go
Adding more metrics to keep monitor parallel TX, as it's difficult to debug, it would be useful to have more metrics for observability.
> Add more parallel TX metrics

- app/app.go
Upgrade handler for nitro store should be set at 1.2.2beta not 1.2.1beta. This caused the state sync issue described in https://discord.com/channels/973057323805311026/978080988422893619/1026619126363455620
Performed upgrade with 1.2.2beta locally and in internal testnet. Verified it work. 1.2.2beta binary has this fix already: https://github.com/sei-protocol/sei-chain/commit/92472c4f0b7482c97690e9803de434d0d55eb344
> Fix upgrade handler

- x/tokenfactory/README.md
- Adds a readme to describe the tokenfactory module + its associatd messages
> Add tokenfactory module readme

- app/ante.go
- app/antedecorators/gasless_test.go
- app/antedecorators/traced_test.go
- app/app.go
- go.mod
- go.sum
This uses the ante dep generator introduced in sei-cosmos and defines a wrapper for compatibility with existing antedecorators to have conservative dependency generation.
Needs testing
> [ante] Add ante dep generator default behavior

- aclmapping/bank/mappings.go
- aclmapping/dependency_generator.go
- aclmapping/utils/identifier_templates.go
Adding the dynamic access op mapping for testing purposes - this is most likely the end state, and adding this won't affect the actual processing logic but it does make changes easier as I don't need to branch off my personal branches 
make install works fine, and dynamic access ops are disabled by default
> Add msg send dynamic access ops

- x/dex/contract/execution.go
- x/dex/exchange/limit_order.go
- x/dex/exchange/limit_order_fuzz_test.go
- x/dex/exchange/limit_order_test.go
Update the order of the dex module processing to add limit orders to order book before matching. Order is now:
```
1) cancel trades
2) add all limit orders to the orderbook
3) fill market orders with the more liquid orderbook
4) fill matching buys and sell limit orders
```
- Updated `limit_order_test` and `exchange_test`
> Change Order Processing

- x/dex/contract/market_order.go
This PR fixes the market order by nominal type order status. This order type's executed quantity follows the real time settlement price and nominal requested, which may not always be the same as the order.quantity. So in the cancellation check, we only need to cancel it when zero quantity is executed.
TODO:
- add unit test for the FOKMARKETBYVALUE type after the dex/module_test.go is updated
> Fix market order by nominal type order status

- app/app.go
As discussed offline, this will be the new state for managing cache stores when running concurrent transactions:
- L0 - actual tree stored in FS (Initialized/Read from disk on start) 
- L1 - (DeliverState) - initialized at the start of FinalizeBlock, branches off L0 - This must be stable (i.e. shape has to be the same). - Ultimately committed to L0, through setting stateToCommit = DeliverState - Commit stage takes whatever is in stateToCommit and commits it 
- L2 - branched for ALL TXs from DeliverState - Allows dependent TXs to have an accurate serialized view of the state of the tree. - Merged back into L1 after all TXs are processed - Allows for rollbacks - Shape can be different across different validators since the dirty values are written to L1 in sorted order
- L3 - branched for …
> Branch another cache for all transactions

- loadtest/scripts/populate_genesis_accounts.py
Taking inspiration from work around Parallel Tx,
The create account and adding balance commands don't actually write to any of the data store (AVL trees) (the data folder is empty after genesis accounts are created), the data is persisted in the genesis file.
* https://github.com/sei-protocol/sei-cosmos/blob/63ac1b222e281be5ff25623ade4b93bd61517c1f/simapp/simd/cmd/genaccounts.go#L115-L169
To deal with the race condition for the genesis file, we just store it in memory and flush it to the file at the end when all accounts are complete. 
For 20 nodes, 5000 accounts went from 30mins+ to < ~30 seconds
Created load test cluster and ran 5 rounds of 2k txs per block 
For 20 nodes, 10k accounts went from 2 hours + to 76 seconds
> Optimize genesis account creation script

- x/tokenfactory/types/params.go
- Change the default tokenfactory denom creation fee param to 5 SEI
- Verified locally the 5SEI denom creation fee
> Change default tokenfactory denom creation fee to 5 sei

- loadtest/config.json
- loadtest/loadtest_client.go
- loadtest/main.go
- loadtest/sign.go
- loadtest/tx.go
- loadtest/types.go
- scripts/old_initialize_local.sh
- x/oracle/simulation/operations.go
Concurrency didn't seem to be the bottleneck. 
* Refactored the script 
* Made a cache for the signer/account seqno responses
* Instead of querying for each Seq No, we will just manage it locally
* For opening test account files, it will be the same, and read it from memory instead of from file each time 
Went from ~5 minutes -> 2 minutes
The first two rounds take the longest (active/inactive accounts fetching live info) then the remaining 3 rounds are super fast since it's just reading from the cache. 
Without this change:
> Refactor Loadtest script

- loadtest/scripts/populate_genesis_accounts.py
Cherry picking the commits directly
> git cherry-pick 75e7b2539aac7ac6143e631bee01f9310756402a
> Cherry pick account creation optimizations

- aclmapping/bank/mapping_test.go
- aclmapping/bank/mappings.go
- aclmapping/bank/mappings_test.go
- aclmapping/utils/identifier_templates.go
- aclmapping/utils/resource_type.go
- app/app.go
- go.mod
- go.sum
- store/testutils.go
- utils/metrics/metrics_util.go
- x/oracle/simulation/operations.go
* Updates the banksend acl mapping to use the prefix/storekeys as the identifiers rather than arbitrary ones
* Adds logic for handling failovers in the case when concurrent executions fail 
* Adds metric to count failed TX counts, we should add alerting on this in the future 
Will need to update the mapping for all the other modules
Unit tests
Deployed to load test cluster and was able to run bank sends e2e and verified that the height increases
Also manually forced failure scenario
> Validate Concurrent Messages + Update BankSend 

- aclmapping/wasm/mappings.go
- app/ante.go
- app/antedecorators/gas.go
- app/antedecorators/gas_test.go
- app/app.go
- go.mod
- go.sum
- wasmbinding/message_plugin.go
- wasmbinding/query_plugin.go
- wasmbinding/test/message_handler_test.go
- wasmbinding/test/query_test.go
- wasmbinding/utils.go
Integrate with the following sei-cosmos changes
- Allow fine-grained Wasm dependency specification
- Apply gas discount for Wasm contracts which specify non-* dependencies
- Pass "bad" contract addresses (the ones which specify wrong dependencies) to EndBlock context (which will be used by accesscontrol's EndBlock to reset dependencies for those contracts)
The gas change is tested with unit tests, the rest are tested with manual e2e test on a single node loadtest cluster
> integrate with sei-cosmos changes

- x/tokenfactory/keeper/admins_test.go
Branched this off Tony's branch as current master doesn't run properly right now 
This PR updates and fixes the tokenfactory unit test with the new logic regarding deferred burns and mints 
See this https://github.com/sei-protocol/sei-cosmos/pull/77
> Fix Bank Send Unit Tests 

- app/ante.go
- app/ante_test.go
- app/antedecorators/depdecorators/signers.go
- app/apptesting/test_suite.go
- go.mod
- go.sum
Updates the ante handler resource dependencies to match the logic we're using for validation
> Update Antehandler resource depedencies 

- loadtest/main.go
- x/oracle/simulation/operations.go
Turns out the previous branch didn't have much to merge into the cherry-pick branch 
https://github.com/sei-protocol/sei-chain/pull/360/commits/5434ab534b5816781ab833d327ab778420cebb29
Just did some cleanups
> Small Refactor for loadtest script

- wasmbinding/message_plugin.go
- wasmbinding/query_plugin.go
- wasmbinding/test/message_handler_test.go
- wasmbinding/test/query_test.go
**Will rebase to master once 2.0.0beta is cherrypicked to master**
Dependencies for each message is already set in context, so in wasmbindings we can read those dependencies from context instead of loading from keeper and reevaluate selectors. This also allows wasmbindings to not check dependencies for sudo calls from `dex` EndBlock, which would not set dependencies in its context.
Unit tests
Tested with local sei
> Use dependencies from context in wasmbindings

- app/app.go
- loadtest/config.json
- loadtest/loadtest_client.go
- loadtest/main.go
- loadtest/metrics.go
- loadtest/tx.go
- x/oracle/simulation/operations.go
It looks like some of the constant load testing changes might've gotten lost during the rebase, this PR adds it back and also adds support for exporting metrics. We need to have a thread to listen and return the metrics 
Will make another PR for the wrapper on this to run different configurations 
Note: one issue we'll have with running constant load tests is that the accounts eventually run out of tokens due to the gas fees, we'll need to think of a way to constantly supply these accounts with sei 
Had a constant load test running every 10 mins and see that the metrics are exported:
Example output at the end
```
Transactions not committed: 18
Response Code Mapping:
map[string]int{
"Error code=5 : insufficient funds": 1,
"ok":                                193,
}
```
> Add constant loadtesting back and export metrics for transactions 

- loadtest/config.json
- loadtest/main.go
- loadtest/metrics.go
- loadtest/scripts/run_tests.py
- loadtest/types.go
- x/oracle/simulation/operations.go
Adding a python script wrapper to be able to run load tests with different configurations, it uses the existing loadtest/config.json as the base and creates a copy of it with different 
Will make another PR to create service config files for these to run internally
Burst:
* Much larger tx per block but less cadence
Steady:
* Less TX per block but the higher cadence 
Steady Mode
Burst mode
> Add wrapper for load tests to run in different modes

- x/nitro/replay/replay.go
- x/nitro/replay/replay_test.go
The indexer sends account keys, recent blockhash, and instruction data with a `\x` prefix, which the replayer does not expect. So here we trim it off it such prefix is present before sending data to the replayer.
unit tests
> Nitro: trim \x prefix in data passed to replayer

- oracle/price-feeder/oracle/provider/gate_test.go
- oracle/price-feeder/oracle/provider/mock_server.go
- oracle/price-feeder/oracle/provider/mock_server_test.go
This adds a mock websocket server for mocking providers more robustly in unit testing.
Added unit tests for mock server, and tested the flaky gate provider unit tests with -count 10 to ensure it was no longer flaky
> add mock server provider

- oracle/price-feeder/oracle/client/client.go
This will alow the oracle sidecar to vote on the same block as the oracle tick (relevant for 1 block voting windows)
> [oracle] Fix sidecar broadcast timeout

- app/upgrades.go
- x/dex/cache/order.go
- x/dex/keeper/utils/order_book.go
- x/dex/types/match_result.go
- x/dex/types/match_result_test.go
Fix ordering of incoming orders so that they are stable
- Merged in 1.2.2beta-postfix
- Add unit tests
> Sorted order diffs cherry pick

- aclmapping/dex/mappings_test.go
- app/app.go
- testutil/keeper/dex.go
- wasmbinding/test/query_test.go
- x/dex/cache/cache.go
- x/dex/cache/cache_test.go
- x/dex/cache/order.go
- x/dex/cache/order_test.go
- x/dex/contract/abci.go
- x/dex/contract/execution.go
- x/dex/contract/whitelist.go
- x/dex/keeper/abci/end_block_place_orders_test.go
- x/dex/keeper/keeper.go
- x/dex/module.go
- x/dex/module_test.go
- x/dex/types/keys.go
Change the underlying data of order placement in MemState to be backed by KV store. Some details to note:
- `GetBlockOrders` always instantiates a new `BlockOrders` which is now just a wrapper over the underlying KV store
- `DeepCopy` of `BlockOrders` don't really do anything
- these order placement KV entries are deleted at the end of each block because they don't need to get written to disk during `Commit()`
unit tests
> Move order placement in MemState to store

- aclmapping/utils/identifier_templates.go
- app/ante.go
- app/antedecorators/gasless.go
- x/oracle/ante.go
This fixes the oracle antehandler dependencies and enables them for ante deps. 
Tested by running oracle transactions and verifying there were no errors in the comparator
> [ante] properly use the oracle ante deps

- app/ante.go
- app/antedecorators/gasless.go
- app/antedecorators/gasless_test.go
- go.mod
- go.sum
- oracle/price-feeder/oracle/client/client.go
- oracle/price-feeder/oracle/client/tx.go
- oracle/price-feeder/oracle/oracle.go
- scripts/old_initialize_local.sh
This fixes the regression with gasless TXs, once again allowing them to be executed without spending any gas. One change here is that gasless TXs NEED to specify zero gas in the tx to be processed as gasless. Otherwise, we will treat them as non-gasless in order to allow for tx prioritization via higher gas prices.
Verified gasless and gas enabled oracle txs
> [ante] Fix gasless ante and allow for specifying gas with gasless txs

- x/dex/cache/cache.go
- x/dex/cache/cache_test.go
- x/dex/cache/cancel.go
- x/dex/cache/cancel_test.go
- x/dex/contract/whitelist.go
- x/dex/keeper/msgserver/msg_server_cancel_orders.go
- x/dex/types/cancel.go
- x/dex/types/keys.go
Change the underlying data of order cancellation in MemState to be backed by KV store. 
- GetBlockCancels always instantiates a new wrapper over the underlying KV store
- Cancellations are stored by `MemCancel-{$contract_addr}-{$order_id}` in the KV store
unit tests
> Remove memstate for order cancellation

- x/dex/contract/abci.go
- x/dex/keeper/contract_test.go
- x/dex/keeper/utils/wasm.go
- x/dex/types/params.go
This PR does 3 things:
1. Fix a race condition in determining gas consumed by a sudo call. Previously it reads a shared gas meter before and after the `sudo` call, but since the reads and the sudo call are not atomic, race conditions across multiple threads using the same gas meter are possible and observed in loadtest.
2. Fix the rollback logic where the original context (hence the original store) instead of the cached store is returned if the processing fails.
3. We will not launch with sudo rent initially, so setting default sudo gas price to 0.
unit test
> Change default rent price to 0

- loadtest/config.json
- loadtest/tx.go
Seeing some `out of gas in location: WriteFlat; gasWanted: 200000, gasUsed: 201581: out of gas` in the latest client, looks like we need to bump up the gas for some of these transactions
Also updates contract addr based on recent changes, it might still be different between runs
> Increase gas limit for loadtest TXs

- aclmapping/bank/mappings_test.go
Improves coverage of aclbankmapping by adding tests for the bank module dependency generator
Coverage before: 63%
Coverage after: 100%
> [tests] Improve aclmapping bank generator coverage

- x/dex/cache/cache.go
- x/dex/cache/cache_test.go
- x/dex/contract/execution_test.go
- x/dex/keeper/contract_test.go
- x/dex/types/utils/enums_test.go
- x/dex/types/utils/unit_test.go
- x/dex/types/wasm/block_hooks_test.go
- x/dex/types/wasm/settlement_test.go
Bump unit test coverage rate for dex module core functionality. 
Note that
- the `abci` in both /contract and /keeper is covered by integration test (`module_test.go`) instead.
- some files are already fully covered but % shows not or even < 50%
- unit test is not included for /dex/client 
- Bump x/dex/types coverage rate
- Bump x/dex/keeper coverage rate
- Integrate coverage rate graph to github CI
Coverage report before:
```
ok  	github.com/sei-protocol/sei-chain/x/dex/cache	5.905s	coverage: 76.4% of statements
ok  	github.com/sei-protocol/sei-chain/x/dex/client/cli/query	64.795s	coverage: 23.1% of statements
?   	github.com/sei-protocol/sei-chain/x/dex/client/cli/tx	[no test files]
?   	github.com/sei-protocol/sei-chain/x/dex/client/utils	[no test files]
? …
```
> Add unit test for dex module

- x/dex/keeper/msgserver/msg_server_place_orders.go
- x/dex/keeper/msgserver/msg_server_place_orders_test.go
In order to prevent users from abusing order placement message's gasless feature, we need to validate order placement messages such that it's not possible to send an empty message.
unit test
> Validate order placement message

- go.mod
- go.sum
Using the same version of goleveldb as the sei-chain one, the newer one seems to be causing some issues with the store initialization. It looks like the state isn't being committed properly
```
failed to load state at height 9774; version does not exist (latest height: 9774): invalid request
Usage:
seid tx wasm store [wasm file] [flags]
```
Pretty sizable diff 
https://github.com/syndtr/goleveldb/compare/64ee5596c38af10edb6d93e1327b3ed1739747c7..2ae1ddf74ef7020251ff1ff0fe8daac21a157761
> Use older version of goleveldb to match sei-chain

- aclmapping/bank/mappings.go
- aclmapping/dex/mappings.go
- aclmapping/oracle/mappings.go
- aclmapping/staking/mappings.go
- aclmapping/tokenfactory/mappings.go
- aclmapping/utils/resource_type.go
- app/ante.go
- app/antedecorators/depdecorators/gas.go
- app/antedecorators/depdecorators/signers.go
- app/antedecorators/gasless.go
- go.mod
- go.sum
- x/oracle/ante.go
This properly adds the READ resource dependency on the wasm dependency mapping in the ante decorators for the gas meter setter. This is needed when we see wasm execute messages because the ante handler then reads from accesscontrol to get the dependencies to determine whether to allow gas discounts.
This also refactors identifier templates to use hex encoded strings
Tested with local sei to ensure that no more concurrent execution errors due to this access op being excluded
> [ante] Add ante deps for gas meter setter

- app/app.go
- app/app_test.go
- go.mod
- go.sum
- x/oracle/keeper/test_utils.go
- x/oracle/simulation/operations.go
We already reset the cacheKv (by not writing it) if the transactions fail, but we also need to reset the in-mem values to as those are different from the store 
Previously we didn't clear the state so the deferred sends from the previous call carried over 
Unit tests
> Refund gas fees if concurrent TX fails

- scripts/initialize_local.sh
Problem:
Initialize_local.sh is broken on Mac because sed command is not working on latest MacOS:
```
sed -i 's/mode = "full"/mode = "validator"/g' $HOME/.sei/config/config.toml
sed: 1: "/Users/yzang/.sei/confi ...": unterminated transform source string
```
Fix:
sed is little bit different on Mac compared to Linux GNU, we need to change the command to this
`sed -i'.bak' -e 's/something/else'g' filepath`
Tested on Mac and Ubuntu
> Fix local initialization script

- x/dex/keeper/abci/begin_block_new_block_test.go
- x/dex/keeper/utils/wasm.go
- x/oracle/simulation/operations.go
The `wasm` module would allow contracts to run forever if `ctx.GasMeter()` doesn't have a limit. So instead of using an infinite meter as the temporary meter (which was originally added to prevent race conditions between concurrent calls), we will use one that inherits the limit depending on whether it's called within BeginBlock or EndBlock (inferred from `ctx.GasMeter().Limit()`.
Tested on local chain with contract that has infinite loop in hooks
> Fix Begin/EndBlock stuck at infinite loop in contracts

- app/abci.go
- app/app.go
- go.mod
- go.sum
- x/oracle/abci.go
- x/oracle/module.go
This adds midblock functionality to sei-chain, and introduces logic to register midblock handlers with the module manager. As part of this, we are including an oracle Midblock function that no-ops for now (simply outputs an INFO log) that will later be refactored from EndBlock.
Tested with localsei
> [app] Add midblock functionality to sei-chain and oracle module

- app/ante.go
- app/antedecorators/gas_test.go
- app/app.go
- app/app_test.go
- app/test_helpers.go
- x/oracle/abci.go
- x/oracle/abci_test.go
- x/oracle/ante.go
- x/oracle/ante_test.go
Perform oracle consensus logic in Midblock instead of endblock
Refactored the tests to call midblock instead of endblock
> Oracle midblock

- .gitignore
- x/dex/keeper/contract.go
- x/dex/keeper/contract_test.go
- x/dex/keeper/utils/wasm.go
Set sudo gas limit based on the remaining rent of a contract instead of overall block gas limit so that the processing may time out sooner without affecting processing outcome. There would also be no race condition since there could be at most one sudo call happening at a time for the same contract.
unit test
local chain test
> Use contract rent to decide sudo call gas limit

- x/dex/cache/order.go
- x/dex/cache/order_test.go
- x/dex/contract/execution.go
- x/dex/exchange/market_order.go
- x/dex/exchange/market_order_fuzz_test.go
- x/dex/exchange/market_order_test.go
- x/dex/exchange/settlement.go
- x/dex/exchange/settlement_fuzz_test.go
In the previous testing we found the market order status is not updated correctly after the memstate refactor (always show ORDER_PLACED instead of ORDER_FULFILLED for fillled market orders). 
In this PR we update the order quantity and status in the memState (KVstore) for each settlement. 
To be noted that FOK market orders can only be settled when they're fulfilled so we don't need to check their quantity for fulfilled or not.
unit test
> Update market order status for each block

- aclmapping/dex/mappings_test.go
- aclmapping/staking/mappings_test.go
- app/params/config.go
- docker/localnode/scripts/step1_configure_init.sh
- docker/localnode/scripts/step2_genesis.sh
- go.mod
- go.sum
- scripts/initialize_local.sh
- scripts/initialize_local_test_node.sh
- scripts/old_initialize_local.sh
- x/dex/types/keys.go
- x/mint/client/rest/grpc_query_test.go
- x/mint/simulation/genesis_test.go
- x/oracle/simulation/operations.go
> Update default configs for consenssus TM and bump version for new defaults 

- aclmapping/wasm/mappings.go
- app/antedecorators/gas.go
- go.mod
- go.sum
This updates the calls to pass in the appropriate arguments. Also added a TODO not within scope for this change but a reminder to test some edge cases around wasm dependency generation failure and how it might affect other wasm dependency generation.
Existing tests
> [aclmapping] Update to use the refactored arguments for GetWasmDependencyMapping

- app/params/config.go
- x/oracle/simulation/operations.go
Sei-devnet-2 seeing a lot of validators miss blocks, turn off skip `UnsafeBypassCommitTimeoutOverride` and increase commit timeout to 100ms 
Don't need to change TM as this directly overrides whatever is from the config.toml file
local chain with timeout set to 5s, can see that each block height was very slow
> Update consensus configs to be less strict

- x/dex/contract/whitelist.go
- x/dex/contract/whitelist_test.go
This PR reverts the wasm prefix change as it conflicted with the current prefix used in the x/wasmd module (i.e. plain sdk.AccAddress). 
e2e test and unit test
> Revert wasm whitelist prefix

- x/dex/contract/abci.go
- x/dex/keeper/abci/end_block_place_orders.go
- x/dex/keeper/contract.go
- x/dex/keeper/utils/wasm.go
- Removed uninformational logs inside `SetContract`
- Added gas consumption log for each wasm call
- Added a log for initial rent balance when EndBlock starts
local sei
> [dex] improve dex EndBlock logs

- x/oracle/keeper/ballot.go
Seems like the oracle denoms should not be referencing Terra anymore 
Before:
After:
> update oracle denom names

- x/dex/migrations/v10_to_v11.go
- x/dex/migrations/v10_to_v11_test.go
- x/dex/module.go
This PR adds a migration handler for the dex prefixes change here: https://github.com/sei-protocol/sei-chain/pull/483. To be noted that here we will simply nuke the old data as this will only be needed on the devnet-2.
Other option is to replace the existing data like the snippet below, but given there are keys with suffix, either getting all pairs from contracts or assuming the contract address length is 62 in bytes is not as safe as nuking the old data on the devnet-2.
```
for _, prefixKey := range DexPrefixes {
store := prefix.NewStore(ctx.KVStore(dexkeeper.GetStoreKey()), []byte(prefixKey))
iterator := sdk.KVStorePrefixIterator(store, []byte{})
defer iterator.Close()
for ; iterator.Valid(); iterator.Next() {
key := iterator.Key()
if !bytes.HasPrefix(key, []byte(prefixKey)) { …
```
> Migrate old dex prefix data

- oracle/price-feeder/oracle/client/chain_height.go
- oracle/price-feeder/oracle/client/client.go
- oracle/price-feeder/oracle/oracle.go
**Problem:**
Currently, the oracle price feeder is not able to keep up with the block chain speed, it is only able to broadcast the transactions for every a few blocks. Ideally, we want the transaction to be broadcasted for every block, not to skippping any blocks.
**Solution:**
This PR propose the change to make the tick asynchronous and best effort. 
The previous behavior is that, we have a separate thread keep updating the height, and on block height changes, we will send a new tx broadcast. Whenever each time if there are some broadcast failures, we will retry the same tx for the next few blocks up till some max retry blocks  and will sleep for 1 second between each retry. This 1 second sleep takes too much time and doesn't make lot of sense any more. 
The new behavior will use a …
> [OraclePriceFeeder] Improve feeder performance by making tx broadcast async

- app/antedecorators/depdecorators/gas.go
- go.mod
- go.sum
- scripts/old_initialize_local.sh
This fixes incorrect dependency issues when we have a contract reference. Because the gas discount now expands the wasm dependencies of applicable contract references, we need to cover those as well as the original contract in the Accesscontrol READ access op. However, to prevent excessing iteration to identify the exact contracts, we can just declare a blanket `*` READ dependency since READs aren't blocking for other READs. This performance degrades a little if theres a tx registering a wasm dependency at the same time as executing a wasm TXs, but we expect dependency regsitration to be fairly infrequent in volume compared to the READs incurred by wasm contract execution.
Verified on localsei with wasm contract execution without invalid concurrent deps
> Fix contract reference deps for gas discount antehandler

- cmd/seid/cmd/root.go
We want to retain 3 days of block data so that if an outage occurs, the data is still available for investigation. 3 days gives us enough for the weekend.
> Increase pruning keep recent to keep 3 days of block data

- oracle/price-feeder/oracle/client/client.go
- oracle/price-feeder/oracle/client/tx.go
- oracle/price-feeder/oracle/oracle.go
When broadcastTx hit an error, we should not increment the sequence number, we should refresh the current sequence number and use that for the next transaction request.
> Fix oracle account sequence number increment logic

- oracle/.env
- oracle/oracle.js
- oracle/price-feeder/README.md
- oracle/price-feeder/oracle/client/client.go
- oracle/price-feeder/oracle/oracle.go
- oracle/price-feeder/oracle/provider/binance_test.go
- oracle/price-feeder/oracle/provider/huobi_test.go
- oracle/price-feeder/oracle/provider/kraken_test.go
- oracle/price-feeder/oracle/provider/mexc_test.go
- oracle/price-feeder/oracle/provider/okx_test.go
- oracle/price-feeder/oracle/util_test.go
- oracle/utils.js
- proto/oracle/query.proto
- vue/src/store/generated/sei-protocol/sei-chain/seiprotocol.seichain.oracle/module/types/oracle/query.d.ts
- vue/src/store/generated/sei-protocol/sei-chain/seiprotocol.seichain.oracle/module/types/oracle/query.ts
- x/dex/keeper/price.go
- x/oracle/client/cli/query.go
- x/oracle/client/cli/tx.go
- x/oracle/keeper/keeper_test.go
- x/oracle/simulation/operations.go
- x/oracle/spec/02_state.md
- x/oracle/spec/03_end_block.md
- x/oracle/spec/04_messages.md
- x/oracle/types/ballot.go
- x/oracle/types/query.pb.go
- x/oracle/types/vote_test.go
Did a mass replace for `Terra,terra,TERRA` and `Luna,luna,LUNA` for `Sei,sei,SEI` respectively 
Unit tests
> [cleanup] Remove Terra and Luna references

- app/antedecorators/gas.go
- app/antedecorators/gas_test.go
Modifies the gas denominator calculation to use the most conservative denominator for the TX so that users can't game the system by including a message with discount to get a discount on the whole Tx.
Updated unit test
> Gas discount calc

- app/params/config.go
- loadtest/contracts/deploy_ten_contracts.sh
based on sei-tendermint, max packet mesg should just be used in the channel when reading msgs and errors out if the packet size is too long so this should be fine to bump up 
https://github.com/sei-protocol/sei-tendermint/blob/46d0a598a7f5c67cbdefea37c8da18df2c25d184/internal/p2p/conn/connection_test.go#L503-L544
> Bump max packet msg payload

- app/antedecorators/gasless.go
- app/antedecorators/gasless_test.go
- x/oracle/types/errors.go
**Problem:**
oracle checkTx has a bunch of ante handlers and one of them is to make sure oracle transactions is gasless. However, this gasless check currently hide several exceptions underneath the boolean return result. The issue is when an exception happens within the check condition, it only returns a true/false, and doesn't surface the exception out. So when it moves on the next checkTx ante handler, we are seeing some weird, unrelated exception "insufficient fee"
**Fix:**
The fix here is in the gassless antehandler, instead of just return a true/false, we should also surface all the possible exceptions for real cause out, this would provide a more accurate explanation for why checkTx fails
> Oracle should not throw checkTx invalid insufficient fee errors

- x/dex/contract/abci.go
- x/dex/keeper/utils/wasm.go
Since we are seeing non-determinism with rent consumption, we need more visible log for rent gas consumed for future clusters.
n/a
> promote dex rent log level

- x/oracle/abci_test.go
- x/oracle/keeper/slash.go
- x/oracle/keeper/slash_test.go
This start calculating the valid vote rate using both misses and abstains, resulting in punishment for too much of either (or too much in combination) by a validator
Updated unit test
> [oracle] Punish abstaining along with bad participation

- loadtest/contracts/deploy_ten_contracts.sh
- x/dex/keeper/msgserver/msg_server_contract_deposit_rent.go
- x/dex/keeper/msgserver/msg_server_contract_deposit_rent_test.go
- x/dex/keeper/msgserver/msg_server_register_contract.go
- x/dex/keeper/msgserver/msg_server_register_contract_test.go
- x/dex/keeper/msgserver/validations.go
Wasm would multiply gas limit by a factor of 140000000, so we need to make sure the rent deposited (which would be used as the gas limit for dex wasm sudo calls) would not overflow after being multiplied.
unit tests
> Add validation for dex contract rent balance

- utils/logging/time.go
- utils/logging/time_test.go
- x/dex/contract/abci.go
- x/dex/contract/runner.go
- x/dex/keeper/utils/wasm.go
We want to get insight if some operations are hanging, but we don't want the logs to get noisy. This PR added a utility to only log if an operation takes an unexpectedly long time.
unit tests
> Add logging if operation takes too long

- x/dex/contract/runner.go
The runner would spawn one goroutine per contract, and each of those goroutines will send to a common unbuffered channel (which means the send operation is blocking). The main goroutine has a loop that keeps iterating until all contract runnables are confirmed finished, and the main goroutine is responsible for receiving from the common buffer. If the runnable for each contract is fast enough, the receiving operation of that common channel may happen fewer times than the number of goroutines trying to send to it. This would not block the main goroutine because only senders, which are spawned off goroutines, would have no counterpart receiver and block, and this would not cause contract runnable to malfunction because the send operation happens at the very end of the spawned off …
> Fix dex contract runner goroutine leak

- x/dex/client/cli/query/query_match_result.go
- Removed the `height` arg in the `get-match-result` cli command, but the cobra args number was not decremented
- Tested fully
> Remove unused cobra arg

- utils/logging/time.go
- utils/logging/time_test.go
Panics in a separate goroutine will not be recovered by main goroutine's `recover`, so we need to capture any panic and reraise
unit test (failing before the change, passed after the change)
> Handle panics correctly in logging util

- app/app.go
- app/upgrade_test.go
- x/oracle/simulation/operations.go
When there's a planned upgrade then process block will panic, this is an issue when there's a scheduled upgrade as it relies on the priv_val_state and WAL log, but in the optimsitic processing we don't flush before existing. Issue here is that the wal log is deep inside the tendermint state and inaccessible from sei-chain when it does Panic handling
Therefore the suggestion here is to not try to optimistic processing if there's a potential upgrade at this height
Before we would see:
`10:45PM ERR failed signing vote err="error signing vote: conflicting data" height=20 module=consensus round=0 vote={"block_id":{"hash":"","parts":{"hash":"","total":0}},"extension":null,"extension_signature":null,"height":"20","round":0,"signature":null,"timestamp":"2023-02-07T03:45:44.730316Z","type":1,"valid …
> Don't optimistic processing if theres a planned upgrade

- x/dex/contract/abci.go
- x/dex/keeper/utils/wasm.go
- x/dex/module_test.go
Dex EndBlock has a rollback mechanism such that any state change by a failed contract would be reverted. However this rollback should not include the rent charge applied to the failed contract; the rent should be always be charged. This PR adds an explicit operation for rent charge to be applied to the outer cache store.
unit test
> Charge rent even if contract failed execution in EndBlock

- oracle/price-feeder/oracle/jail.go
- oracle/price-feeder/oracle/oracle.go
This adds a check for whether the validator is jailed, and if so, doesn't allow submission of oracle votes, and instead logs error output
Verified with personal cluster
> [price-feeder] Add handling for jaield validator in oracle tick

- cmd/seid/cmd/debug.go
- cmd/seid/cmd/root.go
- go.mod
This adds the dump-iavl script as a debug command instead, using this, we can further extend logic to make certain iavl dumped data more human readable
Tested command locally
Example Output:
```
seid debug dump-iavl 90
db path: <REDACTED>
Processing Module: dex
Got version: 90
Printing all keys with hashed values (to detect diff)
Processing Module: wasm
Got version: 90
Printing all keys with hashed values (to detect diff)
Processing Module: accesscontrol
Got version: 0
Error reading data: no versions found while trying to load 90
Processing Module: oracle
Got version: 90
Printing all keys with hashed values (to detect diff)
Processing Module: epoch
Got version: 90
Printing all keys with hashed values (to detect diff)
Processing Module: mint
Got version: 90
Printing all keys with hashed …
```
> [cmd] Add dump-iavl to debug command

- x/dex/keeper/common.go
- x/dex/keeper/long_book.go
- x/dex/keeper/match_result.go
- x/dex/keeper/msgserver/msg_server_unregister_contract.go
- x/dex/keeper/msgserver/msg_server_unregister_contract_test.go
- x/dex/keeper/order_placement.go
- x/dex/keeper/pair.go
- x/dex/keeper/price.go
- x/dex/keeper/short_book.go
- x/dex/keeper/trigger_book.go
- x/dex/types/keys.go
Remove all states associated with a contract if it is unregistered
unit tests
> Delete contract-related states unpon unregister

- cmd/seid/cmd/debug.go
- cmd/seid/cmd/iavl_parser.go
This adds "shape" output and also adds the smart bank module parser
Example output for `bank.data`
```
007561746F6D | Supply | Denom: uatom
C344E9487BFBD5C4E03C9FB90D62A5DDE5E00B54D55C46E9F4A803AEA162B80C
0075736569 | Supply | Denom: usei
17FAD2629E760FEE1DB1DEA01C46C6C28ACB4D3F12EC0F434ACDBFF57A913001
007575736463 | Supply | Denom: uusdc
C344E9487BFBD5C4E03C9FB90D62A5DDE5E00B54D55C46E9F4A803AEA162B80C
017561746F6D7561746F6D | DenomMetadata | Denom: uatomuatom
60736A1A9F3CEC52945D12B4450EF05A0E1A9D87EEBE18F5D1E59B2C87ED2050
0214E42BCEAB96202850A7021B999A7FF77526D52F2375736569 | Balances | AddrLength: 20 | AddrBech32: sei1us4ua2ukyq59pfczrwve5llhw5nd2terrw9mwx | Denom: usei
DB3FCA8FAC2245BC9A63C94E8036E3C299A4177E828B79D5EB3FB1650A516FB5
0214E43D40D05524B57392F3BC610524DD8C8175A12C75736569 …
```
> [debug] Add smart parse to bank iavl

- cmd/seid/cmd/init.go
- cmd/seid/cmd/root.go
- go.mod
- go.sum
- scripts/old_initialize_local.sh
On init, save chain-id to client.toml (used to other commands to run seid commands to bypass requirement for --chain-id already) 
Then on startup, just read from client.toml's value if chainId isn't passed
Ran the new `./scripts/old_initialize_local.sh` 
Then restarted chain with `seid start`
Also validates
> make chain-id optional for seid start

- app/params/config.go
50ms is too fast if we want a truly decentralized chain as that will put a strong preference on validators staying close together and alienate any validators that are further
> [config] Update default UnsafeCommitTimeoutOverride to 100ms

- utils/logging/time.go
- utils/metrics/metrics_util.go
- x/dex/contract/runner.go
- x/dex/keeper/utils/wasm.go
- x/oracle/simulation/operations.go
Easier to tell if this is causing issues
> Add metrics around log not done util

- oracle/price-feeder/config.example.toml
- x/oracle/abci.go
This fixes map iteration to happen in sorted order for consistent event order, and also removes store READs within a store iterator
Existing tests
> [oracle] Sorts map keys prior to tallying for consistent ordering

- x/dex/cache/cache.go
- x/dex/cache/cache_test.go
- x/dex/keeper/common.go
- x/dex/keeper/price.go
- x/oracle/keeper/keeper.go
Performing store access before an iterator is closed may cause deadlocks (see https://github.com/sei-protocol/sei-chain/pull/567 for context).
This PR refactors existing logic to move store access that were previously within iterator's scope to be after iterator closure.
Note that there are still cases for this in oracle keeper, but all the methods there are only called in oracle's Mid/EndBlock, which are not parallelized in any way and thus not subject to the deadlock issue
unit tests + existing tests
> Defer store read/write from iterator loop

- loadtest/scripts/run_tests.py
> Bump up loadtest settings

- x/mint/types/minter.go
**Problem**:
Update inflation documentation In x/mint/types/minter.go:26 is stated that the intended default initial inflation rate should be 13%. However, in L21 the initial inflation rate is set to sdk.NewDec(0). If this is not intended behavior, this error may cause severe errors on the initial token distribution of the Sei token.
> Fix documentation for default inflation rate

- x/dex/client/cli/tx/tx_register_contract.go
**Problem**:
In x/dex/client/cli/tx/tx_register_contract.go, arguments [need hook] and [need order matching], only check against the string true. For example, if a user capitalizes the word, the flag is going to be set as false. Use strconv.ParseBool
Tested manually with cli after building sei chain
> [oak] Fix boolean parse for CLI

- x/dex/types/genesis.go
- x/dex/types/wasm/block_hooks.go
The alternative representation can be faster and more efficient in terms of memory.
This PR changes this representation of the hash map to a map[T]struct{}{} based on the results from https://itnext.io/set-in-go-map-bool-and-map-struct-performance-comparison-5315b4b107b.
Existing unit test covers it
> [oak] Use map[T]struct{}{} instead of map[T]bool for performance reason

- x/dex/keeper/msgserver/msg_server_register_pairs.go
- x/dex/keeper/msgserver/msg_server_update_price_tick_size.go
- x/dex/keeper/msgserver/msg_server_update_quantity_tick_size.go
**Problem**:
Validate and update are using two separate loops
**Action Items**: 
Combine validate & update in 1 loop
> [oak] Fix inefficient implementation of UpdateQuantityTickSize and UpdatePriceTickSize

- x/dex/keeper/msgserver/msg_server_place_orders.go
- x/dex/keeper/msgserver/msg_server_place_orders_test.go
- Removes redundant checks for nil fund amount during place order
- Adds unit tests for nil fund amount + negative fund amount during place order
- Added in unit tests
- Tested e2e with place order
> [oak] Remove redundant PlaceOrder checks for nil or negative transfer fund amount

- x/dex/client/cli/tx/tx_place_orders.go
- Removes redundant call to validate basic (ValidateBasic is already called in `GenerateOrBroadcastTxCLI`)
- Tested with place order from cli  and verified validate basic throws error
> Remove redundant validate basic in tx place order

- x/dex/exchange/cancel_order.go
- x/dex/exchange/cancel_order_test.go
- Checks position direction before cancellation and only iterate through relevant orders (longs or shorts)
- Adds a unit test for cancel orders
- Unit test added
- Tested e2e on local sei with cancellation
> [oak] Cancellation only iterate through relevant orders

- app/ante.go
- x/dex/ante.go
I investigated these TODos for the two audit tickets and determined that theyre no longer actionable / don't need to be addressed
> Removed dex audit todos, no longer relevant

- x/dex/keeper/query/grpc_query_get_historical_prices.go
It's already based on price and asset denom prefix - it's just missing the date in the prefix iterator, in that case it's essentially still iterating on all the prices. 
As of now the logic just gets all the prices and sorts
> Remove TODO for time filter

- oracle/price-feeder/oracle/provider/binance.go
- oracle/price-feeder/oracle/provider/coinbase.go
- oracle/price-feeder/oracle/provider/gate.go
- oracle/price-feeder/oracle/provider/huobi.go
- oracle/price-feeder/oracle/provider/kraken.go
- oracle/price-feeder/oracle/provider/mexc.go
- oracle/price-feeder/oracle/provider/okx.go
The response from `Dial` can sometimes be nil if there are specific errors. However, the defer assumes that there will never be a nil response, so attempting to get the `Body` from response causes a nil pointer panic. The true correct assumption is that body is non-nil IFF response is non-nil, so we want to have a check for non-nil response prior to `Close`ing the body.
> [price-feeder] gracefully handle nil response for new provider

- aclmapping/dex/mappings.go
- x/dex/keeper/abci/end_block_deposit.go
- x/dex/keeper/abci/end_block_place_orders_test.go
- x/dex/keeper/msgserver/msg_server_place_orders.go
- x/dex/keeper/msgserver/msg_server_place_orders_test.go
We originally placed coin sending logic in EndBlock to improve performance with batch operation (e.g. if an account placed a lot of micro deposits in the same currency, it will only be sent once in EndBlock). However this opened up an attack vector as described in https://linear.app/seilabs/issue/SEI-2678/[sei-chain]-msgplaceorders-should-hold-funds-in-escrow So we are moving the logic into transaction processing stage.
unit tests
> Send deposit funds in message server instead of EndBlock

- loadtest/scripts/metrics.py
Previously we were using events for which not all txs were reported (we neeed to emit events for custom modules).
This instead parses the txs and looks for matching words. This is a short term solution before we actually use some sort of cosmos-sdk / sei-chain python client
Ran and verified different txs showed up:
```
"Best block": {
"height": 17773,
"tps": 212.5984251968504,
"tx_mapping": {
"oracle": 53,
"bank": 1
},
"block_time_ms": 254
}
```
> Parse txs rather than events for loadtest metrics script

- x/dex/keeper/msgserver/msg_server_cancel_orders.go
- x/dex/keeper/msgserver/msg_server_contract_deposit_rent.go
- x/dex/keeper/msgserver/msg_server_place_orders.go
- x/dex/keeper/msgserver/msg_server_register_contract.go
- x/dex/keeper/msgserver/msg_server_register_pairs.go
- x/dex/keeper/msgserver/msg_server_unregister_contract.go
- x/dex/types/events.go
This adds events for many of the dex messages for potential downstream consumption
Tested locally, and verified on 20 node cluster that TPS isn't materially affected:
```
{
"Summary (excl. edge block)": {
"average_block_time": 1.3750865,
"average_throughput_per_block": 69.85714285714286,
"average_throughput_per_sec": 50.80199889762779,
"number_of_full_blocks": 7,
"full_blocks": [
3760,
3762,
3764,
3765,
3766,
3782,
3785
],
"total_txs_num": 489
},
"Detail (incl. edge blocks)": {
"blocks": [
3757,
3760,
3762,
3764,
3765,
3766,
3782,
3785,
3802
],
"txs_per_block": [
103,
95,
39,
108,
4,
111,
29,
103,
17
]
},
"Best block": {
"height": 3766,
"tps": 360.38961038961037,
"tx_mapping": {
"oracle": 17,
"dex": 94
},
"block_time_ms": 308
}
}
```
> [dex] Add events to msgs

- app/app.go
- app/upgrade_test.go
- app/utils.go
- scripts/initialize_local_test_node.sh
This fixes the deadlock issue of the optimistic processing (when it is disabled by an upgrade). When the optimistic processing is aborted: https://github.com/sei-protocol/sei-chain/blob/master/app/app.go#L959, the FinalizeBlocker is stuck by the op.Completion channel here https://github.com/sei-protocol/sei-chain/blob/master/app/app.go#L986
This PR replaces the `Abort` with a buffered boolean channel (size 1) `Completion` to signal whether an OP succeeds or gets aborted
- e2e test locally
- unit test
> Fix optimistic processing deadlock in upgrade issue

- app/app.go
- x/oracle/keeper/test_utils.go
- x/oracle/simulation/operations.go
This is so that it's easier to track what versions our nodes are running between loadtest clusters and our testnet/devnet clusters 
Ran locally
> Continously emit version metrics

- app/app.go
Optimistic processing may be skipped even for the first proposal of a height for reasons like upgrade. In those cases we want to mark completion immediately so that FinalizeBlocker won't be blocked.
The original fix was reverted due to concerns of regression on the non-determinism problem.
> Fix deadlock when optimistic processing is skipped for the 1st proposal

- x/nitro/keeper/msg_server.go
- x/nitro/keeper/msg_server_test.go
- x/nitro/types/errors.go
Unchecked error on SubmitFraudChallenge might cause adding an empty transaction. n x/nitro/keeper/msg_server.go:76 there is no check for an error on server.GetTransactionData. In case there was an error, it will mean that the transaction was not found but still added into the slice of transactions. This will be caught later on in the replay function. However, it is unnecessary to perform extra computations on input that is known to fail.
This PR adds a check for non-existent transaction data.
- unit test
> [Oak Audit] Add check for non-existent transaction

- app/app.go
- x/dex/contract/abci.go
- x/dex/contract/execution.go
- x/dex/contract/settlement.go
- x/dex/keeper/abci/end_block_cancel_orders.go
- x/dex/keeper/abci/end_block_deposit.go
- x/dex/keeper/abci/end_block_place_orders.go
- x/dex/types/wasm/order_placement.go
To reduce overheads we will skip sudo calls if the arguments are empty (e.g. no order in order placement call, no settlement in settlement call, etc.)
WIP
> Do not make Sudo call if parameters are empty

- go.mod
- go.sum
Thought we should bump up sei-cosmos and sei-tendermint and let some chains run with the new cosmos and tendermint changes if we're planning to do an upgrade soon
Had a chain run over night and no issues so far
> Bump sei-cosmos and sei-tednermint

- app/app.go
- go.mod
- go.sum
- utils/metrics/metrics_util.go
- x/dex/keeper/msgserver/msg_server_place_orders.go
- x/oracle/simulation/operations.go
Emit metrics for chain level performance. 
We need to store it in the baseapp as a counter we only scrape every 30seconds and our block times are < 1s most of the time, so if it's emitted per block it's not entirely accurate. (As seen in my testing, it was severally underreporting) 
The reason why we add the final counter at the end of the ProcessBlock is also due to the lifecycle of the contextMemcache object, and that's when we're sure that the counters are the ones being committed to the block. 
See this PR:
https://github.com/sei-protocol/sei-cosmos/pull/200
> Record and emit transaction, metrics and order counter 

- cmd/seid/cmd/genwasm.go
- cmd/seid/cmd/root.go
This adds `add-wasm-genesis-message` to seid so that wasm projects can be added during genesis. This already exists in our fork https://github.com/sei-protocol/sei-wasmd/blob/main/cmd/wasmd/genwasm.go#L10 but we cannot import the cmd directly b/c the package is main (so it is a program, not a lib). Recreates the file and adds it to seid
```
~/sei-chain | add-wasm-genesis *5 !1  seid add-wasm-genesis-message                                                                                                         ok | 01:39:42 PM
Wasm genesis subcommands
Usage:
seid add-wasm-genesis-message [flags]
seid add-wasm-genesis-message [command]
Available Commands:
execute              Execute a command on a wasm contract
instantiate-contract Instantiate a wasm contract
list-codes           Lists all …
```
> Add add-wasm-genesis-message to seid

- app/app.go
- app/app_test.go
Implementation for https://github.com/sei-protocol/sei-chain/pull/new/tony-chen-max-block-gas-check
We want honest validators (i.e. validators who do not use a maliciously modified binary) to reject block proposals whose transactions' GasWanted add up to something greater than max block gas. Since transactions in block proposals are sent as raw bytes, the only place to decode them would be on application-level during ProcessProposal. For context, ProcessProposal is called during `prevote` phase by validators, and if it returns a status of `REJECT`, validators will vote nil.
unit test
integration test in a loadtest cluster with a modified node to verify such proposal will indeed be rejected
> Reject proposal if max block gas is exceeded

- loadtest/config.json
- loadtest/loadtest_client.go
- loadtest/main.go
- loadtest/scripts/run_tests.py
- loadtest/sign.go
- loadtest/tx.go
- loadtest/types.go
- x/oracle/simulation/operations.go
Change to periodically collect rewards and also distribute them to test accounts 
Left is node-0, and right is node-1 we see that node-0 (where the LT client is running) has a lot less rewards as it was collected. For sei-internal we'll need to update distribution to collect rewards from the other validators 
Saw that the balance for the admin account was dropping 
Need to refactor the sei-infra script to test the reward collecting properly (too many acc seq issues caused by oracle not using its own acc)
> Periodically collect and distribute tokens to test accounts 

- oracle/price-feeder/oracle/oracle.go
Because tick failures are tolerated infrequently, it seems appropriate to downgrade the log message for failed ticks to a warning, which represents the incorrect behavior of that oracle's tick, but shouldn't affect future tick operation so it won't cause price feeder failure.
patched and tested on a node running price feeder
> [price-feeder] Change tick failure log to warning

- cmd/seid/cmd/root.go
- docker/localnode/config/app.toml
- docker/rpcnode/config/app.toml
- Removes `ibc/6D45A5CD1AADE4B527E459025AC1A5AEF41AE99091EF3069F3FEAACAFCECCD2` from min gas prices. This was originally added because we wanted usdc to be set as one of min gas prices on `seid init`. But this denom is specific to atlantic-1. 
- In future we could potentially add another denom to seid init if we want other default 
- Tested fully on local chain
> Remove ibc denom from min gas prices

- .github/workflows/go.yml
- .github/workflows/unit_tests.yml
- Makefile
Runtests.py runs it concurrently on a single machine, it works well locally but this is better when running against git workflows as we can split it up to reduce the time to build for PR jobs
The test coverage report also takes a while to run too so its good to split it out from the Go workflow
PR jobs
> Split Unit tests into multiple git PR jobs

- go.mod
- go.sum
Bumping cosmos and tendermint versions to include feature to auto restart if the node is behind a threshold 
```
#######################################################
#######################################################
[self-remediation]
p2p-no-peers-available-window-seconds = 60
statesync-no-peers-available-window-seconds = 60
blocks-behind-threshold = 1000
blocks-behind-check-interval = 30
restart-cooldown-seconds = 1800
```
This node is running with 200ms delay on all egress requests
The first break is when I restarted the node with the self-remediation turned on, and after that we see that there's no breaks between restarts and going into block sync mode and node is able to catch up
> [go.mod] bump for auto restart if behind

- x/dex/contract/abci.go
- x/dex/contract/abci_test.go
- x/dex/keeper/contract.go
- x/dex/keeper/contract_test.go
We want to automatically send rent consumed in each EndBlock to FeeCollector.
Specifically we will take an in-mem snapshot of eligible contracts' rent before EndBlock execution starts, and take another only if all contracts execute successfully. Then we will send the difference between the snapshots from `dex` module to `fee_collector` module (note that all rents are already stored in `dex` module's bank account: https://github.com/sei-protocol/sei-chain/blob/master/x/dex/keeper/msgserver/msg_server_contract_deposit_rent.go#L41)
unit tests
> Send consumed rent to fee collector

- go.mod
- go.sum
- Context: https://forum.cosmos.network/t/upcoming-cosmwasm-security-patch-codename-cherry/10474
- Adds Cosmwasm Security Patch for wasmvm according to https://github.com/CosmWasm/advisories/blob/main/CWAs/CWA-2023-002.md
- Updates wasmvm version from 1.0.0 to 1.0.1
- Spun up local chain and tested spot-lite contract, verified orders and rest go through
- Looking into details of security bug and verifying fixes
> Security CW Patch Cherry

- x/dex/contract/abci.go
- Fixes issue with `TransferRentFromDexToCollector` not updating amount deducted for rent in End Block
-  `GetRentsForContracts` to used cached context `cachedCtx`
- Spun up local chain, uploaded contract and verified amount sent from `TransferRentFromDexToCollector` 
```
11:36PM INF TransferRentFromDexToCollector - preRents map[sei14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9sh9m79m:100000000]
11:36PM INF TransferRentFromDexToCollector - postRents map[sei14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9sh9m79m:99984719]
11:36PM INF TransferRentFromDexToCollector - total 15281```
> Update GetRentsForContracts to use cachedCtx

- app/app.go
This change bumps the maximal uploadable wasm file size from 1024 * 1024 to 1280 * 1024.
- unit test
- e2e contract deployment test
> Bump max wasm file size to 2MB

- x/dex/keeper/utils/order_book.go
- x/dex/module_test.go
When no pair is registered for a contract, the old logic would not populate orderbook for the contract which would cause this check to fail https://github.com/sei-protocol/sei-chain/blob/master/x/dex/contract/abci.go#L225 and thus cause the contract to be considered a failed contract. This does not cause correctness issue because a no-pair contract should no-op anyway but does cause performance issue because each EndBlock now needs to be processed twice. This PR populates empty orderbook for such contract so that they will properly noop.
unit test which fails before the change and passes after the change
> Populate empty orderbook when no pair registered

- x/dex/keeper/contract.go
- x/dex/keeper/msgserver/msg_server_unregister_contract.go
- x/dex/module.go
- x/dex/module_test.go
If a contract fails execution in dex EndBlock, we want to automatically unregister it so that it doesn't slow down the chain for an indefinite amount of time
unit test
> Automatically unregister failed contracts in Dex EndBlock

- x/dex/contract/abci.go
- x/dex/module.go
Added following metrics:
**Latency:**
- get_all_contract_info
- end_blocker_atomic
- total_end_blocker_atomic
- handle_deposits
- order_matching_runnable
- handle_settlements
- handle_unfulfilled_market_orders
**Gauge:**
- num_of_registered_contracts
- num_of_valid_contracts
- num_of_zero_balance_contracts (rent =0)
**Counter:**
- total_failed_contracts
- total_unregistered_contracts
Tested in rpc nodes
> Add more metrics for dex module

- .github/workflows/go.yml
Context: https://github.com/actions/first-interaction/issues/10#issuecomment-670968624
This should fix non-contributors not being able to run PR jobs 
Can't test on my side but I can update the branch for one of the external PRs to test after merging
> Change go job to Pull request target 

- proto/dex/contract.proto
- utils/datastructures/set.go
- x/dex/keeper/contract.go
- x/dex/keeper/contract_test.go
- x/dex/module.go
When a contract X is unregistered, we should update other registered contracts' dependency list to remove that unregistered contracts, which includes:
- for contracts that depend on X, remove X from their list
- for contracts that X depend on, decrement `NumIncomingDependencies`
- for contracts that depend on the same contract which X depend on (i.e. sibling contracts), update the immediate sibling pointer so that X's immediate elder and younger sibling become immediate siblings with each other
If dependencies are not updated properly, `dex` EndBlock may hang due to dependency requirements that's never fulfillable.
unit test & local sei
> Clear unregistered contracts from other contracts dependency list

- x/dex/ante.go
- x/dex/ante_test.go
- x/dex/exchange/market_order.go
- Allows Market Price of Zero
- Fixes issue with Orders where zero price (which is allowed) was giving error because it previously wasn't a multiple of tick size
- Tested e2e local chain placing orders + market orders with price 0
> Fix Zero Price Order

- x/dex/types/codec.go
Similar to https://github.com/cosmos/cosmos-sdk/blob/v0.45.4/x/staking/types/codec.go#L51-L55, registers legacy amino
- Unit tests
- Ran chain locally
> [Oak Audit] Register legacy amino for x/dex

- x/dex/contract/abci.go
- x/dex/keeper/abci/end_block_deposit.go
- x/dex/module_test.go
- x/oracle/simulation/operations.go
Optimize the sudo deposit calls and the message building 
Ran in the same loadtest cluster for the other contract optimizations
> Parallelize Sudo Deposit 

- cmd/seid/cmd/root.go
This increases the gas used by wasm vm to better represent compute time used
Tested on loadtest clusters, verified that contract upload is not affected as well
> modify wasm gas multiplier to make wasm executes more in line with compute cost

- app/app.go
- x/dex/cache/cache.go
- x/oracle/simulation/operations.go
We need to clear the dex memcache
> Clear dex memstate cache

- app/app.go
- app/test_helpers.go
Refund any used gas during concurrent processing before sequential fallback processing
> Reset block gas meter if concurrent processing fails

- app/app.go
This disables tx execution concurrency on non prioritized (non-oracle, dexregister msgs) txs
Will test on a loadtest cluster
> Disable tx concurrency

- scripts/initialize_local_chain.sh
- x/oracle/keeper/keeper.go
- x/oracle/keeper/keeper_test.go
- x/oracle/keeper/querier.go
- x/oracle/utils/assets.go
This updates oracle to remove the base denom since all assets are priced relative to USD. This will also allow for pricing USDC relative to USD.
unit tests and local sei testing
> remove base denom from oracle

- app/ante.go
- app/ante_test.go
- app/app.go
- go.mod
- go.sum
Sets a global minimum fee that takes inspiration from cosmos hub: https://github.com/cosmos/gaia/blob/d42583423861bbb7b60327e11802b3e79ac6e219/x/globalfee/ante/fee_utils.go#L23C1-L52
It takes the max of (global minimum gas prices, validator minimum gas prices) and uses that to run checkTx
Integrates it with this PR: https://github.com/sei-protocol/sei-cosmos/pull/252
> Add global minimum fees

- app/app.go
This re-enables tx concurrency
Tested along with the fixes for feegrant to verify that we no longer had concurrency violations for that execution path.
> Re enable tx concurrency for non-oracle/prio txs

- x/oracle/keeper/querier_test.go
- x/oracle/utils/period.go
Derive this value based on oracle slash window of 108000
> [Certik Audit] Set default blocks per min to a more realistic value

- app/export.go
Original way of parsing validator key is incorrect.
Verified `seid export --for-zero-height --chain-id=sei-chain` now works
> [Certik Audit] Fix validator address parsing for genesis export

- .github/workflows/unit-test-coverage.yml
This workflow requires a github.event.number that likely doesn't exist when merging a PR, which causes it to fail with:
`  Error: fatal: invalid refspec '+refs/pull//merge:refs/remotes/pull//merge'`
This only needs to be run on PR updates anyways.
Will validate once merged
> Remove unit-test-coverage on master merge

- x/oracle/ante.go
- x/oracle/ante_test.go
- x/oracle/keeper/keeper_test.go
Improved oracle unit test coverage for keeper and other material logic
unit testing and coverage report
```
github.com/sei-protocol/sei-chain/x/oracle/abci.go:16:				MidBlocker					100.0%
github.com/sei-protocol/sei-chain/x/oracle/abci.go:157:				EndBlocker					100.0%
github.com/sei-protocol/sei-chain/x/oracle/ante.go:26:				NewSpammingPreventionDecorator			100.0%
github.com/sei-protocol/sei-chain/x/oracle/ante.go:35:				AnteHandle					100.0%
github.com/sei-protocol/sei-chain/x/oracle/ante.go:52:				AnteDeps					85.7%
github.com/sei-protocol/sei-chain/x/oracle/ante.go:89:				CheckOracleSpamming				85.0%
github.com/sei-protocol/sei-chain/x/oracle/ante.go:127:				NewOracleVoteAloneDecorator			100.0%
github.com/sei-protocol/sei-chain/x/oracle/ante.go:132:				AnteHandle					100.0% …
```
> Improve oracle unit test coverage

- app/params/config.go
Tunes consensus configs so that we don't have high p95 block times on a slow validator:
- UnsafeProposeTimeoutOverride: let's validators vote "nil" if a proposal doesn't come in in time: 1s -> 300ms, shoudl be enough time for 1 network rtt
- UnsafeProposeTimeoutDeltaOverride: How much time to increase the propose timeout every time we enter a new round
- UnsafeVoteTimeoutDelta: How much time to incrase the vote timeout every time we enter a new round
Launched a cluster and slowed a node down.
Before:
After:
> Decrease consensus timeout backoff values

- aclmapping/dex/mappings.go
- aclmapping/tokenfactory/mappings.go
- app/app.go
- x/dex/keeper/msgserver/msg_server_place_orders.go
- x/tokenfactory/keeper/bankactions.go
This removes deferred send usages from tokenfactory and dex. This increases overall safety because now only feecollector uses deferred balances.
tested on localsei
> remove deferred send usages from dex and tk

- integration_test/dex_module/place_order_test.yaml
- integration_test/tokenfactory_module/create_tokenfactory_test.yaml
- x/tokenfactory/keeper/createdenom.go
- x/tokenfactory/keeper/createdenom_test.go
- x/tokenfactory/keeper/keeper_test.go
- x/tokenfactory/keeper/migrations.go
- x/tokenfactory/keeper/migrations_test.go
- x/tokenfactory/module.go
- x/tokenfactory/types/expected_keepers.go
x/bank requires that display, name and symbol for all denoms are valid. However, when exporting genesis we found that this is not the case.
This is an initial PoC. We need to backport (migrate all existing denoms) if this looks good.
- Unit test 
- Created denom locally, ran validate-genesis, ensure it passes
- Created denom on 3.0.3, ran upgrade, ensure new genesis is valid
```
"denom_metadata": [
{
"base": "factory/sei1099gwedy7ds2ysc8xjegfl9720qmczgfwdzdk7/test",
"denom_units": [
{
"aliases": [],
"denom": "factory/sei1099gwedy7ds2ysc8xjegfl9720qmczgfwdzdk7/test",
"exponent": 0
}
],
"description": "",
"display": "factory/sei1099gwedy7ds2ysc8xjegfl9720qmczgfwdzdk7/test",
"name": "factory/sei1099gwedy7ds2ysc8xjegfl9720qmczgfwdzdk7/test",
"symbol": …
```
> Add display,name,symbol to tokenfactory denom creation

- aclmapping/tokenfactory/mappings_test.go
- aclmapping/utils/resource_type.go
- app/ante_test.go
- app/antedecorators/accesscontrol_wasm_dependency.go
- app/antedecorators/depdecorators/gas.go
- app/antedecorators/depdecorators/signers.go
- app/antedecorators/gasless.go
- app/antedecorators/gasless_test.go
- app/app.go
- app/app_test.go
- go.mod
- go.sum
- tests/dex_test.go
- x/dex/ante.go
- x/oracle/ante.go
- x/oracle/ante_test.go
- x/tokenfactory/keeper/admins_test.go
- x/tokenfactory/keeper/bankactions_test.go
This PR does the following:
- refactors ante dependency decorators to follow the new pattern of passing txIndex through
- Adds the new deferredcache resource type to the tree
- removes the ContextCache (because of incoming deprecation) setup performed in BuildDependenciesAndRunTxs
- updates instantiation of seid app to use the new BankKeeper with DeferredCache memstore created
local sei testing (and needs more tests added via test harness)
> Refactor deferred usages

- utils/panic.go
- x/epoch/module.go
- x/epoch/types/hooks.go
- x/epoch/types/hooks_test.go
Gracefully recover any x/epoch hook, both before and after, and log the recovered error.
ref: sei-4591
> fix: handle panics in epoch hooks

- app/antedecorators/gasless.go
- app/antedecorators/gasless_test.go
- tests/dex_test.go
We expect certain gasless transactions (e.g. dex order placements) to carry fees even if the amount is not subject to the validator's minimum fee check, but we have not been collecting those fees because DeductFeeChecker (i.e. the wrapped decorators in the gasless decorator) are always skipped for gasless transactions. This not only causes less validator income but also exposes ddos attack vector specifically in the dex module. This PR changes it so that fees are always deducted for transactions in DeliverTx mode.
unit tests
> Deduct fees from gasless tx

- go.mod
- go.sum
- x/dex/migrations/v16_to_v17.go
- x/dex/migrations/v16_to_v17_test.go
See more description here https://github.com/sei-protocol/sei-chain/pull/939
unit tests
> Use ImmutableAppend for migration 16 to 17

- scripts/initialize_local_chain.sh
Use Python for calculating the date differences so that it's more OS agnostic, right now it only works on Mac (Darwin) 
Ran chain locally and the commands on ubuntu ec2 instances
> Make init local chain os agnostic

- oracle/price-feeder/config.example.toml
- oracle/price-feeder/config/config.go
- oracle/price-feeder/oracle/provider/crypto.go
- oracle/price-feeder/oracle/provider/crypto_test.go
- oracle/price-feeder/oracle/provider/provider.go
- oracle/price-feeder/oracle/provider/ws_controller.go
- oracle/price-feeder/oracle/provider/ws_controller_test.go
* Implement crypto.com provider
* Import and use `WebsocketController` which is used by the `CryptoProvider`
Note, this was lifted from Umee's version of the price-feeder @ v3.x. When we have sufficient capacity, we may want to explore the generalized improvements both the Kujira and Umee versions have made, such as generalizing the provider implementation.
> feat: crypto.com provider

- loadtest/config.json
We should not create tokenfactory msgs by default since it could lead to unnecessary state bloat
> Do not create TKF in loadtest by default

- wasmbinding/bindings/msg.go
- wasmbinding/encoder.go
- x/tokenfactory/client/cli/tx.go
- x/tokenfactory/client/cli/tx_test.go
- x/tokenfactory/client/wasm/encoder.go
- x/tokenfactory/types/errors.go
The CLI allow passing in a JSON file, and the wasmbinding takes in a json blob with the same format
local sei
> Add CLI/wasmbinding to set tokenfactory metadata

- x/tokenfactory/client/cli/tx.go
- Registers the Set Metadata Command To Tokenfactory
- Was not showing up previously
- Tested e2e
```
seid q bank denom-metadata --denom factory/sei1y098n8yfpyt8hzhhckncf3d6p70j7mna33g6kx/randomDenom
metadata:
base: factory/sei1y098n8yfpyt8hzhhckncf3d6p70j7mna33g6kx/randomDenom
denom_units:
- aliases:
- randomDenom
denom: factory/sei1y098n8yfpyt8hzhhckncf3d6p70j7mna33g6kx/randomDenom
exponent: 0
- aliases:
- aliasRandomDenom
denom: moreRandomDenom
exponent: 6
description: Update token metadata
display: factory/sei1y098n8yfpyt8hzhhckncf3d6p70j7mna33g6kx/randomDenom
name: randomDenom
symbol: RAND```
```cat set_metadata.json 
{
"description": "Update token metadata",
"denom_units": [
{
"denom": "factory/sei1y098n8yfpyt8hzhhckncf3d6p70j7mna33g6kx/randomDenom",
"exponent": 0,
"aliases": …
```
> Fix Set Metadata Command

- app/app.go
- app/app_test.go
This reorders the TXResults such that the true order of tx indices is preserves as opposed to ordering parititoned and then other TXs which was occurring previously
unit tests + will test patch on chain
> Reorder tx results into absolute order

- CHANGELOG.md
- app/upgrades.go
- go.mod
- go.sum
Changes for 3.0.9 upgrade:
1. Bump tendermint version to include the patch
2. Fix the version naming convention
3. Add upgrade handler for v3.0.9
> Cut v3.0.9 for version release

- scripts/initialize_local_chain.sh
- Mac uses a BSD variety of `sed` whereas Linux is on GNU version
- On Mac, `sed` requires `sed -i ''` whereas on linux it requires `sed -i` (no `''`)
- This change checks `$OSTYPE` before running `sed` to replace config entries for mode & indexer
- Local testing of initializing the local chain
> Fix init chain script for Linux

- oracle/price-feeder/oracle/client/client.go
- oracle/price-feeder/oracle/oracle.go
- oracle/price-feeder/oracle/oracle_test.go
- Filters all prices to only whitelisted entries so that configuring extra prices do not cause a penalty
- This allows us to safely add new oracle prices to the network (add first, then adjust requirement)
- Added a test for tick(), which relies on OracleClient.  
- Instead of refactoring all of OracleClient to be an interface, I used a mock function.  I prefer interfaces, but this was a safer blast radius on the codebase.
- Unit Tests for Filtering logic
- Unit Tests for tick() logic
- local price-feeder verification
There is now a new DEBUG line including pre-filtered values (see uextra)
```
DBG pre-filtered prices exchange_rates=27136.481901959936667054ubtc,1699.246734346635898342ueth,0.999870004013299023uextra,1.000000000000000000uusdc module=oracle
```
This is followed by the INFO …
> Filter oracle price broadcast by whitelist values

- oracle/price-feeder/config.example.toml
- The example config toml will be an example for pacific-1 
- It now includes ATOM, SEI, and OSMO
- Only two providers work for each of these.  
- At this time a 3rd provider (okx) is added to satisfy the 3-provider requirement.
- Tested configuration in local mode (output from log means these providers are loading)
```json
{
"ATOM": [
"coinbase", "kraken"
],
"BTC": [
"coinbase", "kraken", "crypto", "huobi"
],
"ETH": [
"coinbase", "kraken", "crypto", "huobi"
],
"OSMO": [
"gate", "huobi"
],
"SEI": [
"coinbase", "kraken"
],
"USDC": [
"kraken", "huobi"
],
"USDT": [
"coinbase", "kraken", "crypto"
]
}
DBG pre-filtered prices exchange_rates=6.864999999999998121uatom,25697.497452222193405273ubtc,1632.085678885738215518ueth,0.356640025154169049uosmo,0.125800000000034358usei,0.999875812058908680uus …
```
> Add price feeds to the example config toml

- scripts/initialize_local_chain.sh
The previous value for genesis tokens and voting power caused issues when paired with sei-cosmos-exporter, since querying the `general` metrics (which returns staking pool balances) would fail due to int64 overflow. This isn't an issue on chain because the chain uses bigInt for accounting, and ~~I'll need to make an appropriate fix in sei-cosmos exporter, but for the meantime, this will make sure that sei-cosmos-exporter doesn't break when used against local chain~~ never mind, float64 is the limit for a prometheus gauge, so we want the values to remain within int64 bounds
verified that sei-cosmos-exporter works properly on local chain
> reduce genesis values to not overflow int64

- oracle/price-feeder/oracle/oracle.go
- oracle/price-feeder/oracle/oracle_test.go
- x/oracle/types/denom.go
- x/oracle/types/denom_test.go
**Background**
- The `SetPrices()` method enforces that all price feeds are present rather than only whitelisted entries
- If a non-whitelisted entry fails, it means that it would abstain the vote, which is undesirable
**Change Summary**
- This change only requires whitelisted entries, and all others will populate if successful
- It also removes a length check to allow for more entries (it already checks that every required value is present)
- Unit Tests (mocking "bad providers")
- The existing tests now confirm a non-whitelisted entry continues to be set
- A new test confirms a failing non-whitelisted entry doesn't prevent the setting of prices
- Local Chain Testing
> Only whitelisted price feeds should be required

- go.mod
- go.sum
- Bumps version of sei-ibc-go from v3.1.0 to v3.2.0 https://github.com/sei-protocol/sei-ibc-go/releases/tag/v3.2.0
- Fully tested e2e on a chain all changes related to ibc
> Bump Sei-ibc-go version

- oracle/price-feeder/config/config.go
- oracle/price-feeder/oracle/oracle.go
- oracle/price-feeder/oracle/oracle_test.go
- oracle/price-feeder/oracle/provider/binance.go
- oracle/price-feeder/oracle/provider/binance_test.go
- oracle/price-feeder/oracle/provider/coinbase.go
- oracle/price-feeder/oracle/provider/coinbase_test.go
- oracle/price-feeder/oracle/provider/crypto.go
- oracle/price-feeder/oracle/provider/crypto_test.go
- oracle/price-feeder/oracle/provider/gate.go
- oracle/price-feeder/oracle/provider/gate_test.go
- oracle/price-feeder/oracle/provider/huobi.go
- oracle/price-feeder/oracle/provider/huobi_test.go
- oracle/price-feeder/oracle/provider/kraken.go
- oracle/price-feeder/oracle/provider/kraken_test.go
- oracle/price-feeder/oracle/provider/mexc.go
- oracle/price-feeder/oracle/provider/mexc_test.go
- oracle/price-feeder/oracle/provider/okx.go
- oracle/price-feeder/oracle/provider/okx_test.go
- scripts/initialize_local_chain.sh
This does the following:
- adds some additional debug and warning logging
- Refactors the gate provider to use the new API that allows for subscribing to more than one currency pair
- removes the all or nothing behavior that prevents providers from returning prices unless ALL of their configured asset prices are available
Tested with oracle price feeder with local chain, need to test longer running on a loadtest cluster with steven's monitoring additions
> Improve pf providers

- CHANGELOG.md
- app/upgrades.go
Changes for 3.1.0 upgrade:
- Add upgrade handler for v3.1.0
- sei-ibc-go version has already been bumped
> Cut v3.1.0 for version release

- oracle/price-feeder/oracle/oracle.go
- oracle/price-feeder/oracle/oracle_test.go
- In US regions, binance clients never initialize
- Initializing takes ~500ms, which impacts price broadcasting cadence
- This quickfix avoids re-initializing binance repeatedly if it fails at startup
- unit test
- local testing
> Avoid re-initializing providers that fail initially

- oracle/price-feeder/oracle/util.go
- oracle/price-feeder/oracle/util_test.go
- TVWAP calculation decreases a weight by time passed
- Before this change, it would return a divide-by-zero error
- Now it correctly starts the value as 1 if it's the same second
- This was occurring every few hours in arctic-1
- unit testing
- local chain testing (though we need to watch it over time in envs)
> Tolerate candles within same second as now

- oracle/price-feeder/oracle/oracle.go
- oracle/price-feeder/oracle/oracle_test.go
- This was processing the set of ticker prices rather than candle prices
- This caused a lack of an error metric if ticker was fine, and candle was missing
- Unit test to capture this scenario (good tickers, bad candle)
> Fix metric for candle error

- oracle/price-feeder/oracle/oracle.go
- oracle/price-feeder/oracle/oracle_test.go
- If the broadcast request returns as nil response, the log statement would panic
- This makes the log statement tolerant to a nil response, causing a restart
- Reproduced and added unit test
> Add tolerance to nil response for error log

- .github/ISSUE_TEMPLATE/bug_report.md
bug reports created using templates will have linear tag applied
> add linear tag to bug_report.md

- go.mod
- go.sum
- x/evm/keeper/address.go
- x/evm/keeper/address_test.go
- x/evm/keeper/keeper.go
- x/evm/state/balance.go
- x/evm/state/balance_test.go
- x/evm/state/state.go
- x/evm/state/state_test.go
- x/evm/state/statedb.go
- x/evm/types/keys.go
Implement functions to initialize/get/set/destruct state in EVM state interface. Specifically,
- Get/SetState sets a KV entry under a specified account prefix
- GetCommittedState is similar to GetState but reads from the state as if at the beginning of the transaction (i.e. skip the cache layer and go directly to the parent. See corresponding sei-cosmos extension here: https://github.com/sei-protocol/sei-cosmos/pull/319)
- Get/SetTransientState writes to a in-memory map under a specified account prefix, and is not committed to KV store.
- SelfDestruct would burn account's balance and clear its state, but leave transient state untouched (as per go-ethereum behavior)
- SelfDestruct6780 is equivalent to SelfDestruct iff the account is newly created in the same block
- CreateAccount marks an …
> Add state-related function implementations in EVM state interface

- evmrpc/block.go
- evmrpc/block_test.go
Add endpoint to get block by number (height). Note that the endpoint takes in several special "number" as input:
- earliest -> corresponding to genesis height
- safe/pending/finalized/latest -> all corresponding to latest height since Sei has instant finality
unit tests
> [EVM] add getBlockByNumber endpoint

- evmrpc/block.go
- evmrpc/block_test.go
Add `eth_getBlockTransactionCountByHash` and `eth_getBlockTransactionCountByNumber`. Note that this includes all transactions not just EVM transactions, which is intended since these endpoints are most commonly used to determine congestion level of the chain, which both EVM and non-EVM transactions contribute to.
unit tests
> [EVM] add endpoints to get block transaction count

- .github/workflows/codeql.yml
- .github/workflows/compatiblity_check.yml
- .github/workflows/fuzz.yml
- .github/workflows/golangci.yml
- .github/workflows/integration-test.yml
- .github/workflows/unit_tests.yml
- Dockerfile
- evmrpc/block.go
- evmrpc/info.go
- evmrpc/info_test.go
- evmrpc/server.go
- evmrpc/testutils.go
- evmrpc/tx.go
- evmrpc/utils.go
- go.mod
- x/evm/keeper/testutils.go
Add `feeHistory` endpoints that returns base fee and rewards percentile (weighted by gas used) for the requested block range. More details on the percentile calculation can be found in comments.
unit tests
> [EVM] add endpoint to return fee history

- evmrpc/subscribe.go
- evmrpc/subscribe_test.go
- evmrpc/testutils.go
Add a helper class `SubscriptionManager` to facilitate subscription to tendermint events (docs: https://docs.tendermint.com/v0.34/rpc/#/Websocket/subscribe). Filters can be created via the new `QueryBuilder` struct and passed to `SubscriptionManager`.
Note that we make use of `Subscribe` method which is marked as deprecated, but not really deprecated in the new tendermint version.
unit tests
> [EVM] add subscription utility

- evmrpc/send.go
- evmrpc/send_test.go
- evmrpc/server.go
- evmrpc/testutils.go
- loadtest/loadtest_client.go
- x/dex/cache/cancel.go
- x/dex/cache/deposit.go
- x/dex/cache/order.go
- x/dex/keeper/utils/wasm.go
- x/evm/types/ethtx/txdata.go
- x/tokenfactory/keeper/migrations.go
- x/tokenfactory/keeper/migrations_test.go
- x/tokenfactory/types/events.go
Implement `SendRawTransaction`. Note that for now Sei nodes will not custody users' private keys so it will not offer endpoints that provide signing capability (e.g. SendTransaction, Sign, SignTransaction)
unit tests
> [EVM] add endpoint to send transaction

- .github/workflows/compatiblity_check.yml
- .golangci.yml
- evmrpc/server.go
- evmrpc/simulate.go
- evmrpc/simulate_test.go
- evmrpc/state_test.go
- evmrpc/testutils.go
- go.mod
- go.sum
- x/evm/keeper/keeper.go
- x/evm/keeper/keeper_test.go
- x/evm/keeper/msg_server.go
- x/evm/state/balance.go
- x/evm/state/balance_test.go
- x/evm/state/log.go
- x/evm/state/log_test.go
- x/evm/state/state.go
- x/evm/state/state_test.go
- x/evm/state/statedb.go
Implement the following simulation endpoints:
`createAccessList`
`estimateGas`
The endpoint makes use of an implementation of interface `Backend` that drives the core simulation logic in go-ethereum. It only implemented the functions that may be called by `createAccessList` or `estimateGas`, and simplified logics such as `SuggestTipCap` to be config-based.
It also involves changes in our go-ethereum fork to expose private functions/types so that we don't have to copy them here.
unit tests
> [EVM] get simulation endpoints

- evmrpc/state.go
- evmrpc/state_test.go
- evmrpc/testutils.go
- x/evm/keeper/testutils.go
Implement `eth_getProof` endpoint. The response differs from normal Ethereum's because:
1. on Sei there is no per-account storage root
2. Sei stores data with a regular Merkle tree instead of a Patricia tree, so the proof format is different
unit tests
> [EVM] add getProof endpoint

- x/evm/ante/gas.go
- x/evm/ante/gas_test.go
- x/evm/keeper/msg_server.go
There were two issues with gas return value previously:
1. Mempool uses the `gasWanted` field in the return value of `CheckTx` to determine priority. This field is populated based on the gas meter limit that's read from the context returned by ante handlers. So we must set gas meter limit properly when evm ante handlers return.
2. `DeliverTx` will read the `gasUsed` field from the gas meter returned by the message handler and add it to block gas meter. So even though we let EVM handle gas checks internally, we still need to add the consumed gas to the gas meter before the message handler returns.
One thing to note is that, because of the changes made to address 1, the evm transaction handler will no longer have an infinite gas meter when its processing starts, so we need to overwrite it …
> [EVM] return gas info in message handler correctly

- aclmapping/utils/resource_type.go
- aclmapping/utils/resource_type_test.go
- app/app.go
- go.mod
- go.sum
- loadtest/config.json
This generates the estimates similar to how dependencies are generated in the original parallelism model, and then bundle it with the deliverTX request.
local chain + ongoing testing on loadtest cluster
> [occ] enable occ prefill estimates from sei chain

- .golangci.yml
- cmd/seid/cmd/root.go
- go.mod
- go.sum
- tools/README.md
- tools/cmd.go
- tools/tx-scanner/client/grpc.go
- tools/tx-scanner/cmd/scan.go
- tools/tx-scanner/query/block.go
- tools/tx-scanner/query/tx.go
- tools/tx-scanner/scan_cmd.go
- tools/tx-scanner/state/types.go
Add a command line for seid to scan missing transactions:
- The tool will persist the state (offset and detected heights) to a json file if --state-dir is specified
- The tool can be run as a background daemon and won't crash even if seid is stopped
- The tool will resume from where it was left for each restart and will keep running after it hits latest height
- All the missing tx blocks will be output and persisted into tx-scanner-state.json
- Added a readme for sei tools
Tested on testnet rpc nodes:
```
root@ip-172-31-20-148:/home/ubuntu/sei-chain# cat tx-scanner-state.json  |jq
{
"last_processed_height": 44394319,
"blocks_missing_txs": null
}
root@ip-172-31-20-148:/home/ubuntu/sei-chain# seid tools scan-tx --start-height 44392219 --state-dir ./
Detected last processed height: 44394319 …
```
> [CLI] Add seid tools command and tx scanner tool for sei chain

- aclmapping/dependency_generator.go
- aclmapping/evm/mappings.go
- aclmapping/evm/mappings_test.go
- aclmapping/utils/resource_type.go
- app/app.go
- go.mod
- go.sum
Add ACL dependencies for EVM transactions. Note that it only contains non-wildcard matching for `to` address, since `from` address must be derived from signature which is a costly process that only happens during ante processing (i.e. after dependency evaluation). All contract state accesses are covered by wildcards.
unit tests
> [EVM] add ACL dependencies

- aclmapping/evm/mappings.go
- evmrpc/block.go
- evmrpc/setup_test.go
- evmrpc/tx.go
- evmrpc/tx_test.go
- x/evm/ante/sig.go
- x/evm/client/cli/tx.go
- x/evm/keeper/msg_server.go
- x/evm/types/message_evm_transaction.go
- x/evm/types/message_evm_transaction_test.go
Fixes the following:
- `rpc` flag conflicts with existing flag name. Changing it to `evm-rpc`
- `to` address might be nil in the case of contract creation. Handle it properly in dependency generator
- Exclude `AssociateTx` from EthereumTx decoding since it's not standard Ethereum TX but a Sei-specific utility type
- Return pending transaction (i.e. unconfirmed transactions in mempool) in `getTransactionByHash`
local sei
> [EVM] several bug fixes

- loadtest/scripts/metrics.py
The script for loadtest result is not accurate in terms of calculating `average_block_time` and `average_throughput_per_sec`.
This is because the total duration is over-estimated for the current logic.
The correct way to calculate total duration is to only add up the block time that we send transactions to since the current loadtest client has to wait and stop sending tx between rounds.
> Fix loadtest metric script

- app/ante.go
- x/evm/ante/fee.go
- x/evm/ante/preprocess.go
- x/evm/ante/preprocess_test.go
Add blanket dependencies for EVM ante handlers (R/W for acc, bank ,evm). Right now it's not possible to get more granular dependencies because the `from` address is not know at the time of dependency evaluation. This may be improved with ante handler refactoring (i.e. stateless ante handler runs first, fully parallelized -> dependency graph -> stateful ante handlers)
unit tests as well as local testing
> [EVM] add deps for EVM ante handlers

- loadtest/config.json
- loadtest/loadtest_client.go
- loadtest/tx.go
- loadtest/types.go
Allow the loadtest client to take a list of endpoints to better distribute load
Tested on a loadtest cluster
> Allow loadtest client to take a list of grpc endpoints

- cmd/seid/cmd/root.go
- docker/rpcnode/config/config.toml
- evmrpc/config.go
- evmrpc/config_test.go
- evmrpc/send.go
- evmrpc/server.go
- scripts/initialize_local_chain.sh
Added a slow config for sending raw txns. When set to true, it should only our RPC to process one transaction at a time.
local testing, however uniswap hardhat tests still don't work.
> [EVM] --slow config for send raw txn

- x/evm/client/cli/tx.go
We want to allow accounts that are not managed by `seid keys` to also be able to associate address through CLI. Note that the private key will not be transferred via network; it's only used locally (local to where the seid command is run) to compute the signature and only the signature will be transferred to remote sei node.
local sei testing
> [EVM] allow passing in private key hex for address association

- app/ante_test.go
- evmrpc/filter.go
- evmrpc/filter_test.go
- evmrpc/query_builder.go
- evmrpc/setup_test.go
- evmrpc/subscribe.go
Previously `GetLogs` might return empty even if it should return some logs. That is because the log endpoint used to use `EventLog` in Tendermint which is transient (i.e. only stored in memory). When the node is restarted, the event log is gone.
This PR changes all logs related endpoints to use transaction index instead to query for logs.
Also, the block filter was broken because there is an additional wrapper in the tendermint response over EventData. This PR fixed that as well.
local sei testing with hardhat-boilerplate contracts (and the log it generates)
unit tests
> [EVM] fix logs disappearing issue

- evmrpc/block.go
- evmrpc/block_test.go
This fixes this error:
```
server returned empty uncle list but block header indicates uncles
```
There's a magic value that we have to use to indicate zero uncles.
- Updated unit test
> Fix empty uncle hash

- Dockerfile
This is necessary so that the libwasmvm static lib works properly since the required go version was recently bumped to go `1.21.4` 
`docker build . -t sei`
> bump golang version for docker container

- .github/workflows/compatiblity_check.yml
- aclmapping/evm/mappings.go
- aclmapping/evm/mappings_test.go
- aclmapping/utils/resource_type.go
- app/app.go
- go.mod
- go.sum
- x/evm/client/cli/tx.go
- x/evm/module.go
- x/evm/state/balance.go
- x/evm/state/statedb.go
- x/evm/state/utils.go
- x/evm/state/utils_test.go
Previously we were truncating any amount after the sixth decimal point in balance operations, which could cause confusion to some developers or just outright render some applications unusable.  This PR makes use of the new bank keeper functions introduced in https://github.com/sei-protocol/sei-cosmos/pull/386 to handle amounts up to 18 decimal points properly.
unit test
integrated with local sei
> [EVM] call SendCoinsAndWei to support 18-decimal point precision

- x/dex/contract/abci.go
- x/dex/contract/abci_test.go
- x/dex/contract/execution.go
- x/dex/contract/runner.go
- x/dex/contract/runner_test.go
- x/dex/module.go
Any panic in EndBlock would cause the chain to halt, so we decide to add back panic recovery handler. Also made executions for multiple pairs sequential for each contract so that panics are easier to manage.
After this fix, there will be:
- `EndBlock` function, the main goroutine, with a panic handler at https://github.com/sei-protocol/sei-chain/compare/fix-dex?expand=1#diff-f32c70484252fadec70cda9a6ad7888fd568f6afffb3750bb9621090e2ac88bbR307
- ParallelRunner, which is the only place where goroutines will be spawned under the main goroutine, with a panic handler inside the spawned goroutine function at https://github.com/sei-protocol/sei-chain/compare/fix-dex?expand=1#diff-e2db42e8d9bee39dc72e4b409b496fd72ca1959186d8b81f000dfc16ccc26a14R137
Tested locally by reproducing the reported bug …
> Add catch all panic handler in dex endblock

- wasmbinding/test/query_test.go
- x/oracle/abci.go
- x/oracle/abci_test.go
- x/oracle/keeper/keeper.go
- x/oracle/keeper/keeper_test.go
This ensure that oracle feeds are removed at the end of the oracle slashing window IF the asset is no longer whitelisted. Additionally, it prevents the TWAPs endpoint from serving twaps for denoms that are no longer in the whitelist.
Unit tests
> Cleanup removed oracle feeds

- app/seidb.go
Problem:
When seiDB is enabled, and snapshot is enabled as well, we need to make sure ss store is also enabled to provide historical state access, otherwise it would end up creating bad snapshots that could cause app hash issues for state sync.
Solution:
We can add a config validation during app initialization to make sure people have the correct setting set up.
Tested in local docker chain and verify the configs are validated, bad configs are rejected
```
6:59PM INF --tracing not passed in, tracing is not enabled
6:59PM INF Creating node metrics provider
6:59PM INF Starting Process
6:59PM INF SeiDB is enabled, running node with StoreV2 commit store
panic: Config validation failed, SeiDB SS store needs to be enabled when snapshot interval 100 > 0
goroutine 1 [running]: …
```
> Add config validation logic for seidb

- cmd/seid/cmd/genaccounts.go
- docker/localnode/Dockerfile
Fixes for gen accounts command to only run for test keyring and also update docker cluster go version to 1.21.4
tested using `make docker-cluster-start`
> fix docker cluster and gen accounts evm address linking

- app/app.go
- loadtest/loadtest_client.go
- loadtest/main.go
- loadtest/sign.go
- loadtest/tx.go
A few more fixes after noticing some performance issues:
- only numProducer accounts were used, limiting the throughput
- parallelize loading keys to make startup faster
- increase numProducers
- add a buffer for highTps tests to allow producers to populate the queue
- fix hanging threads
ran against loadtest cluster:
> Loadtest producer consumer various fixes

- evmrpc/block.go
- evmrpc/block_test.go
- evmrpc/tx.go
- evmrpc/tx_test.go
Fixes for:
[Tony] Invalid value supplied to RpcBlockWithTransactions
[Tony] eth_getTransactionReceipt is missing contractAddress field
curl --location 'https://evm-devnet.seinetwork.io' \
--header 'Content-Type: application/json' \
--data '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x57beed40598914c0d90cd903d883633df9afa8117f5a4bd37ae29a3d670a5218"],"id":1}'
unit tests
> Minor RPC fixes

- loadtest/main.go
- loadtest/sign.go
- loadtest/tx.go
Fix loading account logic in loadtest client
> Lt client fix

- contracts/test/EVMCompatabilityTester.js
- evmrpc/association.go
- evmrpc/send.go
- evmrpc/send_test.go
Previously `sendRawTransaction` would send associate TX if the payload can be unmarshaled into an AssociateTx, and `Associate` endpoint would delegate the call to `sendRawTransaction`. This PR removes the associate tx logic in `sendRawTransaction` and make `Associate` directly broadcast to tendermint.
unit test (existing)
> Separate endpoint for associateTx

- .github/workflows/integration-test.yml
- go.mod
- go.sum
- integration_test/bank_module/send_funds_test.yaml
- integration_test/contracts/create_tokenfactory_denoms.sh
- integration_test/contracts/deploy_dex_contract.sh
- integration_test/contracts/deploy_wasm_contracts.sh
- integration_test/seidb/state_store_test.yaml
- Add seidb state store integration tests
- Add multiple wasm store code tx's at different height intervals
- Add multiple tokenfactory create denom tx's at different height intervals
- Run verification on number of contracts, contract id, tokenfactory denoms
- Iteration: wasm list code / tokenfactory get denoms from creator. Historical: Query each at different height intervals
- Testing in progress
> SeiDB State Store Integration Tests

- go.mod
- go.sum
- x/evm/keeper/keeper.go
- x/evm/keeper/keeper_test.go
- x/evm/state/check.go
- x/evm/state/check_test.go
EVM would generate cachekv with more levels than normal transactions, but iterators in cachekv with too many levels are very inefficient (to a point where it would appear that the chain has halted). There are only two iterator usage in `evm`:
- remove all keys under some prefix -> replaced by the dedicated `DeleteAll` call that doesn't have the same inefficiency as iterators
- check if account has state -> removed because only contracts can have states and we already check for code hash under the address.
unit test that would hang before the change but pass after the change
> Remove iterator usage in EVM

- app/app.go
This sets the txIndex appropriately for synchronous execution as well, which doesnt change tx outcomes, but has had impact on gas usage in the past because of memstore used for fee collection.
Verified gas usages were consistent.
> Update synchronous execution to set tx indices properly

- cmd/seid/cmd/debug.go
This fixes the iavl-dump by fixing the accesscontrol storekey from `accesscontrol` to `aclaccesscontrol`
verify proper iavl output
> fix debug iavl dump

- evmrpc/simulate.go
- we do not want to read latest Tendermint block because it's not committed atomically with (and before) application state for that height. So when "latest" (or equivalent) is requested, we should use the latest application height (obtained from latest context) instead
- even though we check if a version exists in store before querying, it's possible for that version to be pruned in the short window between the check and the query. So we'd still need to add a panic catcher at the query to account for such cases.
need to test on loadtest cluster
> Edge case fixes for height-based queries

- app/upgrades.go
- update upgrades.go so we can test a major upgrade
- version is `v4.0.5-evm-devnet`
- pre-devnet evm environment upgrade
> [EVM] tick version for v4.0.5-evm-devnet

- x/evm/keeper/keeper.go
- x/evm/keeper/keeper_test.go
- x/evm/module.go
- x/evm/module_test.go
We previously refactored the in memory golang struct containing txHashes for EVM transactions into a mem KV such that the state generated would be revertible as necessary by OCC. Previously with the in memory list, we would clear it out int he following beginblock, but a similar change wasn't included when moving to an in memory KV store. As a result, stale tx hashes can build up for tx indices not overwritten in a block, resulting in potential appHash errors when nodes restart since the in memory KV stores arent restored. This change introduces the appropriate `Clear` function and calls it in EndBlock as soon as evm is done with the txHash data.
unit tests
> Clear txDeferredInfo in EndBlock

- evmrpc/block.go
- evmrpc/block_test.go
This removed bank send from the txs returned for evm block txs
> remove msgSend from evm block tx filtering

- aclmapping/evm/mappings_test.go
- app/upgrades.go
- go.mod
- go.sum
Bump seidb and cosmos version to latest. Including the fix for:
- segmentation fault
- concurrent map access
- disable seqno
- No longer disable dynamic dep generation during ACL dependency generation
> Bump seidb and cosmos version to latest

- go.mod
- go.sum
- oracle/price-feeder/oracle/client/client.go
- x/oracle/ante.go
When oracle broadcast fail due to vote already exist, we should not consider that as a failure. We can ignore and consider it as a successs.
> Ignore error for vote already exist

- scripts/run-node.py
Create an easy tool for starting a sei node. This will ultimately help with documentation as we no longer need to maintain a lot of resources on the web page. Inspiration comes mostly from https://docs.osmosis.zone/osmosis-core/osmosisd
Tested locally
> Create rpc startup script

- app/app.go
- x/evm/keeper/keeper.go
- x/evm/keeper/keeper_test.go
- x/evm/module.go
- x/evm/module_test.go
This is a performance optimization resulted from recent load test. Specifically storing and iterating through deferred info in cachekv store is a major bottleneck. This change replaces cachekv usage with an in-memory `sync.Map`, which:
- is cleared at each `BeginBlock`
- is key'ed by tx index, so that rerun of the same tx will overwrite its previous run's entry
- may contain invalid entries (e.g. tx X finished successfully in its first run and inserted an entry to this map, but needed to rerun and finished erroneously during rerun), which are excluded based on `ExecTxResult`
local sei && unit tests
> Use in-memory map for deferred info

- evmrpc/simulate.go
- evmrpc/tx.go
Fixed 2 small bugs:
1. txIndex should be used not index (which was automatically 0)
2. we need to return the evmIndex. THis is already used elsewhere so move that to a helper function
- unit tests still pass
- tested on evm-devnet:
```
root@ip-172-31-38-43:/home/ubuntu/sei-chain# curl http://localhost:8545 -X POST -H "Content-Type: application/json" --data '{"method":"debug_traceTransaction","params":["0xf2192a7d0fa48f41d382bbc55e9c6852ae6b4b374cbdf15a527049b94e029723", {"tracer": "callTracer"}], "id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"result":{"from":"0xf87a299e6bc7beba58dbbe5a5aa21d49bcd16d52","gas":"0x5208","gasUsed":"0x5208","to":"0xf87a299e6bc7beba58dbbe5a5aa21d49bcd16d52","input":"0x","value":"0x1","type":"CALL"}}
```
> Fix debug trace tx

- x/evm/client/cli/tx.go
The `--evm-chain-id` does not exist and is not necessary so remove it
> Update evm tx cli to remove non-existent flag

- loadtest/scripts/populate_genesis_accounts.py
We introduced an "evm_address" field which caused the position of the mnemonic to change. Instead, use the last value in array.
```
- name: psu-test
type: local
address: sei179ep77c0x4d5gccfpk5wq2dm0sfpsxp9mllaru
evm_address: ""
pubkey: '{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"AvHWnr1680gyFscSzqJpFgRFA6l6p6m7NPXiKIMmV67t"}'
```
Deployed LT cluster
> Fix mnemonic for populate accounts

- evmrpc/block.go
- evmrpc/block_test.go
- if no transactions, there is a special value that the transacitonRoot should have
- otherwise, clients will fail to parse the value
- new unit test
> [EVM] fix empty tx root value

- app/ante.go
- precompiles/wasmd/wasmd_test.go
- x/evm/ante/preprocess.go
- x/evm/ante/preprocess_test.go
- x/evm/ante/router_test.go
When a new account makes a Cosmos transaction, the chain will be able to obtain its pubkey. We can take this opportunity to also set EVM address association for it if it's not already set.
unit test & local sei
> Set address association for Cosmos tx

- loadtest/contracts/deploy_erc20.sh
Deploying evm contracts was previously broken. See this output:
```
{"ERC20":"0x0000000000000000000000000000000000000000","ERC721":"0x0000000000000000000000000000000000000000"}}
```
This is because https://github.com/sei-protocol/sei-chain/blob/evm/loadtest/main.go#L83 it expects only one output. However, before other outputs were breaking this.
Tested:
```
:{"ERC20":"0x0eb8cd1440c7d6beee12ea511b9b7bcd84810921","ERC721":"0x0000000000000000000000000000000000000000"}}
```
> Remove command output that breaks loadtest deploying

- contracts/src/ERC721.sol
- contracts/test/ERC721Test.js
- loadtest/contracts/deploy_erc721.sh
- loadtest/contracts/evm/bindings/erc721/abi.json
- loadtest/contracts/evm/bindings/erc721/erc721.go
- loadtest/contracts/evm/src/ERC721.sol
- loadtest/evm.go
- loadtest/loadtest_client.go
- loadtest/main.go
- loadtest/types.go
- created new PR for erc721 changes 
- load tests
> [EVM] Add erc721 to loadtest

- .dockerignore
The problem this commit fix was that the `seid` binary built via Docker didn't contain the correct version when doing `seid version` because `.dockerignore` was specifying that `.git` should not be copied to the Docker context.
However, without copying it, the version cannot be computed anymore since the Makefile is defining version to be `VERSION := $(shell echo $(shell git describe --tags))` and of course if the `.git` is not copied, then this command cannot work.
Removing the `.git` from `.dockerignore` fixes the problem, it brings context transfer from `~78 MB` to `~295 MB` which added `1.1s` to a Docker build (0.4s vs 1.5s) on a Mac M1 Max.
```
$ git checkout seiv2 && docker build . -t "sei-chain:test-docker" --load && docker run --rm -it sei-chain:test-docker version
$ git checkout …
```
> Pass `.git` folder to Docker context

- evmrpc/config.go
- evmrpc/config_test.go
- evmrpc/rpcstack.go
- evmrpc/rpcstack_test.go
- go.mod
- go.sum
This PR add a new configuration for EVM RPC to configure deny list. If a method appears in deny list, the server will return an error response to indicate the method is not found.
Config would be look like:
deny_list = ["eth_a", "eth_b"]
Added unit test for deny list.
> Add deny list config for EVM RPC

- go.mod
- go.sum
> update sei-cosmos dependency to v0.2.77

- x/evm/ante/preprocess.go
- x/evm/ante/preprocess_test.go
When an account gets associated, if it has ever received any tokens, we want to transfer all of those from the temporary location to the correct sei address. This was done for all bank tokens except for wei. This PR adds such transfer for wei.
unit test
> Transfer wei when account is associated

- x/evm/ante/preprocess.go
- x/evm/ante/preprocess_test.go
- x/evm/ante/sig.go
Previously there were two issues with our handling of unprotected TXs:
- They are outright not allowed (checked in sig.go), but they do still exist in today's Ethereum mainnet
- The pubkey derivation logic for unprotected TXs was wrong. Specifically we need to use Frontier's hashing logic for unprotected TXs.
unit tests & replay
> Handle unprotected TXs properly

- app/app.go
- app/eth_replay.go
- cmd/seid/cmd/ethreplay.go
- cmd/seid/cmd/root.go
- x/evm/ante/preprocess.go
- x/evm/keeper/genesis.go
- x/evm/keeper/keeper.go
- x/evm/keeper/msg_server.go
- x/evm/keeper/params.go
- x/evm/keeper/replay.go
- x/evm/keeper/state.go
- x/evm/module.go
- x/evm/replay/config.go
- x/evm/state/accesslist.go
- x/evm/state/balance.go
- x/evm/state/check.go
- x/evm/state/code.go
- x/evm/state/expected_keepers.go
- x/evm/state/nonce.go
- x/evm/state/state.go
- x/evm/types/keys.go
Add a new command `ethreplay` to replay transactions from ethereum mainnet. Note that currently this command only supports one-off mode (i.e. replay a predefined number of blocks and exit), but can be extended to long-running if needed in the future.
Details of operation can be found here: https://www.notion.so/3pgv/ETH-Mainnet-Replay-8887dea71cbc4f3294c264f8d8858e83
Even though this PR added a new state prefix, it would never be written/read if `eth_replay.enabled = false`, which will be the case for all actual network nodes.
replay
> Add utils to replay ETH mainnet txs

- precompiles/distribution/distribution_test.go
- precompiles/staking/staking.go
- precompiles/staking/staking_test.go
- x/evm/ante/preprocess.go
- x/evm/keeper/address.go
- x/evm/keeper/address_test.go
- x/evm/keeper/code.go
- x/evm/keeper/code_test.go
Right now there is no association or `Account` object set for EVM contracts, which makes it impossible for them to become delegators. This PR:
- sets association and `Account` for EVM contract when its code is set. The associated Sei address is directly cast from the EVM address bytes
- refactored `Account` setting logic so that it becomes part of `SetAddressMapping`, since we need the invariant that any associated address has `Account` set
- made staking precompile errors message more explicit if the delegator is not associated
unit test
> Set association and account for EVM contracts

- evmrpc/simulate.go
- evmrpc/subscribe.go
- precompiles/bank/bank.go
- utils/constants.go
- x/evm/ante/fee.go
- x/evm/ante/preprocess.go
- x/evm/client/cli/tx.go
- x/evm/keeper/evm.go
- x/evm/keeper/keeper.go
- x/evm/keeper/params.go
- x/evm/module.go
- x/evm/state/balance.go
- x/evm/state/check.go
- x/evm/state/statedb.go
- x/evm/state/utils.go
- x/evm/types/config.go
- x/evm/types/ethtx/legacy_tx.go
- x/evm/types/ethtx/txdata.go
Use constants instead of keep allocating new variables whenever values like `big.NewInt(0)` is needed
unit tests
> Set big int constants

- app/app.go
- utils/metrics/labels.go
This adds metrics for the OCC logic paths to properly show gas used and gas wanted for nodes running OCC execution as well.
> Add occ metrics for gas used

- evmrpc/filter.go
We should not replace the original log index in RPC response
patched on an rpc node and made filter request to it to verify log index field is properly set
> Not override log index

- app/eth_replay.go
- x/evm/keeper/keeper.go
Prevent having to query block for every transaction
replay
> cache block during eth replay

- app/ante.go
- app/antedecorators/authz_nested_message.go
- app/antedecorators/authz_nested_message_test.go
- Ante handler to reject authz msg Execs which contain nested evm messages
- Added unit tests
- Verifying e2e
> Ante Handler: Nested Evm Messages within Authz 

- app/app.go
- contracts/src/EVMCompatibilityTester.sol
- contracts/test/EVMCompatabilityTester.js
- evmrpc/simulate.go
- this uses the block context passed through the api
- otherwise create the default latest context (existing)
- manual api calls
- hardhat test for tracing
- hardhat test for block properties
> [EVM] Fix timestamp in evm read calls

- app/eth_replay.go
- evmrpc/simulate.go
- go.mod
- go.sum
- x/evm/module_test.go
- x/evm/state/balance.go
- x/evm/state/balance_test.go
- x/evm/state/check_test.go
- x/evm/state/code.go
- x/evm/state/log.go
- x/evm/state/nonce.go
- x/evm/state/state.go
- x/evm/state/state_test.go
- x/evm/state/statedb.go
This only brings the dependency (will need to wait for a merge + tag of the branch before merging this PR) and the required changes to adapt `DBImpl` to support the new interface.
Relates to:
- https://github.com/sei-protocol/go-ethereum/pull/15
- https://github.com/sei-protocol/sei-chain/pull/1344
This makes the necessary changes in `sei-chain` to bump `go-ethereum` to the upcoming version with enhanced EVM tracing.
Run unit tests. `evmrpc/tracers_test.go:20` test `TestTraceTransaction` fails, the `gasLimit` seems not populated correctly now. I need to investigate further as I don't quite understand actually how it's passing before. 
I wanted to open the PR sooner than later, I'll fix the test tomorrow.
> Update that brings `go-ethereum` with live tracer support

- app/eth_replay.go
- x/evm/keeper/replay.go
- x/evm/module.go
- Use cached block in `EndBlock`
- Verify contract states
applied to the replay node
> Optimize replay

- app/app.go
- cmd/seid/cmd/root.go
- x/evm/keeper/grpc_query.go
- x/evm/keeper/keeper.go
- x/evm/querier/config.go
Right now EVM static call query uses an infinite gas meter that may be subject to DoS attacks. This PR adds a config-based gas limit to this query endpoint.
local sei with config gas limit setting to 1
> Add gas limit for EVM static call query

- precompiles/addr/addr.go
- precompiles/bank/bank.go
- precompiles/common/precompiles.go
- precompiles/common/precompiles_test.go
- precompiles/distribution/distribution.go
- precompiles/gov/gov.go
- precompiles/ibc/ibc.go
- precompiles/json/json.go
- precompiles/oracle/oracle.go
- precompiles/pointer/pointer.go
- precompiles/pointerview/pointerview.go
- precompiles/staking/staking.go
- precompiles/wasmd/wasmd.go
- x/evm/state/check_test.go
- Previously we panicked for incorrect arg length and asserting non payable
- Remove panic in favor of raising errors
- Verified on unit tests
- Verified on chain
> Precompiles Raise Error over Panic

- evmrpc/block.go
- evmrpc/info.go
- precompiles/common/precompiles.go
- precompiles/ibc/ibc.go
- precompiles/wasmd/wasmd.go
- x/evm/ante/fee.go
- x/evm/ante/fee_test.go
- x/evm/ante/gas.go
- x/evm/keeper/evm.go
- x/evm/keeper/keeper.go
- x/evm/keeper/msg_server.go
- replace banker's rounding to explicit `TruncateInt`
- only truncate after computation not before
existing test should still hold
> Fix Int rounding issues

- x/evm/state/state.go
- x/evm/state/state_test.go
- x/evm/state/statedb.go
Geth's behavior of SelfDestruct is to only clear account balance when SelfDestruct is called but clear other account states at the end of the transaction. This PR aligns sei's behavior to that of Geth's
unit test
> Clear self-destructed account state at the end of tx

- x/evm/keeper/keeper.go
- x/evm/keeper/msg_server.go
- x/evm/module.go
- x/evm/module_test.go
We want to have some records for transactions that fail with a panic. This PR write receipts for transactions that had a panic during processing.
unit test
> Write receipt for txs with non VM errors

- precompiles/addr/addr.go
- precompiles/bank/bank.go
- precompiles/bank/bank_test.go
- precompiles/common/precompiles.go
- precompiles/distribution/distribution.go
- precompiles/gov/gov.go
- precompiles/ibc/ibc.go
- precompiles/json/json.go
- precompiles/oracle/oracle.go
- precompiles/pointer/pointer.go
- precompiles/staking/staking.go
- precompiles/wasmd/wasmd.go
- precompiles/wasmd/wasmd_test.go
Ottersec:
```
Not collecting gas for unknown precompile contract calls. This is not a critical issue in itself, since the evm call opcode already consumes gas, but we'd like to confirm whether this is intended behavior
```
This is not intended and this PR fixes it
const change
> Set unknown method call on precompiles to be non-zero

- precompiles/json/json.go
- precompiles/json/json_test.go
```
The json precompile extractAsBytesList [function](https://github.com/sei-protocol/sei-chain/blob/c932310d1ca1b55adfd01a9e22baed50753dcf69/precompiles/json/json.go#L140) will fail if any of the fields in the data could not be interpreted as a list.
```
unit test
> Fix extractAsBytesList in json precompile

- x/evm/state/balance.go
- x/evm/state/balance_test.go
If a contract is self-destructed in the same block, we want subsequent balance changes to it to no-op, as this is the behavior in Ethereum. Note that `HasSelfDestructed`  will only return true if the self-destruct happened in the same block AND the account is not recreated in the same block
unit test
> Disallow balance change for self-destructed address

- integration_test/evm_module/hardhat_test.yaml
- loadtest/config.json
- loadtest/loadtest_client.go
- loadtest/main.go
- loadtest/types.go
Add a new loadtest config `post_tx_evm_queries` to specify what EVM queries should be benchmarked after the normal EVM transactions are loadtested (since we need load first in order to query), and the number of concurrent queries to send. Right now we support two query types but more can be added:
- block header & transactions
- transaction receipt
load test cluster
> Add mechanism for benchmarking EVM queries

- evmrpc/filter.go
- evmrpc/filter_test.go
- integration_test/evm_module/hardhat_test.yaml
https://linear.app/seilabs/issue/SEI-7055/insecure-direct-object-reference-idor-issue-in-filter-rpc-api
tldr: an auto-incrementing integer ID may open an attack vector where a malicious user can keep deleting others' filters
unit tests
> Use random string filter ID instead of incrementing ints

- x/evm/state/balance.go
- x/evm/state/state.go
- x/evm/state/state_test.go
- x/evm/state/statedb.go
Instead of ignoring balance changes to self-destructed accounts in the same block, we want to keep track of the balance changes (just in case the account is recreated in the same block) and burn any remaining tokens at the end of the transaction
unit test
> Fix balance behavior for selfdestructed accounts

- app/ante.go
- app/ante_test.go
- x/evm/ante/error.go
We want every EVM transaction that makes into a block to have a receipt persisted for it, regardless of whether the transaction succeeds, fails with a VM error, fails with a non-VM error, or fails ante. That last scenario was not previously covered and is what this PR is for.
unit test
> Add ante error handler for EVM msgs

- contracts/test/EVMPrecompileTester.js
- precompiles/addr/addr.go
- precompiles/bank/bank.go
- precompiles/common/expected_keepers.go
- precompiles/distribution/distribution.go
- precompiles/gov/gov.go
- precompiles/gov/gov_test.go
- precompiles/ibc/ibc.go
- precompiles/wasmd/wasmd.go
- precompiles/wasmd/wasmd_test.go
- x/evm/artifacts/native/artifacts_test.go
- x/evm/client/wasm/query.go
- x/evm/client/wasm/query_test.go
- x/evm/keeper/address.go
- x/evm/keeper/evm.go
- x/evm/state/utils_test.go
This PR is to address an issue found in Sec3 audit.
If unassociated EOA addresses are allowed to use precompiles like `wasmd` or `staking`, they will leave behind states key'ed under their default address counterpart (i.e. direct casting), which will be impossible to identify and merge when the account does get associated. As a result, we need to restrict unassociated addresses from making any precompile calls.
unit tests
> Disallow unassociated EOA addresses from using precompiles

- x/evm/client/wasm/bindings/queries.go
- x/evm/client/wasm/query.go
- x/evm/client/wasm/query_test.go
For a wasm binding query we need to marshal it as json, and for bytes we usually encode it as base64. Neither was done for `StaticCall`'s response which is fixed by this PR.
unit test
> Marshal wasm-evm StaticCall response

- cmd/seid/cmd/root.go
- evmrpc/config.go
- evmrpc/config_test.go
- evmrpc/filter.go
- evmrpc/filter_test.go
- evmrpc/server.go
- evmrpc/setup_test.go
- evmrpc/subscribe.go
We want to apply a limit for log-related queries similar to how Alchemy does for its endpoints:
unit test
> Add limit to filter logs

- app/app.go
- precompiles/addr/addr.go
- precompiles/bank/bank.go
- precompiles/common/precompiles.go
- precompiles/distribution/distribution.go
- precompiles/gov/gov.go
- precompiles/ibc/ibc.go
- precompiles/json/json.go
- precompiles/oracle/oracle.go
- precompiles/pointer/pointer.go
- precompiles/pointerview/pointerview.go
- precompiles/setup.go
- precompiles/staking/staking.go
- precompiles/wasmd/wasmd.go
- x/evm/client/cli/common.go
- x/evm/client/cli/query.go
- x/evm/client/cli/tx.go
- remove deprecated pointer deployment CLIs (pointer are now deployed via precompiles)
- generalize the delegate CLI for all precompiles (usage: `seid tx evm call-precompile [precompile name] [method] [args...] --value=`
local sei
> Cleanup EVM CLI

- integration_test/distribution_module/rewards.yaml
The distribution integration tests tend to be flaky on PR CI due to the query for distribution rewards sometimes querying to quickly and therefore not returning the expected increase in rewards. This adds a pause such that we can give some time so the test doesnt flake due to inconsistent query timing.
Integration tests
> Fix distr integration test

- x/evm/module.go
- x/evm/module_test.go
- x/evm/state/balance.go
- x/evm/state/balance_test.go
Fix for https://linear.app/seilabs/issue/SEI-7179/immunefi-evm-module-panic-report
For operations that aim to transfer the whole balance from an address to the other, we should use `SpendableCoins` instead of `GetBalance` so that locked tokens won't be attempted
unit test
> Only consider spendable coins when transferring in EVM

- contracts/test/CW20toERC20PointerTest.js
- contracts/test/lib.js
- x/evm/keeper/evm.go
- x/evm/keeper/msg_server.go
- x/evm/module.go
Previously for a CosmWasm transaction that enters EVM space (i.e. via wasmbinding) for the first time in its transaction lifecycle, we are merely calling `evm.Call` or `evm.Create`, which is problematic because that omits a bunch of checks and preparation logic in `StateTransition::TransitionDb`. This is not a problem for transactions that have already invoked `TransitionDb` at some point earlier in its lifecycle (e.g. an EVM tx that calls CW via precompile which then calls back to EVM via wasmbinding), for which we can detect via checking for `evm` in the context
```
TransitionDb
Prechecks
Charge Intrinsic Gas
Prepare StateDB (including setting AccessLists)
evm.Call
```
Note a couple things with TransitionDb invoked this way:
- no receipt will be created (because there is no EVM tx hash …
> Invoke StateTransition for initial EVM entrance

- x/evm/keeper/evm.go
- x/evm/keeper/evm_test.go
This disallows passing negative values into the Internal EVM Call function.
Unit Test
> Disallow negative value passed into internal EVM calls

- loadtest/main.go
Loadtest TPS isn't correctly calculated when there are mix tx types. This PR fix the tps calculation logic by adding perMsgType tps together into totalTPS
Verified in Loadtest cluster
> Fix loadtest client TPS calculation logic

- app/app.go
- x/oracle/ante.go
- x/oracle/keeper/keeper.go
- x/oracle/keeper/keeper_test.go
- x/oracle/keeper/test_utils.go
- x/oracle/types/keys.go
This refactors the oracle spam prevention decorator from using an in memory map and instead uses an in memory KV store to improve its compatibility with OCC execution
Updated unit tests
> Refactor oracle spam counter to use mem store instead of in memory map

- app/app.go
- app/upgrades.go
This registers the `v5.1.0` upgrade to be used on environments NOT having EVM module. This will add the evm module to the store keepers and perform related store upgrades
Tested upgrading from `v3.9.0` to `v5.1.0` locally
TODO: wait to merge until code frozen and also update changelog + remove TODO message
> V5.1.0 upgrade

- app/app.go
In replay we do additional write after FinalizeBlock returns, which would cause the `WriteStateToCommitAndGetWorkingHash` call in Commit() that comes after those writes to fail, because `WriteStateToCommitAndGetWorkingHash` has already been called in FinalizeBlock
replay
> Do not call `WriteStateToCommitAndGetWorkingHash` in FinalizeBlocker during replay

- evmrpc/utils.go
- x/evm/client/cli/tx.go
Similar to https://github.com/sei-protocol/sei-cosmos/pull/495/files, ```priv, err := legacy.PrivKeyFromBytes([]byte(localInfo.PrivKeyArmor))``` only works with secp256k1 algo, so we should disallow using sr25519 addresses
```
root@ip-172-31-4-247:/home/ubuntu/sei-chain# printf "12345678\n" | seid tx evm send 0xF87A299e6bC7bEba58dbBe5a5Aa21d49bCD16D52  100000000000000000 --from sei-foundation
Error: can only use addresses using secp256k1
```
> Disallow using sr25519 addresses for evm send and other funcs

- evmrpc/setup_test.go
- evmrpc/simulate.go
- go.mod
- go.sum
- x/evm/ante/preprocess.go
> Add association logic in simulate

- evmrpc/filter.go
- evmrpc/server.go
- evmrpc/setup_test.go
- evmrpc/subscribe.go
- evmrpc/subscribe_test.go
instead of having each subscription subscribing to tendermint and encode to JSON independently, we will maintain a single subscription with tendermint and a single copy of encoded JSON per head, then fan it out to all outgoing subscriptions
> optimize WS newhead

- evmrpc/tx.go
- evmrpc/tx_test.go
- to should be nil (instead of 0x00000..) on contract deploy
- contractAddress should only be populated if to is nil (not for factory deploys)
- unit test
> [EVM] Fix contract deploy receipts

- x/evm/state/balance.go
`SpendableCoins` uses an iterator to get all coin balances first and then subtract those with `LockedCoins` (`LockedCoins` in itself doesn't require iterators), but using iterator is gonna cause huge performance issue within EVM. So this PR changes `SpendableCoins` with a point query and then do the subtraction inside stateDB.
replay test
> Avoid using iterator when getting spendable coins

- .golangci.yml
- evmrpc/subscribe.go
We want to close connection for consumers that are falling behind by too much, since otherwise we'd need to keep in memory all heads contained in the lag. Using a buffered channel for that purpose here
> Use buffered listener for NewHeads subscription

- app/antedecorators/gasless.go
- app/antedecorators/gasless_test.go
- integration_test/dex_module/cancel_order_test.yaml
- integration_test/dex_module/place_order_test.yaml
There is a potential exploit on tx body size. Given the infrequent usage of `dex` order placement, the safest way to prevent the exploit is to start charging fees on PlaceOrder messages.
unit test
> Make PlaceOrder tx not gasless

- x/evm/keeper/address.go
- x/evm/keeper/address_test.go
We want to be able to get EVM address for a CW contract address so that a CW contract can for example receive ERC20 tokens via pointer. We notice that there is a size difference between CW address and normal address so we leverage that fact to determine whether we should direct cast and early return.
Note that this is only one-way - getting Sei address for an EVM address obtained this way will not work, because the EVM address only contains a truncated version of the original Sei address.
uint test
> Always consider CosmWasm contract address as associated

- go.mod
- go.sum
- x/evm/ante/fee.go
- x/evm/derived/derived.go
- x/evm/genesis.go
- x/evm/keeper/ante.go
- x/evm/keeper/msg_server.go
- x/evm/migrations/fix_total_supply.go
- x/evm/migrations/fix_total_supply_test.go
- x/evm/module.go
- x/evm/module_test.go
- x/evm/state/balance_test.go
- x/evm/state/statedb.go
- x/evm/types/keys.go
Background:
Because EVM updates balance on one side at a time, it is possible to incur surplus during the execution (e.g. one credit of 100wei and one debit of 110wei would result in a surplus of 10wei). Such surplus are handled at `EndBlock` (sent to EVM module account) to make sure no coin is burnt/minted silently (as in, total supply would not be updated). However, surplus incurred in the ante handler (specifically the fee handler) may not be handled if the transaction fails during processing, in which case silent burning/minting would happen.
Fix:
Instead of setting state of ante surplus in the message server, we will set it inside ante handler to make sure it's always carried over. To do that, we can no longer use in-memory state, so we use memstate instead, and clear it up at the …
> Fix ante surplus handling

- scripts/run-node.py
Added check for existing `~/.sei` dir as condition for `seid tendermint unsafe-reset-all`
Deleted relevant dir prior to running script, no issues
> fix for first time setup

- x/evm/module.go
- x/evm/module_test.go
We need to set BlockNumber field, otherwise  x/evm/ante will fail.
Added unit test
> Add block number for receipt

- cmd/seid/cmd/debug.go
- x/evm/ante/preprocess.go
We want to emit signer event even for cases when there is no corresponding EVM address possible, with Sei address only
local sei
> Emit signer event for all cases

- evmrpc/info.go
- evmrpc/info_test.go
This PR add a new EVM rpc endpoint for eth_maxPriorityFeePerGas, we don't really have an exact same implementation for tip, but for now we can just return a suggested gas price using feeHist.Reward[0][0].ToInt()
Added unit test
> Add evm rpc endpoint eth_maxPriorityFeePerGas

- x/evm/gov.go
- x/evm/gov_test.go
Before we make pointer contract address stable, we want no pointer upgrade to happen. However if someone registers a contract via gov with a version number lower than the current version and then run a regular pointer deployment, they will upgrade the gov-deployed contract. This PR restricts the version being passed by the gov proposal to be at least as large as the current version. We may remove this restriction once the stable address change is in and upgrades become allowed.
unit test
> Validate pointer version set by gov

- contracts/test/ERC20toNativePointerTest.js
- contracts/test/lib.js
- precompiles/bank/bank.go
- precompiles/bank/bank_test.go
This modifies bank precompile behavior to allow receiving native tokens to an unassociated address in a casted way such that they will be migrated in `migrate_balance` upon association.
Need to add unit tests + integration tests, have performed some local chain testing but need to perform more for thoroughness.
> Allow bank precompile to use the unassociated casted address for receiving balances

- x/evm/keeper/keeper.go
Within EVM module we still want to treat the newly added VM error code as "successful" on the tx-level, in the sense that we don't want to perform a tx-level rollback.
unit tests
> Handle VM error code properly

- scripts/run-node.py
Corrected order of operations to handle "local" mode properly, fixes 'nil validator set' error.
Corrected version handling, working directory and interrupting main script at proper time when "local" mode selected.
> Fixes local network in  /scripts/run-node.py

- x/evm/keeper/msg_server.go
If there is an evm panic due to occ conflict, don't log or increment metrics for this evm panic
existing tests
> Make occ caused evm panics less noisy

- contracts/test/CW20toERC20PointerTest.js
- contracts/test/lib.js
- evmrpc/tx.go
- go.mod
- go.sum
- precompiles/wasmd/wasmd.go
- precompiles/wasmd/wasmd_test.go
- x/evm/client/cli/common.go
- x/evm/keeper/evm.go
- x/evm/keeper/evm_test.go
Previously interop hop was limited to 1 due to concerns of reentrancy attacks. This PR removes the limit and now relies on the fact that each hop would instantiate a new, isolated EVM instance as base of operation. This creates the need of bubbling up EVM events generated  in those isolated EVM instances, which is solved by a dedicated event manager in context.
integration test that calls the wasmd precompile which calls a CW->ERC pointer
> Remove interoperability hop limit with isolated EVM instances

- go.mod
- go.sum
Just bumping the go-ethereum version to pull in empty trace on insufficient funds error. Related go-ethereum change: https://github.com/sei-protocol/go-ethereum/pull/31
modified unit tests on geth since it is a bit hard to trigger this error
> Show empty trace on insufficient funds error

- app/params/config.go
- docs/migration/seiv2_config_migration.md
- Reduce defaults for ttl-duration to 15s and ttl-num-blocks to 30
- Verified on local chain
> Reduce Default TTL configs

- app/app.go
- precompiles/bank/bank.go
- precompiles/bank/bank_test.go
- precompiles/common/expected_keepers.go
- precompiles/setup.go
Usually in EVM we don't create accounts for receiver because we don't want to create accounts for cast addresses to reduce storage footprint and make execution more parallelized. `SendNative` is unique in that the receiver is not expected to be (though not impossible) cast addresses, so we should treat account creation the same as regular bank sends.
unit test
> Create account for sendNative receiver

- x/evm/keeper/keeper.go
- Replace `Random` field with hash of block timestamp
> Update Random to Hash of Block Timestamp

- x/evm/ante/preprocess.go
- x/evm/ante/preprocess_test.go
It is possible for a cast address to hold locked tokens since anyone (e.g. an attacker) can create vesting account for anyone before the account is first referenced on chain. So when consolidating balances we should only transfer the unlocked part. Any locked tokens under cast addresses will be frozen, since there is no real use case for creating vesting account for cast addresses.
unit tests
> Only send unlocked tokens upon address association

- app/test_state_store.go
- this store is just used for mocking a state store
- keys need to be sorted to have a stable iterator 
- existing unit test now passes
> Add sorting to a test store to fix flaky test

- contracts/test/CW20toERC20PointerTest.js
- evmrpc/block.go
- evmrpc/simulate.go
- evmrpc/tx.go
- x/evm/keeper/deferred.go
- x/evm/keeper/evm.go
- x/evm/keeper/evm_test.go
- x/evm/keeper/msg_server.go
- x/evm/keeper/msg_server_test.go
- x/evm/keeper/receipt.go
Create receipt for CosmWasm transactions that invoked EVM contracts. Tx hash for such receipt is set to be the Cosmos tx hash of the originating tx, which happens to also be a 20-byte array same as EVM tx hash.
unit test
integration tests
> Set receipt for CW->EVM calls

- precompiles/common/precompiles.go
- precompiles/common/precompiles_test.go
- precompiles/distribution/distribution_test.go
- precompiles/ibc/ibc_test.go
- precompiles/wasmd/wasmd_test.go
Follow geth's convention by setting revert reason in `ret` and replace any error with `ErrExecutionReverted`
> Return ErrExecutionReverted for precompile errors

- app/app.go
- app/app_test.go
Right now panics from transaction decoding are not caught. In case of a bad validator (which is the only way for decoding to panic), we want such panics to be handled gracefully (i.e. as if it encountered a non-panicking decoding error).
unit tests
> gracefully handle panics in TX decoding

- precompiles/common/expected_keepers.go
- precompiles/pointer/pointer.go
- precompiles/pointer/pointer_test.go
- utils/metadata.go
- x/evm/artifacts/artifacts.go
- x/evm/gov.go
- x/evm/integration_test.go
- x/evm/keeper/pointer.go
- x/evm/keeper/pointer_test.go
- x/evm/keeper/pointer_upgrade.go
- x/evm/keeper/pointer_upgrade_test.go
- x/evm/keeper/view.go
- x/evm/migrations/migrate_all_pointers.go
- x/evm/migrations/migrate_all_pointers_test.go
- x/evm/module.go
- x/evm/module_test.go
Previously pointer contract will be assigned a new address when it's upgraded to a new version, which is quite inconvenient to end users and applications. Since pointer contracts themselves are stateless, it is possible to reuse the same address for a new version of code. This PR implements that for the EVM->CW direction pointers. A similar change will be made for CW->EVM pointers
unit test
> Reuse the same contract address when upgrading ERC->CW pointers

- evmrpc/simulate.go
- go.mod
- go.sum
- wasmbinding/message_plugin.go
- wasmbinding/wasm.go
- x/evm/ante/fee.go
- x/evm/keeper/evm.go
- x/evm/keeper/evm_test.go
- x/evm/keeper/msg_server.go
- x/evm/state/state_test.go
- x/evm/state/statedb.go
- x/evm/types/context.go
- x/evm/types/context_test.go
Using new EVM instance for interop calls can cause discrepancies in behavior against ethereum. This PR changes the behavior to be reusing existing EVM instance, with an additional tweak which returns the latest `sdk.Context` from the evm instance to the wasmd message handler, so that there will never be a scenario where messages dispatched by a wasm call operate on different `sdk.Context`.
existing integration test should still work
> Reuse existing EVM instance in interop calls

- app/app.go
- contracts/test/AssociateTest.js
- go.mod
- go.sum
- precompiles/wasmd/wasmd_test.go
- testutil/keeper/evm.go
- x/evm/keeper/address.go
- x/evm/keeper/address_test.go
- x/evm/migrations/migrate_cast_address_balances.go
- x/evm/migrations/migrate_cast_address_balances_test.go
- x/evm/module.go
- x/evm/module_test.go
We don't want to allow users to send funds to a temporary address that's created through direct casting of an EVM address after that EVM address has been associated with its true Sei address counterpart. This PR in conjunction with [this sei-cosmos PR](https://github.com/sei-protocol/sei-cosmos/pull/526) introduces such a check.
unit test
> Disallow sending to direct cast address after association

- evmrpc/setup_test.go
- evmrpc/simulate.go
- evmrpc/simulate_test.go
If a user calls `eth_call` with a very high balance override, it isn't possible for us to actually set that address to uint256 max due to how our usei, wei logic works as well as a constraint we have that any intermediate balance must have at most 256 bits.
Specifically, when we set balances in the statedb, we need to set so that the usei balance * 10^12 + 10^12 is less than uint256 max. However, there is no integer such that usei balance * 10^12 + 10^12 == uint256 max, so if the user wanted to actually do a balance override to uint256 max, we are not able to do so.
Therefore, the best can do is produce a meaningful error message when the balance overflows.
unit test
> [EVM] Meaningful error message for eth_call balance override overflow

- x/evm/keeper/coinbase.go
Charging gas for a potentially cached operation could cause non-determinism
applied on archive node to get it out of apphash error
> Do not charge gas for feecollector address query

- .github/workflows/integration-test.yml
- Makefile
- docker/docker-compose.yml
- docker/localnode/Dockerfile
- docker/localnode/scripts/deploy.sh
- docker/localnode/scripts/step6_start_price_feeder.sh
- docker/rpcnode/Dockerfile
- on linux files created inside `build/generated` are owned by root - fixed it by providing the current user to the docker compose
- due to that everything is now stored under `/home/ubuntu` rather than `/root`
- `rm -rf build/generated` command is moved from Dockerfile to `deploy.sh` because it should be run on every cluster creation (correct me if I'm wrong)
- `HOME` env variable does not exist in Dockerfile during `docker build` phase - defined it
- to build `seid` faster the local `GOCACHE` is mounted inside the containers
Tested on Linux, please test on Darwin
> Fix docker setup for local cluster

- precompiles/pointer/pointer_test.go
- x/evm/state/state.go
- x/evm/state/state_test.go
- x/evm/state/statedb.go
Create a new event manager when snapshots are created so that events created in the new snapshot can be cleanly reverted when the snapshot itself is reverted.
Not apphash-breaking because events are not part of consensus
unit test
> Fork event manager when creating EVM snapshots

- contracts/hardhat.config.js
There has been a high occurrence of EVM integration tests flaking recently due to timeouts being exceeded during tests, this increases timeouts such that we no longer have this flakiness during the first run of integration tests where all of them are running at the same time.
CI
> Increase timeout for evm hardhat tests

- evmrpc/block.go
- evmrpc/block_test.go
- precompiles/pointer/pointer_test.go
- x/evm/client/wasm/query_test.go
- x/evm/types/message_evm_transaction_test.go
There are certain non-EVM transactions that may emit synthetic EVM events (e.g. CW20/721 executes that have an EVM pointer). For those transactions, we want to show them in `eth_getBlock` series of endpoints. Fields are populated on a best-effort basis and certain fields cannot be populated (e.g. signatures) due to the difference in the natures of EVM vs. non-EVM txs.
unit test
> Show CW transactions that have synthetic EVM events in eth_getBlock* response

- x/evm/ante/basic.go
- x/evm/ante/fee.go
- x/evm/integration_test.go
We want a failed tx to still bump account's nonce only if that tx is having a valid nonce and failing for other reasons. This PR adds a check so that the bump-for-failed logic only runs for txs with valid nonces.
unit test
> Check TX nonce before registering hook to bump nonce for failed tx

- precompiles/common/expected_keepers.go
- precompiles/common/precompiles.go
- precompiles/distribution/distribution_test.go
- precompiles/ibc/ibc_test.go
- precompiles/pointer/pointer.go
- precompiles/pointer/pointer_test.go
- x/evm/gov.go
- x/evm/keeper/params.go
- x/evm/keeper/pointer_upgrade.go
- x/evm/keeper/pointer_upgrade_test.go
- x/evm/migrations/migrate_all_pointers.go
- x/evm/migrations/migrate_all_pointers_test.go
Previously gas is tracked in two places for a pointer precompile call: the gas meter in `sdk.Context`, and `suppliedGas`. This PR unifies them into `sdk.Context` so that we don't miscount or double-count gas usage.
unit tests
> Properly handle gas in pointer precompile

- x/evm/migrations/migrate_deliver_tx_gas_limit.go
- x/evm/migrations/migrate_deliver_tx_gas_limit_test.go
- x/evm/module.go
- x/evm/module_test.go
> Add migration for new params

- x/evm/keeper/params.go
- x/evm/keeper/params_test.go
- x/evm/migrations/migrate_deliver_tx_gas_limit.go
> fix: use GetParamsIfExists() to fetch old params

- evmrpc/subscribe.go
To fix https://github.com/sei-protocol/sei-chain/issues/1850
There is a bug in how `fromHeight` is set during the websocket handler loop. Specifically each iteration will only look at the latest height if we don't set `filter.FromBlock` to the last height handled by the last iteration, so in the case where multiple heights have passed between two websocket iterations, events would be lost.
difficult to simulate latest height passing in unit test. Since this is an RPC-only change, we can apply it to the RPC node the bug reporter is using and see if the error is resolved
> Fix websocket from_height

- evmrpc/block.go
- evmrpc/block_test.go
This reverts https://github.com/sei-protocol/sei-chain/pull/1832/files#diff-905971bab6ab091b4980166748c8ef8aea28bd1d258321badd04c5d9644035c9 and fixes https://github.com/sei-protocol/sei-chain/issues/1859
> Revert showing wasm transactions in EVM rpc

- contracts/test/CW20toERC20PointerTest.js
- x/evm/keeper/msg_server.go
We need to call `Finalize` before writing receipts; otherwise receipts/events written in inner calls will not be visible for outer receipt writes
integration test
> Fix events in 2-hop scenarios

- proto/buf.lock
- proto/buf.yaml
Update `buf.yaml` dependencies to point to `buf.build/sei-protocol/cosmos-sdk` rather than `buf.build/cosmos/cosmos-sdk`
This PR should fix https://github.com/sei-protocol/sei-chain/actions/runs/10966410259
- local buf linting
- buf push (from local)
- ignite generate proto-go
> update buf.yaml dependencies

- evmrpc/block.go
Minor fix for issue where transaction bytes were showing up for synthetic txs on sei_getTransactionReceipt. This is what the error looks like:
```
curl http://127.0.0.1:8545 -X POST -H "Content-Type: application/json" --data '{"method":"sei_getBlockByNumber","params":["0x56A54",false],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"result":{"baseFeePerGas":"0x0","difficulty":"0x0","extraData":"0x","gasLimit":"0x12a05f200","gasUsed":"0x2da14","hash":"0xe1aadee07615cc4e6c7c4dbcd0311d020569f5b9cb03daab3cc80d3ee94e01c2","logsBloom":"0x000000000000000000020000000000000000100000000000000000010000000000000008000400000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000100000000400000 …
```
> fix tx byte arr in synthetic endpoints

- CHANGELOG.md
- app/upgrades.go
> Add v5.9.0 upgrade

- evmrpc/simulate.go
- evmrpc/simulate_test.go
- go.mod
- go.sum
There are cases when gas estimation needs to be done based on certain simulated states which cannot be statically inputted as state overrides. One example is to estimate gas for an ERC20 transferFrom while assuming the allowance is in place.
This PR (together with https://github.com/sei-protocol/go-ethereum/pull/35) adds a new endpoint `eth_estimateGasAfterCalls` to support such use cases.
unit test
> Add endpoint to estimate gas after simulating calls

- testutil/keeper/epoch.go
- x/epoch/types/codec.go
- x/evm/keeper/msg_server.go
- x/evm/module.go
- x/evm/module_test.go
- x/evm/types/codec.go
- x/mint/types/codec.go
- x/oracle/keeper/test_utils.go
- x/oracle/module.go
- x/oracle/types/codec.go
- x/tokenfactory/keeper/migrations_test.go
- x/tokenfactory/types/codec.go
This modifies the way the amino codec is used for custom modules to verify signatures. This will allow our custom modules to properly be amino signed and verified.
Local chain testing
> Fix amino registry for custom modules

- x/evm/migrations/migrate_eip_1559_params.go
- x/evm/migrations/migrate_eip_1559_params_test.go
Migration handler should update min base fee to 1gwei
unit tests
> EIP-1559: fix migration handler to update min base fee

- x/evm/ante/sig.go
This PR suppress the noisy error log for chainID mismatch, it is not a real error any more
> Suppress noisy chainID logs

- app/receipt.go
- app/seidb.go
- go.mod
- go.sum
- tools/migration/sc/migrator.go
- Make the lookup of GetDeliverTxHookWasmGasLimit use an infinite gas meter (10k gas)
- Use the DeliverTxHookWasmGasLimit parameter to govern the whole method, including
-   Setting Transient Receipt
-   Lookups like translating CW20 events
-   GetEVMAddressOrDefault
-   AppendToEvmTxDeferredInfo
> refactor: use wasm-to-evm gas limit for all interop operations

- go.mod
- go.sum
- tools/migration/sc/migrator.go
- Disables pruning of state store during sc migration
- Pruning previously didn't have an effect though since there is only 1 version for each key stored which won't get removed
- bump sei-cosmos to v0.3.43
- Tested on rpc nodes for sc migration
-
> Disable Pruning during SC migration + Bump Sei-cosmos

- app/app.go
> EIP-1559 - exclude cosmos txs from base fee calculation

- evmrpc/block_test.go
- evmrpc/filter.go
- evmrpc/filter_test.go
- evmrpc/info.go
- evmrpc/setup_test.go
Fixes this issue: https://github.com/sei-protocol/sei-chain/issues/1934
This PR fixes the case where there's a block with a synthetic tx followed by a normal evm tx, we would do an early return and skip the normal evm tx logs in the eth_getLogs endpoint. Instead, what we should do is simply skip the synthetic tx and return any normal evm logs later on in the block.
unit tests.
> bug fix: eth_getLogs missing events from early return

- app/receipt.go
- app/receipt_test.go
PR https://github.com/sei-protocol/sei-wasmd/pull/67 introduces a new event type indicating the pre-transfer owner of a CW721 token. This PR leverages the new event type to populate the owner topic of synthetic ERC721 transfer event correctly (previously it's set to the sender, which may be the spender and not the actual owner, and is against ERC721 convention).
Since events and receipts are not part of consensus state, this PR shouldn't be breaking app hash.
unit test
> Use owner event to populate ERC721 transfer topic

- evmrpc/simulate.go
- go.mod
- go.sum
geth changes: https://github.com/sei-protocol/go-ethereum/pull/36
fixes:
- https://github.com/sei-protocol/sei-chain/issues/1944
- https://github.com/sei-protocol/sei-chain/issues/1943
The https://github.com/sei-protocol/sei-chain/issues/1943 "address 0xxxx is not linked" issue is caused by not being able to retrieve the previous/parent block's statedb due to an association error. Instead of just erroring out completely, we want to still try our best to return a statedb for the parent block to run debug trace blocks on the current block.
The https://github.com/sei-protocol/sei-chain/issues/1944 "Nonce too low" issue is caused when a tx in the current block is not able to be traced. In this situation, we want to just skip over this tx and continue to trace other txs in the same block …
> bug fix: Be resilient to failing txs in debug trace block [main]

- cmd/seid/cmd/root.go
- tools/cmd.go
- tools/migration/cmd/cmd.go
- tools/migration/sc/migrator.go
- tools/migration/ss/migrator.go
- tools/migration/utils/helper.go
- tools/migration/wasm/keeper.go
This PR should fix the missing module for archive migration.
> Fix missing module for migration and add command to export IAVL

- aclmapping/confidentialtransfers/mappings_test.go
- proto/confidentialtransfers/query.proto
- x/confidentialtransfers/client/cli/query.go
- x/confidentialtransfers/client/cli/tx.go
- x/confidentialtransfers/keeper/msg_server_test.go
- x/confidentialtransfers/types/account.go
- x/confidentialtransfers/types/apply_pending_balance.go
- x/confidentialtransfers/types/initialize_account.go
- x/confidentialtransfers/types/msgs.go
- x/confidentialtransfers/types/msgs_test.go
- x/confidentialtransfers/types/query.pb.go
- x/confidentialtransfers/types/transfer.go
- x/confidentialtransfers/types/withdraw.go
We want users to have the ability to easily query a tx hash in it's decrypted state (if they have the private key)
This PR adds a seid method seid q ct tx <HASH> --from <USER> that queries a tx by it's hash, then decrypts it using the user's private key.
Manual testing using the updated seid
> Add query decrypted tx method to confidential transfers client

- app/receipt.go
- app/receipt_test.go
It is possible to have multiple ERC721 transfers in the same transaction. The previous implementation of owner replacement doesn't account for such scenarios and always use the last `pretransfer_owner` event to fill in owners for synthetic ERC721 events. This PR fixes it by assigning `pretransfer_owner` event to the correct transfer event based on order of appearance.
unit test that involves multiple transfers in a tx
> Assign owner correctly when there are multiple transfers

- precompiles/addr/addr.go
- precompiles/addr/addr_test.go
The `addr` precompile may use iterators for funds migration, so it's also eligible for dynamic gas calculation.
unit test
> use dynamic gas for address precompile

- evmrpc/filter.go
- evmrpc/filter_test.go
This PR add parallelization for eth_getLogs to speed up the query, especially on hundreds/thousands of blocks on archive node.
> Optimize getLogs with parallelization using fixed amount workers

- x/oracle/abci.go
- x/oracle/abci_test.go
- x/oracle/types/ballot.go
This fixes issues that can occur in the most extreme circumstances where extreme values used for cross rates can cause issues during oracle ballot calculations.
Unit test + docker cluster testing
> handle oracle overflow and rounding to zero for extreme values with cross rates

- evmrpc/filter.go
This PR fix the problem of panic, we should not panic in EVM getLogs, instead we can just update the error.
> Avoid panics in getLogs

- app/app.go
- evmrpc/README.md
- evmrpc/block.go
- evmrpc/block_test.go
- evmrpc/info_test.go
- evmrpc/server.go
- evmrpc/setup_test.go
- evmrpc/simulate.go
- evmrpc/tracers.go
- evmrpc/tracers_test.go
- evmrpc/tx.go
- evmrpc/tx_test.go
- go.mod
- go.sum
A panic tx is a tx which fails tracing. This can be due to several issues such as nonce errors, insufficient funds, etc. Adding 3 new endpoints for excluding panic txs.
- `sei_traceBlockByNumberExcludeTraceFail`
- `sei_getBlockByNumberExcludeTraceFail` + `sei_getBlockByHashExcludeTraceFail`
-  `sei_getTransactionByReceiptExcludeTraceFail`
Relies on https://github.com/sei-protocol/go-ethereum/pull/40
added unit tests in rpc layer + test on RPC node
> RPC endpoints for excluding tracing failures

- evmrpc/tracers_test.go
- go.mod
- go.sum
Small change to catch the panic at the top level of TraceTransaction and TraceCall. This way, if one of these panics, it will return more gracefully fail and print out a panic error message instead of "method handler crashed".
existing unit tests
> Catch panic in trace transaction / trace call

- evmrpc/info.go
- evmrpc/info_test.go
Our current eth_gasPrice uses the reward of the 50th percentile tx in the latest block as part of the calculation. This works decently well if the previous block is congested. However, if the previous block had only 1 tx where the user dramatically overpriced their tx, it will return a very high reward. This often causes our eth_gasPrice endpoint to jump around erratically.
This change uses the previous block's total gas used to determine if the block is congested. If the previous block is congested, we will use the previous logic of 50% of reward. Otherwise, eth_gasPrice now pulls the latest base fee and increases it by 10% to ensure the user's tx can be included in a timely manner without dramatically overpaying.
This also makes a similar adjustment to `eth_maxPriorityFeePerGas` where …
> Fix volatile eth_gasPrice

- x/evm/module.go
- x/evm/module_test.go
This PR reverts the migration handler for RemoveTxHashes.
> Revert evm migration for RemoveTxHashes

- Makefile
To link https://github.com/fjl/memsize with go 1.23 a workaround is needed.
> fix linking with go 1.23+

- Dockerfile
We currently override wasmvm depenency with a fork based on an older version of wasmvm.
Tested locally by running
```
docker build . -t sei-protocol/sei:latest --progress=plain --no-cache
```
Fixes SEI-8836
> Fixed extracting the wasmvm release version in the Dockerfile (SEI-8836)

- integration_test/confidential_transfers_module/apply_pending_balance_test.yaml
- integration_test/confidential_transfers_module/close_account_test.yaml
- integration_test/confidential_transfers_module/ct_precompile_queries.yaml
- integration_test/confidential_transfers_module/deposit_test.yaml
- integration_test/confidential_transfers_module/initialize_account_test.yaml
- integration_test/confidential_transfers_module/transfer_test.yaml
- integration_test/confidential_transfers_module/withdraw_test.yaml
- x/confidentialtransfers/keeper/msg_server.go
- x/confidentialtransfers/keeper/msg_server_test.go
We return error code `38` not found for case when account found and exists (on account initialization).
Changing this to be `18` invalid request
- unit test
- integration test
> Fix account not found error code

- run_blocktests.sh
We originally removed some block tests because they were failing due to us removing the full refund of unused gas (https://github.com/sei-protocol/sei-chain/pull/1871/files#diff-0adc342d2882ffb81750cb8734fb7ab5c0a7393082b452370b3aacff3df49777R37-R39). However, we've reverted that change, so adding back these tests.
existing tests
> Add back block tests removed from partial refund

- precompiles/confidentialtransfers/ct.go
- x/confidentialtransfers/client/cli/query.go
- x/confidentialtransfers/types/transfer.go
Updating `ct tx` command to support EVM transactions decryption
- local testing
- unit tests for existing refactored code
> Ct EVM transactions decryption

- app/receipt.go
- app/receipt_test.go
It is possible for a single WASM event to contain multiple actions, so we should be translating each action, instead of each WASM event, into individual EVM logs. This PR changes the translation logic as such.
unit test
> Extract multiple EVM logs from a single WASM event

- evmrpc/block.go
- evmrpc/block_test.go
- evmrpc/server.go
Add a new version of `sei2_getBlock...` endpoints that include bank transfers. Specifically any `usei` bank transfer will show up as  a transaction in the `transactions` field of the `_getBlock` responses, with `from` being the sender, `to` being the recipient, and `input` being the amount (serialized as bytes and in terms of wei)
unit test
localsei
> add sei2_getBlock endpoints to include bank transfers

- evmrpc/info.go
- x/evm/keeper/receipt.go
- x/evm/keeper/receipt_test.go
Add GetReceiptWithRetry to imrove conditions where receipts may not be immediately available after transaction execution. This improves reliability of receipt retrieval by implementing a retry mechanism(3 by default) with linear backoff. 
NOTICE this may not 100% eliminating the `not found` error as we do 3 max retries.
1. Added unit test TestGetReceiptWithRetry 
2. Confirmed `ab -n 100000 -c 100 -T "application/json" -p request.json <endpoint>` got 100% successful rate.
> fix: eth_gasPrice not found

- app/receipt.go
- evmrpc/filter.go
- evmrpc/tx.go
- x/evm/keeper/log.go
- x/evm/keeper/log_test.go
Previously if we have two EVM transactions in the same block, each with 1 log, both logs will have log index of 0, because log index was set relative to each transaction. The expected behavior is for log index to be set across transactions in a block (i.e. the log of the first tx would have index 0, whereas the log of the second would have index 1).
It is not quite feasible to set log index as such during execution though, because transactions may be processed in parallel, so this PR adds backfill log on the read path instead.
unit test
> Set log index across all transactions in a block

- x/evm/keeper/tx.go
- x/evm/keeper/tx_test.go
- x/evm/module.go
Remove 100 tx hashes every block until all tx hashes are deleted.
unit test
> Add logic to remove a small number of tx hashes each block

- evmrpc/simulate.go
- evmrpc/simulate_test.go
Currently if one calls `trace_` or gas simulation endpoints with block number parameter being `safe` or `latest`, it would fail with a message like `height must be greater than zero (requested height: -4)`. This PR makes such keywords acceptable for these endpoints.
unit test
> Allow safe/latest/final to be passed as block number to trace/simulate endpoints

- aclmapping/confidentialtransfers/mappings.go
For increased determinism, this PR adds the appropriate ACL mappings to the initializeMessage method in the CT Module
Unit tests
> Add ACL Mappings for InitializeAccount

- app/app.go
- app/app_test.go
- evmrpc/server.go
- evmrpc/simulate.go
- evmrpc/tests/block_test.go
- evmrpc/tests/mock_accounts.go
- evmrpc/tests/mock_client.go
- evmrpc/tests/mock_contracts.go
- evmrpc/tests/tx.go
- evmrpc/tests/utils.go
- go.mod
- go.sum
- occ_tests/utils/utils.go
- precompiles/pointer/pointer_test.go
- precompiles/setup.go
- x/evm/ante/fee.go
- x/evm/keeper/evm.go
- x/evm/keeper/keeper.go
- x/evm/keeper/msg_server.go
- x/evm/keeper/pointer_upgrade.go
- x/evm/module.go
It's becoming difficult to add new RPC tests due to the way old tests are set up. This PR creates a new framework for adding RPC unit tests where it allows spinning up independent server threads and more authentic data mocking.
One thing to call out is that this refactor requires our custom precompiles to be loaded dynamically rather than through a global variable (so that it's possible to have independent concurrent servers across multiple tests)
unit test
> Refactor RPC tests

- evmrpc/server.go
- evmrpc/setup_test.go
- evmrpc/subscribe.go
- evmrpc/subscribe_test.go
Fixed the following:
- use block gas limit instead of the sum of all txs gas limit for the `gasLimit` field in new header subscription response
- populate base fee per gas now that we've implemented EIP1559
unit test
> Fix RPC subscription fields

- loadtest/contracts/deploy_erc20.sh
- loadtest/contracts/deploy_erc721.sh
- loadtest/contracts/evm/remappings.txt
- loadtest/main.go
- loadtest/types.go
- script outputs the address of the deployed contract, but needed trim
- lower level invocations were emitting warnings which messed up address parsing
- forge now requires --broadcast for the deploy (create) command
- uniswap deploy was clearing out all previously-deployed addresses from the config
- loadtesting env
> fix loadtest for erc20s

- go.mod
- go.sum
> Bump tendermint to v0.5.4

- evmrpc/state.go
- evmrpc/tests/state_test.go
When users query balances (or other states) with a future block height, the expected behavior is an error instead of returning the latest state.
unit test
> disallow future block number to be passed to balance queries

- evmrpc/filter.go
- evmrpc/filter_test.go
- evmrpc/setup_test.go
- evmrpc/tests/log_test.go
Instead of silently returning a truncated list of logs, we will explicitly return an error when log requests are made with ranges that are too wide per RPC provider's config.
unit tests
> return error when log requested with too wide ranges

- app/app.go
- app/mev.go
- app/utils.go
- cmd/seid/cmd/root.go
This PR implements logics to allow validators to dynamically load MEV handlers without having to fork sei-chain. Specifically a new section `mev` is added to `app.toml`. If a validator wishes to have custom MEV logic, they would need to compile encapsulate their logic in a library that follows the rules below:
- defines a custom struct that implements the MEVHandler interface introduced in this PR
- creates a singleton object of the custom struct that's named `HandlerInstance`
- build their library as a plugin.
An example can be found in https://github.com/sei-protocol/mev-demo, which can also be used as a template/starting point for validators to develop their own MEV plugins.
localnet with mev-demo
> Add plugin-based MEV handler support

- app/app.go
- cmd/seid/cmd/root.go
- evmrpc/mev.go
- evmrpc/server.go
- evmrpc/setup_test.go
- evmrpc/tests/utils.go
- mev/mev.go
This PR adds an additional functionality to the MEV plugin interface to allow custom logic for MEV submission via rpc. A new RPC endpoint `mev_submission` is added (which will return error if called on a node without any MEV plugins). An example implementation of the new interface method can be found in https://github.com/sei-protocol/mev-demo/blob/main/plugin.go#L28
localnet with mev-demo
> Add capability for MEV plugin to accept submission via RPC

- evmrpc/simulate.go
- evmrpc/tests/tracers_test.go
- go.mod
- go.sum
related issue: https://github.com/sei-protocol/sei-chain/issues/2116
tracer endpoints were incorrectly using the RLP hash as the block hash in responses. This PR changes the logic so that the tendermint block hash is used to overwrite the block hash in responses.
unit test
> overwrite block hash in tracer response with tendermint block hash

- x/oracle/ante.go
- x/oracle/keeper/keeper.go
- x/oracle/keeper/keeper_test.go
Multiple concurrent CheckTx calls can break through the previous oracle spam prevention implementation because getting and setting are not atomic. This PR makes the check-and-set operation atomic.
unit test
> Harden oracle tx spam prevention

- evmrpc/filter.go
- evmrpc/tests/log_test.go
overwrite txIndex on logs in getLogs response based on the number of txs that are relevant
unit test
> Fix getLog&getReceipt txIndex mismatch

- evmrpc/block.go
- evmrpc/filter.go
- evmrpc/subscribe.go
- evmrpc/utils.go
- evmrpc/utils_test.go
Panics from unmanaged goroutines could crash the entire process. This PR recovers such panics. The panics are also logged from further investigation because in general there shouldn't be any.
unit test
> Recover panics from unmanaged goroutines

- app/invariance.go
- oracle/price-feeder/oracle/filter.go
- oracle/price-feeder/oracle/oracle.go
- oracle/price-feeder/oracle/provider/binance.go
- oracle/price-feeder/oracle/provider/coinbase.go
- oracle/price-feeder/oracle/provider/crypto.go
- oracle/price-feeder/oracle/provider/gate.go
- oracle/price-feeder/oracle/provider/huobi.go
- oracle/price-feeder/oracle/provider/kraken.go
- oracle/price-feeder/oracle/provider/mexc.go
- oracle/price-feeder/oracle/provider/okx.go
- precompiles/bank/bank.go
- precompiles/bank/legacy/v562/bank.go
- precompiles/bank/legacy/v580/bank.go
- precompiles/bank/legacy/v600/bank.go
- precompiles/bank/legacy/v603/bank.go
- precompiles/bank/legacy/v606/bank.go
- tools/migration/ss/migrator.go
- utils/metrics/metrics_util.go
- utils/panic.go
- x/evm/keeper/msg_server.go
If metrics calls panics (e.g. integer overflow), it could lead to uncaught cascading on the critical path and thus crash the whole process. This PR adds a catcher for such panics and prints stack when it does happen (should be rare)
no functional change
> Prevent panics by metrics calls from crashing the process

- evmrpc/info.go
- evmrpc/info_test.go
When eth_feeHistory is called on blocks that are empty, the endpoint returns an empty array instead of "0x0".
unit tests
> [SEI-9691] fix eth_feeHistory empty blocks

- evmrpc/tests/mock_client.go
- evmrpc/tests/tx_test.go
- evmrpc/tx.go
Non-EVM transactions should be skipped when counting for transaction index in `eth_getTransactionByHash|Number` calls
unit tests
> Fix tx index in getTransactionByHash response

- evmrpc/tests/tx_test.go
- evmrpc/tx.go
Transactions that failed ante handler will change no state and thus should not be considered as "included in a block". So we should exclude them when querying `eth_getTransaction...` endpoints, which is consistent with `eth_getBlock...`
unit test
> exclude transactions that failed ante from getTransaction

- Dockerfile
- Makefile
- contracts/test/SeiSoloTest.js
- contracts/test/lib.js
- precompiles/solo/solo.go
- precompiles/solo/solo_test.go
- x/evm/client/cli/native_tx.go
- x/evm/client/cli/tx.go
Instead of only requiring MsgClaim to be properly signed, we also need to enforce that it's signed by the specified sender.
unit/integration tests
> Require MsgClaim sender to match signer

- x/oracle/abci.go
- x/oracle/abci_test.go
- x/oracle/tally.go
This updates oracle tally logic to behave properly in edge case scenarios. Additionally, we rework the validator iteration to be more performant for cases with larger numbers of total validators with a limited active set.
Added unit tests to verify behavior
> [SEI-9824][SEI-9825] Update oracle MidBlock logic

- Makefile
- docker/docker-compose.yml
- docker/localnode/scripts/deploy.sh
- docker/localnode/scripts/step0_build.sh
- scripts/initialize_local_chain.sh
- x/evm/state/balance.go
This allows for mocking EVM balances using a compile-time flag for testing purposes. 
Tested using the intiialize_local_chain script
> [SEI-10041] Add compile flagged mock balance testing functionality

- x/evm/state/state.go
It was originally added to ensure snapshots immutability but it's not necessary since the contract within EVM is for the caller to be responsible for taking snapshots. 
This change is not supposed to cause any logical changes and may have some performance benefits
no logical change; existing tests should still pass
> Do not take a new snapshot upon RevertToSnapshot

- evmrpc/tests/tx_test.go
- evmrpc/tx.go
We changed the logic to get baseFeePerGas for block endpoints but not tx endpoints
unit tests
> Fix gas price mismatch in RPC responses

- x/evm/ante/sig.go
- x/evm/ante/sig_test.go
Pending transactions may become invalid if the state that they run CheckTx on became invalid, which is especially common with balances.
unit test & local sei cluster
> Reject pending transactions if sender doesn't have sufficient funds

- evmrpc/association.go
- evmrpc/block.go
- evmrpc/config.go
- evmrpc/config_test.go
- evmrpc/filter.go
- evmrpc/info.go
- evmrpc/net.go
- evmrpc/rpcstack.go
- evmrpc/send.go
- evmrpc/server.go
- evmrpc/simulate.go
- evmrpc/state.go
- evmrpc/stats/tracker.go
- evmrpc/stats/tracker_test.go
- evmrpc/subscribe.go
- evmrpc/tests/utils.go
- evmrpc/tracers.go
- evmrpc/tx.go
- evmrpc/txpool.go
- evmrpc/utils.go
- every interval (default = 10s)
- can be overridden with `rpc_stats_interval` setting
- logs success/fail, avg & max duration, count, by method, by connection type (ws | http)
- requests are bucketed by a truncated interval (to 10s interval)
- requests are bucketed by _completion_ time to simplify bucketing 
- summarizes success/fail and count across methods
- bug fixes
- fixed double-metric-reporting of get-block-by-number
- fixed capturing panic as errors
- fixed capturing certain errors as errors
- Initially I implemented this with middleware, but that doesn't work for websockets
- For now, left the `recordMetrics` pattern 
- avg and max are preferred to limit performance issues of bookkeeping
- if the channel is full (should never be), we drop events for safety (and log)
- added unit …
> Add periodic rpc stats logs

- .github/workflows/integration-test.yml
If a test times out after 30m it'd have a status of cancelled, which is not caught by our check and thus would allow the PR to be merged
> disallow cancelled integration test to pass CI

- app/test_helpers.go
- contracts/test/CW20toERC20PointerTest.js
- contracts/test/ERC20toCW20PointerTest.js
- contracts/test/ERC721toCW721PointerTest.js
- evmrpc/block.go
- evmrpc/block_test.go
- evmrpc/config.go
- evmrpc/filter.go
- evmrpc/filter_test.go
- evmrpc/server.go
- evmrpc/solidity/ERC20.sol
- evmrpc/solidity/IAddr.sol
- evmrpc/solidity/IJson.sol
- evmrpc/solidity/IWasmd.sol
- evmrpc/solidity/MixedLogTester.sol
- evmrpc/subscribe_test.go
- evmrpc/tests/logindex_test.go
- evmrpc/tests/tx.go
- evmrpc/tests/tx_test.go
- evmrpc/tests/utils.go
- evmrpc/tx.go
- evmrpc/utils.go
- x/evm/keeper/log.go
- x/evm/module.go
We've decided to always include ALL logs (synthetic or not) from an EVM transaction in any relevant `eth_` endpoint's response, because if one initiates an ERC20 transfer for example, they'd expect a Transfer event even if it's synthetic.
This change is cherry-picked from [v6.1.10](https://github.com/sei-protocol/sei-chain/pull/2363), plus:
- modify EVM-only bloom calculation from only non-synthetic logs on EVM txs to ALL logs on EVM txs, to be consistent with what we return for EVM txs now. (this change makes this PR app hash breaking)
unit test
> always include synthetic logs in eth_ endpoints

- .github/workflows/pr-to-slack-codex.yml
- fixes this error on codex github check
```
The --api-key flag is no longer supported. Pipe the key instead, e.g. `printenv OPENAI_API_KEY | codex login --with-api-key`.
```
- this pr execution
> Fix github action codex check (updated CLI)
